### ISSUE TITLE
Please Add redirect-stream

### ISSUE THREAD

**Issue by Shinmera** [quicklisp/quicklisp-projects#1003]
This is a very simple implementation of a gray stream that redirects all stream operations it receives to another stream.

Author: Nicolas Hafner
Source: https://github.com/Shinmera/redirect-stream.git
Documentation: https://shinmera.github.io/redirect-stream/

**Comment by guicho271828** [comment]
sounds like (make-two-way-stream (make-broadcast-stream s) (make-concatenated-stream s)) when s is a two way stream.

**Comment by Shinmera** [comment]
How would you change out the stream of a broadcast stream? That's the main purpose of this library; to allow you to switch out which stream it redirects the output to in the end.
