### ISSUE TITLE
Please Add Qtools-UI

### ISSUE THREAD

**Issue by Shinmera** [quicklisp/quicklisp-projects#1010]
This is a collection of useful widgets and pre-made components for use in Qt applications.

Author: Nicolas Hafner
Source: https://github.com/Shinmera/qtools-ui.git
Documentation: https://shinmera.github.io/qtools-ui/

**Comment by quicklisp** [comment]
Sure.

No screenshots?

**Comment by Shinmera** [comment]
I plan to add that once I have things incorporated into Parasol.
There's two really simple videos of some of the components that I recorded a while back:
https://www.youtube.com/watch?v=KwASFOhYta4&list=PLkDl6Irujx9Mh3BWdBmt4JtIrwYgihTWp&index=7
https://www.youtube.com/watch?v=DuVv97ACfnI&list=PLkDl6Irujx9Mh3BWdBmt4JtIrwYgihTWp&index=6

**Comment by quicklisp** [comment]
A few of the systems fail. Log is here: http://report.quicklisp.org/2015-12-07/failure-report/qtools-ui.html#qtools-ui-options
