### ISSUE TITLE
Please use my bugfixed version of cl-gambol

### ISSUE THREAD

**Issue by thezerobit** [quicklisp/quicklisp-projects#1011]
A couple years back, I tried using the cl-gambol library and found it to be rather buggy. I went about fixing all the bugs I found and cleaning up the code. The version in quicklisp is buggy enough to be unusable. Please use my fork instead (it does have a higher version number):
git@github.com:thezerobit/cl-gambol.git

The reason I bring this up now is that someone emailed me with a question about cl-gambol (must've found it on github assuming I was the original author). Their trivial program was crashing with a nonsensical error (using quicklisp's current cl-gambol), and when I ran it against my version, it worked fine. That's evidence to me that the world would benefit from having a less buggy version of cl-gambol in quicklisp.

**Comment by quicklisp** [comment]
Can you please add :description to the system file?

**Comment by quicklisp** [comment]
Any word on this?

**Comment by thezerobit** [comment]
Done!, sorry, didn't see this.
