### ISSUE TITLE
cl-create

### ISSUE THREAD

**Issue by cl-porky11** [quicklisp/quicklisp-projects#1013]
I made this: https://github.com/cl-porky11/cl-create
Please add it.

**Comment by quicklisp** [comment]
I don't normally remark on the quality of submissions, but this particular project seems spectacularly misguided. Do you have any projects that use CL-CREATE instead of make-instance? Could I see the code to see how it looks?

**Comment by marcoxa** [comment]
Definitively nothing new!  Not that NEW-OP was new either :)  But at least it was fun to write it :)

MA

**Comment by quicklisp** [comment]
Any feedback on this @cl-porky11?

**Comment by cl-porky11** [comment]
I wasn't online for some time.
I used it, but started to rewrite the project. Not sure, if I'll use it again
