### ISSUE TITLE
cl-textmagic

### ISSUE THREAD

**Issue by trumae** [quicklisp/quicklisp-projects#1014]
cl-textmagic is a simple implementation of textmagic api for use of SMS in common lisp

https://github.com/trumae/cl-textmagic

**Comment by quicklisp** [comment]
Can you please add :description to the system file?

**Comment by trumae** [comment]
Done.

Thanks,
   Trumae

On Sun, Dec 6, 2015 at 7:49 PM, Zach Beane <notifications@github.com> wrote:

> Can you please add :description to the system file?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/quicklisp/quicklisp-projects/issues/1014#issuecomment-162351127>
> .
>



-- 

/*__   ____   _____  __ */ float e,a,b,c,d;main(i){for(;b<4;b+=.1){for(a=0;
/*\ \ / /\ \ / /|  \/  |*/ a<4;a+=.06){c=d=0;for(i=99;--i&&c*c+d*d<4;)e=c*c
/* \ V /  \ V / | |\/| |*/ -d*d+a-2,d=2*c*d+b-2,c=e;putchar("X =."[i&3]);}
/*  \_/    \_/  |_|  |_|<trumae@gmail.com> */ puts("");}}
