### ISSUE TITLE
Please check (and maybe re-add) CL-ENUMERATIONS

### ISSUE THREAD

**Issue by marcoxa** [quicklisp/quicklisp-projects#1019]
Hello

I am finally getting back to hack a bit on my projects on CLNET.  Just to test that everything is I think it should be, could you check CL-ENUMERATIONS?  (My other libraries will follow).

According to CLNET GitLab you now need to issue a git clone on either

git@common-lisp.net:cl-enumeration/enumerations.git
https://gitlab.common-lisp.net/cl-enumeration/enumerations.git

I believe the version should be ok, although I get a pesky STYLE-WARNING from SBCL, which I frankly do not understand (I believe it is related to some issue in adding keyword args to methods).

Thanks

Marco

**Comment by quicklisp** [comment]
This has been fetching from gitlab for a while.

**Comment by marcoxa** [comment]
Ok.  Thanks.  Just checking that I did not have to do anything special for
the GitLab setup on cl.net.

MA

On Sun, Dec 6, 2015 at 10:15 PM, Zach Beane <notifications@github.com>
wrote:

> This has been fetching from gitlab for a while.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/quicklisp/quicklisp-projects/issues/1019#issuecomment-162353640>
> .
>



-- 
Marco Antoniotti
Somewhere over the Rainbow
