### ISSUE TITLE
Change bordeaux-threads upstream

### ISSUE THREAD

**Issue by deadtrickster** [quicklisp/quicklisp-projects#1025]
Lets change it to https://github.com/sionescu/bordeaux-threads
New 0.8.4 tagged three months ago.

**Comment by stassats** [comment]
It was recently changed to use https://common-lisp.net/project/bordeaux-threads/releases/bordeaux-threads.tar.gz but it doesn't contain the latest release. And 0.8.4 is pretty important, it includes the timeout parameter.
