### ISSUE TITLE
Please update gsll

### ISSUE THREAD

**Issue by federico-lox** [quicklisp/quicklisp-projects#1026]
Currently quicklisp pulls gssl at the following revision:
https://gitlab.common-lisp.net/antik/gsll/commit/b2f6ae1f (2 years old)

That version suffers from wrong paths on OSX which makes installing this library and cl-ana quite frustrating.

The following commits fix those issues:
https://gitlab.common-lisp.net/antik/gsll/commit/0b40843707902636b0bda5290e61cae038ac35a6
https://gitlab.common-lisp.net/antik/gsll/commit/ad5409ec81f4af0c60d78ebe8a163748c65c61f6

The latest version (2 days ago) also fixes compat issues on Windows:

https://gitlab.common-lisp.net/antik/gsll/commit/6e6df93e591079419950f480c775cd58c644d6b2

**Comment by quicklisp** [comment]
Quicklisp tracks the master branch, so it will automatically get the recent updates.

**Comment by federico-lox** [comment]
Follow up question: the last time gsll's master branch was pulled out seems to be May 5th 2015:
```lisp
(ql:update-dist "quicklisp") 

; You already have the latest version of "quicklisp": 2015-10-31.

(ql:quickload "gsll")

; Notice the date and commit hash in the URI
; Fetching #<URL "http://beta.quicklisp.org/archive/gsll/2015-05-05/gsll-master-b2f6ae1f-git.tgz">
; 303.92KB
```

When will gsll's master be pulled down next and be made available on beta.quicklisp.org?

**Comment by quicklisp** [comment]
gsll's master branch was pulled down on 2015-10-31. It did not differ from the 2015-05-05 version, so there was no change on that date. The next update is tomorrow, 2015-12-13, and it will use the master branch from that date.

**Comment by federico-lox** [comment]
The Mac OSX fix is on master since 5 months ago (so earlier than 2015-10-31):

https://gitlab.common-lisp.net/antik/gsll/commit/ad5409ec81f4af0c60d78ebe8a163748c65c61f6

Given the explanation above I am still not sure why quicklisp 2015-10-31 dist pulls down a 2-years old version of gsll's master.

Did the update happen on 2015-12-13? *(ql:dist-update "quicklisp")* results in:

*You already have the latest version of "quicklisp": 2015-10-31*

**Comment by quicklisp** [comment]
This should be set - let me know if it's not.
