### ISSUE TITLE
Please add QUUX-HUNCHENTOOT

### ISSUE THREAD

**Issue by phmarek** [quicklisp/quicklisp-projects#1031]
> QUUX-HUNCHENTOOT is a set of extensions to Hunchentoot. Currently, the only published extension is a thread-pooling taskmaster.

As this is even referenced in Hunchentoot's documentation, having that packages too would be really nice!

Thanks a lot.

**Comment by phmarek** [comment]
Documentation at https://common-lisp.net/project/qitab/

Sources at https://gitlab.common-lisp.net/qitab/quux-hunchentoot

**Comment by phmarek** [comment]
I just noticed that `QUUX-HUNCHENTOOT` is no longer available; is that because `LIL` is removed?

Could all required libraries for `Q-H` get added again, please?


Thanks a lot!

**Comment by phmarek** [comment]
I just pushed a Merge request that removes the `LIL` dependency; perhaps that is a good candidate.
https://gitlab.common-lisp.net/qitab/quux-hunchentoot/-/merge_requests/2

**Comment by quicklisp** [comment]
It got removed because it doesn't build - when it builds again, I can
re-add it.

**Comment by phmarek** [comment]
Well, it works for me -- even better (because the `LIL` dependency is removed) with my PR above.

Where can I see the error? http://report.quicklisp.org/ doesn't have it any more...
