### ISSUE TITLE
Please add Varjo

### ISSUE THREAD

**Issue by cbaggers** [quicklisp/quicklisp-projects#1055]
Please add varjo to quicklisp, it can be found here: https://github.com/cbaggers/varjo/tree/release-quicklisp

Varjo can compile a subset of common lisp to glsl. It supports functions, macros, type inference & basic flow analysis.

Please can quicklisp pull from the `release-quicklisp` branch. The `master` branch is *not* in a state to be in quicklisp.

Varjo also depends on rtg-math which has quicklisp-projects issue #1054

Thanks folks, quicklisp is awesome

**Comment by quicklisp** [comment]
Varjo has been in Quicklisp for a while. I'll update to use the release-quicklisp branch.

**Comment by cbaggers** [comment]
Oh thanks! I forgot that I had requested that.
