### ISSUE TITLE
Please Add pathname-utils

### ISSUE THREAD

**Issue by Shinmera** [quicklisp/quicklisp-projects#1058]
This is a collection of common tests and operations to help handling pathnames.

Author: Nicolas Hafner
Source: https://github.com/Shinmera/pathname-utils.git
Documentation: https://shinmera.github.io/pathname-utils/

**Comment by quicklisp** [comment]
A style note. The convention in common lisp is to omit a hyphen when making a predicate out of a single word, e.g. LOGICALP rather than LOGICAL-P.

**Comment by Shinmera** [comment]
The convention I follow and have always followed for my libraries is to hyphenate all predicates.
