### ISSUE TITLE
clsql-oracle

### ISSUE THREAD

**Issue by quicklisp** [quicklisp/quicklisp-projects#106]
Update build environment to include oracle support so clsql-oracle builds.

**Comment by josrr** [comment]
If you are using the instanclient 12.1 in Linux maybe you need to change the names of the libraries in oracle-loader.lisp:24 to (list "libclntsh" "libociei").

**Comment by quicklisp** [comment]
That didn't work for me on my debian system - I installed instant-client for x86-64, but clsql fails with

      Couldn't load foreign libraries "libclntsh", "oci". (searched *FOREIGN-LIBRARY-SEARCH-PATHS*: NIL)

libclntsh.so shows up in ldconfig -v output, but Lisp loading fails. I'm not sure if it's a problem with my OS setup, or what.

**Comment by quicklisp** [comment]
It's been too long and I still can't get this working. Time for a new issue if someone can make it work easily on the latest debian stable.
