### ISSUE TITLE
Please add cl-bunny

### ISSUE THREAD

**Issue by deadtrickster** [quicklisp/quicklisp-projects#1060]
RabbitMQ client. Please use latest tag when building dist.

https://github.com/cl-rabbit/cl-bunny

**Comment by quicklisp** [comment]
I can't easily use a latest tag. Can you make releases?

**Comment by quicklisp** [comment]
To be clearer, I mean github releases, not a tar.gz on a website somewhere.

**Comment by deadtrickster** [comment]
AFAIK github creates releases from my tags automatically: https://github.com/cl-rabbit/cl-bunny/releases also could you please you releases for https://github.com/cl-rabbit/cl-amqp also?

**Comment by quicklisp** [comment]
I don't know why github shows the releases tab like that - through the API, it shows no releases. You have to do something extra to make a tag a release, but I'm not sure what. See for example https://github.com/slime/slime/releases - it looks much different from your releases page.

**Comment by deadtrickster** [comment]
Looks like release have to be created using github interface. I've created one for both https://github.com/cl-rabbit/cl-bunny/releases and https://github.com/cl-rabbit/cl-amqp/releases I hope this solves the issue
