### ISSUE TITLE
hu.dwim.sdl

### ISSUE THREAD

**Issue by attila-lendvai** [quicklisp/quicklisp-projects#1069]
branched-git git://github.com/attila-lendvai/hu.dwim.sdl.git quicklisp

it's a complete FFI for https://libsdl.org/ which is a platform independent abstraction layer to game related features around graphics, like displaying and drawing stuff, image file formats, drawing with truetype fonts, etc.

it's needed for the new version of projectured.

It requires the cffi/c2ffi changes merged into CFFI (at the time of writing it's only in master, not in a CFFI release yet).

**Comment by quicklisp** [comment]
Partly builds, but I get this:

    ;   READ error during COMPILE-FILE: Symbol "ENABLE-CASE-PRESERVING-SYNTAX" not 
        found in the HU.DWIM.SYNTAX-SUGAR package

**Comment by attila-lendvai** [comment]
pulled some changes over to the live repos, one of them should fix it.

**Comment by quicklisp** [comment]
This works now.

**Comment by attila-lendvai** [comment]
great, thanks a whole lot!
