### ISSUE TITLE
s-xml-rpc seems unmaintained, link to my new repo with some fixes?

### ISSUE THREAD

**Issue by ibawt** [quicklisp/quicklisp-projects#1075]
The common-lisp web page for it has dead links, I needed to add a datatype to it for my own use.  I thought maybe other people would like it now?

I added the code in a github repo https://github.com/ibawt/s-xml-rpc .  I'm not sure what happens with dead projects.  I'd prefer to contribute back to the original authors but I can't seem to find current links.

**Comment by quicklisp** [comment]
The author is Sven van Caekenberghe, his github page is https://github.com/svenvc - can your reach out to him and ask to be the new maintainer?

**Comment by quicklisp** [comment]
Any update on this?

**Comment by ibawt** [comment]
@quicklisp no, I still have the fixes there but my project that was driving them dried up.  I'll close for now, but I'll leave my repo up in case someone spelunks through and finds it. 

Thanks for running quicklisp !
