### ISSUE TITLE
how to quicklisp package in CGI

### ISSUE THREAD

**Issue by springkim** [quicklisp/quicklisp-projects#1076]
i tried to install 2 packages
"lisp-cgi-utils" , "pg" 
and this is my script

=============
#!/usr/bin/clisp
(load "/home/kimbom/.clisprc.lisp")
(with-open-file
        (*standard-output* "/dev/null" :direction :output :if-exists :supersede)
               (ql:quickload "lisp-cgi-utils")
                (ql:quickload "pg"))

(format t "Content-Type: text/html; charset=UTF-8~%~%~%")
(princ (html:html-header "html.lisp example page"))

(princ (html:body
        (html:h1 "test page for html.lisp package")
        (html:h2 "lists")
        (html:ul
         (html:li "first entry")
         (html:li "second entry"))
        (html:p "a simple paragraph" " and more text")
        (html:p '((class . "tester")) "another one")))
(princ (html:html-footer))
(bye)
=================

it works!! very well

but in Apache2 it doesn`t work...

maybe the apache2 can`t load  .clisprc.lisp file

so how can i include quicklisp module in CGI ?

please help me

**Comment by quicklisp** [comment]
Sorry, you will have to try some other place for troubleshooting CGI problems. It is not related to Quicklisp.
