### ISSUE TITLE
portaudio - problem on OSX 10.11

### ISSUE THREAD

**Issue by p2p3p4** [quicklisp/quicklisp-projects#1080]
Using Clozure CL, trying to
(ql:system-apropos "audio")
#<SYSTEM cl-portaudio / cl-portaudio-20131003-git / quicklisp 2016-02-08>
[...]
? (ql:quickload "cl-portaudio")
[...]
> Error: Unable to load foreign library (LIBPORTAUDIO).

seems there are problems making libportaudio under OSX 10.11

**Comment by quicklisp** [comment]
Sorry - you must install libportaudio to make it work. That is not directly Quicklisp-related.
