### ISSUE TITLE
please add eazy-opencl

### ISSUE THREAD

**Issue by guicho271828** [quicklisp/quicklisp-projects#1082]
OpenCL binding for Common Lisp CFFI.

https://github.com/guicho271828/eazy-opencl

A lisp-C converter is also on the way (https://github.com/gos-k/oclcl), but it is not in a publishable state yet.

**Comment by quicklisp** [comment]
I installed OpenCL headers but I get build warnings, which break the build. Log is here: http://report.quicklisp.org/2016-03-01/failure-report/eazy-opencl.html

**Comment by guicho271828** [comment]
hmm, which OpenCL headers? Additional information may be helpful. OpenCL has many variations.

First of all, I'd like to know the output of `clinfo` on your system. It should be present in the PATH if OpenCL was installed successfully.

Next, I'd like to know a few details of your setup. Examples:
+ `*features*` , which would contain several flags added by eazy-opencl, representing the OpenCL version.
+ the vendor/version of the OpenCL ICD (Installable Client Driver) loader you have installed
+ the vendor/version of the header files (where/how did you get it?)
+ what kind of devices are present in your system? There is a huge degree of freedom here: Your system could have both an Intel internal graphics and an nVidia GPU. Each of them may or may not support OpenCL. Either of the driver may or may not support OpenCL. Were it be supported, it could be missing on the system. Their OpenCL version compatibility may be different. Finally, in any case, there might be a CPU with >SSE2, which may also be OpenCL compatible and there is an ICD loader installed on your system (by default).

**Comment by guicho271828** [comment]
as a note, I have tested eazy-opencl on Thinkpad X61, Intel Core2Duo processor, with AMD ICD.

**Comment by quicklisp** [comment]
Here is clinfo:

    Number of platforms:                             1
      Platform Profile:                              FULL_PROFILE
      Platform Version:                              OpenCL 2.0 AMD-APP (1800.11)
      Platform Name:                                 AMD Accelerated Parallel Processing
      Platform Vendor:                               Advanced Micro Devices, Inc.
      Platform Extensions:                           cl_khr_icd cl_amd_event_callback cl_amd_offline_devices


      Platform Name:                                 AMD Accelerated Parallel Processing
    Number of devices:                               1
      Device Type:                                   CL_DEVICE_TYPE_CPU
      Device ID:                                     4098
      Max compute units:                             8
      Max work items dimensions:                     3
	Max work items[0]:                           1024
	Max work items[1]:                           1024
	Max work items[2]:                           1024
      Max work group size:                           1024
      Preferred vector width char:                   16
      Preferred vector width short:                  8
      Preferred vector width int:                    4
      Preferred vector width long:                   2
      Preferred vector width float:                  8
      Preferred vector width double:                 4
      Native vector width char:                      16
      Native vector width short:                     8
      Native vector width int:                       4
      Native vector width long:                      2
      Native vector width float:                     8
      Native vector width double:                    4
      Max clock frequency:                           3398Mhz
      Address bits:                                  64
      Max memory allocation:                         8362064896
      Image support:                                 Yes
      Max number of images read arguments:           128
      Max number of images write arguments:          64
      Max image 2D width:                            8192
      Max image 2D height:                           8192
      Max image 3D width:                            2048
      Max image 3D height:                           2048
      Max image 3D depth:                            2048
      Max samplers within kernel:                    16
      Max size of kernel argument:                   4096
      Alignment (bits) of base address:              1024
      Minimum alignment (bytes) for any datatype:    128
      Single precision floating point capability
	Denorms:                                     Yes
	Quiet NaNs:                                  Yes
	Round to nearest even:                       Yes
	Round to zero:                               Yes
	Round to +ve and infinity:                   Yes
	IEEE754-2008 fused multiply-add:             Yes
      Cache type:                                    Read/Write
      Cache line size:                               64
      Cache size:                                    32768
      Global memory size:                            33448259584
      Constant buffer size:                          65536
      Max number of constant args:                   8
      Local memory type:                             Global
      Local memory size:                             32768
      Error correction support:                      0
      Unified memory for Host and Device:            1
      Profiling timer resolution:                    1
      Device endianness:                             Little
      Available:                                     Yes
      Compiler available:                            Yes
      Execution capabilities:
	Execute OpenCL kernels:                      Yes
	Execute native function:                     Yes
      Queue properties:
	Out-of-Order:                                No
	Profiling :                                  Yes
      Platform ID:                                   0x7ffff6ce4430
      Name:                                          Intel(R) Xeon(R) CPU E3-1231 v3 @ 3.40GHz
      Vendor:                                        GenuineIntel
      Device OpenCL C version:                       OpenCL C 1.2
      Driver version:                                1800.11 (sse2,avx)
      Profile:                                       FULL_PROFILE
      Version:                                       OpenCL 1.2 AMD-APP (1800.11)
      Extensions:                                    cl_khr_fp64 cl_amd_fp64 cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_int64_base_atomics cl_khr_int64_extended_atomics cl_khr_3d_image_writes cl_khr_byte_addressable_store cl_khr_gl_sharing cl_ext_device_fission cl_amd_device_attribute_query cl_amd_vec3 cl_amd_printf cl_amd_media_ops cl_amd_media_ops2 cl_amd_popcnt cl_khr_spir cl_khr_gl_event

Here's what I get now; I don't understand it at all...

    ; /home/xach/.cache/common-lisp/sbcl-1.3.2.136-7c6bbaa-linux-x64/home/xach/quicklisp/local-projects/eazy-opencl/0.bindings-src/2-4-grovel-cl-TMP.fasl written
    ; compilation finished in 0:00:00.033
    ..
    debugger invoked on a SB-KERNEL:CASE-FAILURE in thread #<THREAD "main thread" RUNNING {1003994863}>: --DEVICE-TYPE fell through COMMON-LISP:ECASE expression. Wanted one of (:CHAR :UNSIGNED-CHAR :UCHAR :SHORT :UNSIGNED-SHORT :USHORT :INT :UNSIGNED-INT :UINT :LONG :UNSIGNED-LONG :ULONG ...).

    Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

    restarts (invokable by number or by possibly-abbreviated name):
      0: [RETRY                        ] Retry PROCESS-OP on #<GROVEL-FILE "eazy-opencl.bindings" "0.bindings-src" "2-4-grovel-cl-enum">.
      1: [ACCEPT                       ] Continue, treating PROCESS-OP on #<GROVEL-FILE "eazy-opencl.bindings" "0.bindings-src" "2-4-grovel-cl-enum"> as having been successful.
      2:                                 Retry ASDF operation.
      3: [CLEAR-CONFIGURATION-AND-RETRY] Retry ASDF operation after resetting the configuration.
      4: [ABORT                        ] Give up on "eazy-opencl"
      5:                                 Exit debugger, returning to top level.

    (SB-KERNEL:CASE-FAILURE COMMON-LISP:ECASE --DEVICE-TYPE (:CHAR :UNSIGNED-CHAR :UCHAR :SHORT :UNSIGNED-SHORT :USHORT :INT :UNSIGNED-INT :UINT :LONG :UNSIGNED-LONG :ULONG ...))
    0] cl:*features*

    (:OPENCL-1.2 :OPENCL-1.1 :OPENCL-1.0 CFFI-FEATURES:FLAT-NAMESPACE CFFI-FEATURES:X86-64 CFFI-FEATURES:UNIX :CFFI CFFI-SYS::FLAT-NAMESPACE :QUICKLISP :SB-BSD-SOCKETS-ADDRINFO :ASDF-PACKAGE-SYSTEM :ASDF3.1 ...)
    0] ; 
    ; compilation unit aborted
    ;   caught 2 fatal ERROR conditions
    ;   printed 1 note

    ("eazy-opencl")
    * cl:*features*

    (:OPENCL-1.2 :OPENCL-1.1 :OPENCL-1.0 CFFI-FEATURES:FLAT-NAMESPACE
     CFFI-FEATURES:X86-64 CFFI-FEATURES:UNIX :CFFI CFFI-SYS::FLAT-NAMESPACE
     :QUICKLISP :SB-BSD-SOCKETS-ADDRINFO :ASDF-PACKAGE-SYSTEM :ASDF3.1 :ASDF3
     :ASDF2 :ASDF :OS-UNIX :NON-BASE-CHARS-EXIST-P :ASDF-UNICODE :64-BIT
     :64-BIT-REGISTERS :ALIEN-CALLBACKS :ANSI-CL :ASH-RIGHT-VOPS
     :C-STACK-IS-CONTROL-STACK :COMMON-LISP :COMPARE-AND-SWAP-VOPS
     :COMPLEX-FLOAT-VOPS :CYCLE-COUNTER :ELF :FLOAT-EQL-VOPS
     :FP-AND-PC-STANDARD-SAVE :GENCGC :IEEE-FLOATING-POINT :INLINE-CONSTANTS
     :INTEGER-EQL-VOP :INTERLEAVED-RAW-SLOTS :LARGEFILE :LINKAGE-TABLE :LINUX
     :LITTLE-ENDIAN :MEMORY-BARRIER-VOPS :MULTIPLY-HIGH-VOPS :OS-PROVIDES-BLKSIZE-T
     :OS-PROVIDES-DLADDR :OS-PROVIDES-DLOPEN :OS-PROVIDES-GETPROTOBY-R
     :OS-PROVIDES-POLL :OS-PROVIDES-PUTWC :OS-PROVIDES-SUSECONDS-T
     :PACKAGE-LOCAL-NICKNAMES :PRECISE-ARG-COUNT-ERROR :RAW-INSTANCE-INIT-VOPS
     :SB-AFTER-XC-CORE :SB-CORE-COMPRESSION :SB-DOC :SB-EVAL :SB-FUTEX :SB-LDB
     :SB-PACKAGE-LOCKS :SB-SIMD-PACK :SB-SOURCE-LOCATIONS :SB-TEST :SB-THREAD
     :SB-UNICODE :SB-XREF-FOR-INTERNALS :SBCL :STACK-ALLOCATABLE-CLOSURES
     :STACK-ALLOCATABLE-FIXED-OBJECTS :STACK-ALLOCATABLE-LISTS
     :STACK-ALLOCATABLE-VECTORS :STACK-GROWS-DOWNWARD-NOT-UPWARD :SYMBOL-INFO-VOPS
     :UNIX :UNWIND-TO-FRAME-AND-CALL-VOP :X86-64)

**Comment by guicho271828** [comment]
Thank you. This is another expected error caused by the older version of CFFI (as noted in the readme). Is there a plan to update it? It requires a fix to CFFI made in the last October, so I thought it were already in quicklisp.

**Comment by gos-k** [comment]
@quicklisp 
CFFI was updated at quicklisp 2016-03-18.
I can build eazy-opencl.

**Comment by quicklisp** [comment]
Does not build for me still - lots of warnings: http://report.quicklisp.org/2016-09-25/failure-report/eazy-opencl.html#eazy-opencl

**Comment by quicklisp** [comment]
Any news on this? Are you able to build on SBCL with warnings enabled (e.g. with quickload :verbose t)?

**Comment by guicho271828** [comment]
I will close this issue at the moment.
