### ISSUE TITLE
Please add sbcl-readline

### ISSUE THREAD

**Issue by jpcima** [quicklisp/quicklisp-projects#1093]
Readline completion and history for SBCL in the terminal.

Homepage: http://jini-zh.org/sbcl-readline/sbcl-readline.html
and GIT repo: git://jini-zh.org/sbcl-readline

**Comment by quicklisp** [comment]
Sorry, I do not add projects that work only on one implementation. See http://blog.quicklisp.org/2015/01/getting-library-into-quicklisp.html for some details.
