### ISSUE TITLE
It looks like the quicklisp project for bordeaux-threads is out of date.  

### ISSUE THREAD

**Issue by pet-ro** [quicklisp/quicklisp-projects#1094]
The quote below is from https://github.com/sionescu/bordeaux-threads/issues/16 

" ... It looks like the quicklisp project for bordeaux-threads is out of date. 
  The file in question should not be included on LispWorks 7.0. 
  Cloning the latest git repository locally into your local-projects 
  should supercede the remote version available from quicklisp, and 
  any dependent systems should load successfully." 

On 2016-03-09 newest version is Release 0.8.5, 
while quicklisp uses Release 0.8.4,

**Comment by quicklisp** [comment]
Thanks, I have discussed it with @sionescu and found a solution, the next Quicklisp release will use the latest release.

**Comment by unwind-protect** [comment]
This is a problem and should be fixed as soon as possible. Cannot deploy code on several machines for this and, although easy to work around, it is unacceptable.
If there's anything I could do to speed up the process, I'm ready to help.
