### ISSUE TITLE
Please add liblmdb

### ISSUE THREAD

**Issue by eudoxia0** [quicklisp/quicklisp-projects#1096]
This is a low-level binding to the [LMDB](http://symas.com/mdb/) key-value database.

https://github.com/antimer/liblmdb

**Comment by quicklisp** [comment]
Doesn't build for me due to redefining non-EQL constant: http://report.quicklisp.org/2016-03-18/failure-report/liblmdb.html

**Comment by eudoxia0** [comment]
I think it's fixed now.
