### ISSUE TITLE
Please add lmdb

### ISSUE THREAD

**Issue by eudoxia0** [quicklisp/quicklisp-projects#1097]
This is a higher-level binding to LMDB

https://github.com/antimer/lmdb

**Comment by quicklisp** [comment]
Hung up on problems building liblmdb for now.

**Comment by quicklisp** [comment]
Got it going. It was a minor pain to get liblmdb.so, but not so bad that I gave up on it.

**Comment by eudoxia0** [comment]
Thanks for taking the time to build it.
