### ISSUE TITLE
Please Add random-state

### ISSUE THREAD

**Issue by Shinmera** [quicklisp/quicklisp-projects#1098]
This is a collection of pseudo random number generators (PRNGs). While Common Lisp does provide a RANDOM function, it does not allow the user to pass an explicit SEED, nor to portably exchange the random state between implementations. This can be a headache in cases like games, where a controlled seeding process can be very useful.

Author: Nicolas Hafner
Source: https://github.com/Shinmera/random-state.git
Documentation: https://shinmera.github.io/random-state/

**Comment by quicklisp** [comment]
It doesn't build for me due to a warning. http://report.quicklisp.org/2016-03-18/failure-report/random-state.html has the context.
