### ISSUE TITLE
Please add DARTS.LIB.EMAIL-ADDRESS

### ISSUE THREAD

**Issue by deterministic-arts** [quicklisp/quicklisp-projects#1101]
Hi Zach,

please add the [DARTS.LIB.EMAIL-ADDRESS](https://github.com/deterministic-arts/DartsCLEmailAddress) system to quicklisp. The licence is MIT. The documentation will be updated soon.

Thanks

**Comment by deterministic-arts** [comment]
If it is possible, consider using the `quicklisp-release` branch instead of `master`. I will try to keep it stable (i.e., not to pollute it with the occasional not-yet-quite-ready-for-prime-time commit). Drop me a note, if your build process requires the use of the `master` branch. I will then switch to a dedicated `development` branch for development.

**Comment by quicklisp** [comment]
I can use any branch, the latest tag, or the latest release. I'll use the quicklisp-release branch as requested.
