### ISSUE TITLE
usocket broken with quicklisp release 2016-03-18

### ISSUE THREAD

**Issue by fragrans** [quicklisp/quicklisp-projects#1105]
**USOCKET upgraded to 0.6.4 in this release, caused the broken.**
And I also reported the broken to usocket:
https://github.com/usocket/usocket/issues/16

CL-USER> (ql:quickload :usocket)
To load "usocket":
  Load 1 ASDF system:
    usocket
; Loading "usocket"
[package usocket].......
; 
; caught ERROR:
;   READ error during COMPILE-FILE:
;   
;     Symbol "INET6-SOCKET" not found in the SB-BSD-SOCKETS package.
;   
;       Line: 287, Column: 71, File-Position: 10470
;   
;       Stream: #<SB-SYS:FD-STREAM
;                 for "file /home/ll/quicklisp/dists/quicklisp/software/usocket-0.6.4/backend/sbcl.lisp"
;                 {10049D1853}>
; 
; compilation unit aborted
;   caught 3 fatal ERROR conditions
;   caught 1 ERROR condition
; Evaluation aborted on #<UIOP/LISP-BUILD:COMPILE-FILE-ERROR {1004DA5D03}>.

**Comment by binghe** [comment]
I've released usocket 0.6.4.1 to handle this issue.

https://common-lisp.net/project/usocket/releases/usocket-0.6.4.1.tar.gz

**Comment by fragrans** [comment]
I would like to test, but I don't know how to upgrade usocket from 0.6.4 to 0.6.4.1 using quicklisp.
OR how to use asdf install/load a local tar.gz file.
;-P

**Comment by binghe** [comment]
Hi, you can download usocket 0.6.4.1 from usocket's web site and then
extract into your "quicklisp/local-projects" folder. That's a feature of
quicklisp for local developers (and package maintainers).

Chun

On 20 March 2016 at 06:03, lll <notifications@github.com> wrote:

> I would like to test, but I don't know how to upgrade usocket from 0.6.4
> to 0.6.4.1 using quicklisp.
> OR how to use asdf install/load a local tar.gz file.
> ;-P
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/quicklisp/quicklisp-projects/issues/1105#issuecomment-198851462>
>



-- 
Chun Tian (binghe)

**Comment by fragrans** [comment]
I tested with sbcl/1.2.14 and sbcl/1.1.14. 
It just worked fine.

fragrans

**Comment by binghe** [comment]
Good to know, thanks!

On 21 March 2016 at 08:41, lll <notifications@github.com> wrote:

> I tested with sbcl/1.2.14 and sbcl/1.1.14.
> It just worked fine.
>
> fragrans
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/quicklisp/quicklisp-projects/issues/1105#issuecomment-199159623>
>



-- 
Chun Tian (binghe)

**Comment by quicklisp** [comment]
If you are stuck with an old sbcl, it will be best to stick with last month's Quicklisp update. The next update, in April, will have 0.6.4.1 (or newer).

If you've already upgraded, you can go back, following the directions on http://blog.quicklisp.org/2011/08/going-back-in-dist-time.html

**Comment by quicklisp** [comment]
This is fixed in the April release.
