### ISSUE TITLE
Please add cl-statsd

### ISSUE THREAD

**Issue by deadtrickster** [quicklisp/quicklisp-projects#1110]
https://github.com/deadtrickster/cl-statsd

[StatsD](https://github.com/etsy/statsd) client in common lisp

**Comment by quicklisp** [comment]
Doesn't build for me - comma not inside backquote. http://report.quicklisp.org/2016-04-01/failure-report/cl-statsd.html has more context.

**Comment by deadtrickster** [comment]
fixed, thanks for the report!
