### ISSUE TITLE
Please add caveman2-widgets

### ISSUE THREAD

**Issue by ritschmaster** [quicklisp/quicklisp-projects#1115]
caveman2-widgets is an extension to caveman2. It introduces Weblocks like widgets but in not such a restricting way like in Weblocks. 

I have tested SBCL and CCL so far but I guess on every plattform where caveman2 works, caveman2-widgets works too, since it (almost) only uses caveman2.

The source is available at: https://github.com/ritschmaster/caveman2-widgets

**Comment by quicklisp** [comment]
Doesn't build for me due to an unrecognized declaration. Context is here: http://report.quicklisp.org/2016-04-01/failure-report/caveman2-widgets.html

**Comment by ritschmaster** [comment]
I am very sorry but my SBCL didn't throw any errors regarding that. It was a minor mistake, but I fixed it. Hopefully there won't be any error again.
