### ISSUE TITLE
Please Add TM - A Formalized Iteration Library

### ISSUE THREAD

**Issue by Antigonus** [quicklisp/quicklisp-projects#1117]
TM - A Formalized Iteration Library

TM stands for "tape machine".

https://github.com/Antigonus/tm/releases/tag/v0.1-alpha

The manual is at docs/html/index.html

Load "load.lisp"  to load the library.

Evaluate (test-all)  to run regression.  Everything is passing on our side.

thank you!

**Comment by guicho271828** [comment]
tape machine != turing machine?

**Comment by Antigonus** [comment]
Hello,

> tape machine != turing machine?

Correct, they are different objects.

The manifest tape machine is a class with two slots and a generic function
interface via CLOS.  The Turing Machine is a mathematical abstraction
defined by a set of five elements.   So these two objects are different.

However,  for many programs that employ the tape machine, it will be
possible to derive a Turing machine with equivalent functionality -- and
that is where the fun begins.

The key is that the tape machine function interface functions accepts as
arguments continuation functions, and that is what gives us our morphism to
the open ended "tape"  of the Turing Machine.

This question is discussed in docs/html/index.html introduction, but I
think the description in this email turned out better ;-)

-Thomas

**Comment by Antigonus** [comment]
This library is being proposed for serious computation, the formalism is an
additional benefit.

**Comment by quicklisp** [comment]
There are some files in the current release tag that have non-ascii filenames. Is it possible to use ascii filenames instead?

**Comment by Antigonus** [comment]
At first I was confused by this as no source code file has a non-ascii file name.   One can see this quickly looking at the tm.asd file.

...  but now I see two files are being autogenerated by the documents tool and are under the /docs/html directory:  (not part of the library, part of the docs).

light§/home/tm> /tm> ls -lR | grep -P "[\x80-\xFF]"
-rw-rw----+ 1 plato tm  2008 Oct 31 13:39 Function-¬∃.html
-rw-rw----+ 1 plato tm  1933 Oct 31 13:39 Function-¬∀.html

§light§/home/tm> find . -name Function-¬∃.html -o -name Function-¬∀.html
./docs/html/dictionary/Function-¬∃.html
./docs/html/dictionary/Function-¬∀.html

I apologize about this, I did not notice this was happening.  I will have a new release out within about ~one week, and will change these.

**Comment by Antigonus** [comment]
Hello, I've issued a new release,  v0.7 on github.com/Antigonus/tm  

I have also written a short book about the library,  a pdf version can be found for free at:
https://www.researchgate.net/publication/315808386_Tom%27s_Turing_Complete_Architecture_Volume_1_Foundation_and_TM_Library_Interface 
 Hard copy and Kindle can be found at Amazon.  (The book should more than answer guicho271828  question ;-)

I did not use the autodoc generator.  There are no unicode file names.

It may be loaded using (load "load").   Regression tests are then run with (test-all).   Small chance that test-ts1-4  or ts1-5 will fail, because they are multithreading and using sleep timers to check collisions.  If one's system is bogged down it is conceivable they will time out.   I've also witnessed thrown errors hang a Bordeaux thread.   Hopefully no one will experience these things.  I think the timers are set sufficiently long.

Thanks Zach!

**Comment by Antigonus** [comment]
Hello,  Its been a month since the last release, so here is a small update.  Fixes some problems in the export list, and changes the quantifiers to have the same form for continuations as for other functions.   The book has had 50 reads at Research Gate, would be nice if the code was available in quicklisp.

**Comment by Antigonus** [comment]
Please note release v0.8 on github

**Comment by quicklisp** [comment]
It's in Quicklisp and updates will be picked up automatically.

**Comment by Antigonus** [comment]
To build the library now requires   sbcl --dynamic-space-size 2048 on my machine.  Where do I put this switch so that quicklisp picks it up?

I say "on my machine" as apparently the default setting is platform dependent.  I am working on a major new release for tm, but to compile the tests SBCL must be invoked with --dynamic-space-size 2048 or it crashes with "Heap exhausted during garbage collection".   It is a little surprising as the test where this happens is miniscule.  It seems to have something to do with the compiler optimizing out unused code after/along with macro expansion.

**Comment by quicklisp** [comment]
It isn't required on my machine, so there's no need to do anything at this time.
