### ISSUE TITLE
Please add RECURSIVE-RESTART

### ISSUE THREAD

**Issue by heegaiximephoomeeghahyaiseekh** [quicklisp/quicklisp-projects#1129]
Available [here](https://github.com/heegaiximephoomeeghahyaiseekh/recursive-restart). It implements a single macro, `RECURSIVE-RESTART-CASE`, which can be used like the normal `RESTART-CASE`, except the restarts can recursively invoke themselves and each other.

**Comment by quicklisp** [comment]
Please add license info to the system file, and add a README.

**Comment by heegaiximephoomeeghahyaiseekh** [comment]
License and README added.
