### ISSUE TITLE
iolib has no deps on libfixposix 

### ISSUE THREAD

**Issue by MatthewRock** [quicklisp/quicklisp-projects#1131]
You can get this library: https://github.com/sionescu/iolib
through quicklisp. However, compilation fails with G++ command returning status 1.  I inspected the case further and found out that iolib depends on libfixposix: https://github.com/sionescu/libfixposix
However, libfixposix isn't marked as dep for iolib.

I hope that I report this on the proper github repository.

**Comment by quicklisp** [comment]
Quicklisp manages only the CL dependencies of a project. libfixposix is a C library and cannot be installed or managed via Quicklisp.
