### ISSUE TITLE
Please add fare-scripts

### ISSUE THREAD

**Issue by fare** [quicklisp/quicklisp-projects#1133]
The next version of exscribe will depend on fare-scripts:

    https://github.com/fare/fare-scripts

**Comment by bhyde** [comment]
On 3 May 2016, at 20:52, François-René Rideau wrote:

> exscribe

Always good to know a bit-o-history :)
  https://en.wikipedia.org/wiki/Scribe_(markup_language)
  https://en.wikipedia.org/wiki/Brian_Reid_(computer_scientist)#Google

Brian, who I like to describe as the creator of usenet’s alt.*, the
CMU cheese cooperative, and something to do with Orkut.  He was a
friend back at CMU, and lived we shared a house at one point.

 - ben
