### ISSUE TITLE
Please add cl-oclapi

### ISSUE THREAD

**Issue by gos-k** [quicklisp/quicklisp-projects#1135]
This is alibrary of OpenCL API bindings.
https://github.com/gos-k/cl-oclapi

**Comment by quicklisp** [comment]
I can't build because of a missing libOpenCL.so. Do you know where I can get it?

**Comment by akacase** [comment]
Debian has these packages available: 
**/usr/lib/x86_64-linux-gnu/libOpenCL.so**	[amd-opencl-dev](https://packages.debian.org/jessie/amd-opencl-dev) [**amd64**], [nvidia-opencl-dev](https://packages.debian.org/jessie/nvidia-opencl-dev) [**amd64**], [ocl-icd-opencl-dev](https://packages.debian.org/jessie/ocl-icd-opencl-dev) [**amd64**]

**Comment by gos-k** [comment]
@quicklisp 
I use `ocl-icd-opencl-dev`
You can get libOpenCL.so
`sudo apt-get install ocl-icd-opencl-dev`
