### ISSUE TITLE
Please add cl-scan.

### ISSUE THREAD

**Issue by akacase** [quicklisp/quicklisp-projects#1136]
[cl-scan](https://github.com/akacase/cl-scan), is a simple port scanner. Thanks.

**Comment by quicklisp** [comment]
What happened to this project?

**Comment by akacase** [comment]
Hey Zach,

I stupidly dumped the repo the other day, because I had a repo with more
commits/activity on my local box. Instead of remote merging I was just
going to swap them and it turns out it wasn't there. I'm working on
trying to restore the repo by end of day. Apologies.


On Wed, Sep 28, 2016, at 09:37, Zach Beane wrote:
> What happened to this project?
> — You are receiving this because you authored the thread. Reply to
> this email directly, view it on GitHub[1], or mute the thread[2].
>


Links:

  1. https://github.com/quicklisp/quicklisp-projects/issues/1136#issuecomment-250168510

**Comment by akacase** [comment]
project is restored, apologies.

**Comment by akacase** [comment]
project is deleted, please dismiss.
