### ISSUE TITLE
Please add cl-scsu

### ISSUE THREAD

**Issue by y2q-actionman** [quicklisp/quicklisp-projects#1143]
cl-scsu is an implementation of Standard Compression Scheme for Unicode (http://unicode.org/reports/tr6/) by Common Lisp.

https://github.com/y2q-actionman/cl-scsu

Thank you.

**Comment by quicklisp** [comment]
Does not build for me in SBCL. The test system name differs from the test system file name, for one.

**Comment by y2q-actionman** [comment]
I found some type declarations are too ambiguous and cause many warning. I fixed them.
I am sorry for taking up your time.
