### ISSUE TITLE
Pull trivial-backtrace from github

### ISSUE THREAD

**Issue by PuercoPop** [quicklisp/quicklisp-projects#1145]
Hi @xach 

The author of trivial-backtrace publishes two repositories for trivial-backtrace. One in [github](https://github.com/gwkkwg/trivial-backtrace/commits/master) and one in [common-lisp.net](https://gitlab.common-lisp.net/trivial-backtrace/trivial-backtrace/commits/master). As you can see the one in github has more recent changes.

cc: @gwkkwg in case he prefers c-l.net the authoritative source

**Comment by gwkkwg** [comment]
> Hi @xach <https://github.com/xach>
> The author of trivial-backtrace publishes two repositories for trivial-backtrace. One in github <https://github.com/gwkkwg/trivial-backtrace/commits/master> and one in common-lisp.net <https://gitlab.common-lisp.net/trivial-backtrace/trivial-backtrace/commits/master>. As you can see the one in github has more recent changes.
> 
> cc: @gwkkwg <https://github.com/gwkkwg> in case he prefers c-l.net the authoritative source
> 
>    
> 

Thanks Javier, 

github is correct.
