### ISSUE TITLE
Please use kingcons for coleslaw source

### ISSUE THREAD

**Issue by mordocai** [quicklisp/quicklisp-projects#1150]
Please switch to https://github.com/kingcons/coleslaw for quicklisp's source for coleslaw.

Quicklisp is currently behind by about 2 months/ five commits it looks like.

**Comment by PuercoPop** [comment]
@mordocai ql is being pulled from that repo it seems, redline6561 is the previous username of kingcons

**Comment by mordocai** [comment]
@PuercoPop I thought quicklisp's process should automatically keep it up to date, which is why I figured the source was incorrect.
