### ISSUE TITLE
Please add neo4cl

### ISSUE THREAD

**Issue by equill** [quicklisp/quicklisp-projects#1155]
https://github.com/equill/neo4cl

It's a simple and reasonably easy-to-use interface for Neo4J, designed for use as a library.
All dependencies are already loadable by quicklisp, and I've tested it on sbcl, ccl and ccl64.

**Comment by quicklisp** [comment]
Can you please add some info to the readme about Neo4J? What does it do? Why would someone want to use it from CL? Links would be good too.

**Comment by equill** [comment]
Excellent points! Thanks; it's easy to get your head too deeply into a project and forget that not everybody else already has the context.
I've updated the readme; hopefully that provides a better intro, but I'll be happy to refine it further if it's still not clear enough.

**Comment by quicklisp** [comment]
The main system builds, but the test system does not load - it has an implicit dependency on neo4cl that should be made explicit.

**Comment by equill** [comment]
That was odd; it _did_ have an explicit dependency.
I've removed the offending :use statement, though, and now the test suite builds cleanly and runs successfully.

**Comment by quicklisp** [comment]
My mistake.

When you define packages in system files, they will be defined even when a simple (asdf:find-system "my-package") is evaluated, when really it should be done only when the project is loaded. It is better to put package definitions in regular .lisp files that are loaded as part of the project.

**Comment by equill** [comment]
The mistake was mine: it definitely didn't compile if you simply tried to load neo4cl-test, which I should have tested myself before wasting your time.
Thanks for the pointer; I'd been wondering which was the smarter way of handling package definitions, and you've answered that question neatly.
