### ISSUE TITLE
Maybe update fiveam?

### ISSUE THREAD

**Issue by scymtym** [quicklisp/quicklisp-projects#1161]
Version 1.3, which has been released recently, adds a few useful features. I suggest updating, unless @sionescu advises differently.

**Comment by guicho271828** [comment]
it's on master, so I guess it will be automatically updated

**Comment by PuercoPop** [comment]
@guicho271828 no, it fetches the [latest release](https://github.com/quicklisp/quicklisp-projects/blob/master/projects/fiveam/source.txt) uploaded to c-l.net

**Comment by quicklisp** [comment]
I'll look into it, thanks.

**Comment by quicklisp** [comment]
I have updated it to use the latest github release, which is 1.3.

**Comment by scymtym** [comment]
Thanks.
