### ISSUE TITLE
Please add ILLOGICAL-PATHNAMES

### ISSUE THREAD

**Issue by tarballs-are-good** [quicklisp/quicklisp-projects#1168]
It is useful to > 1 person it seems, and solves a problem.

It adds a nice syntax for specifying implementation-independent pathnames relative to some configurable base directories. Despite superficial similarities to logical pathnames, it doesn't solve the problem that logical pathnames solves.

Source: git@bitbucket.org:tarballs_are_good/illogical-pathnames.git
URL: https://bitbucket.org/tarballs_are_good/illogical-pathnames/
License: BSD 3-clause

**Comment by quicklisp** [comment]
Doesn't build for me - http://report.quicklisp.org/2016-07-19/failure-report/illogical-pathnames.html - bootstrap timing issue or something?

**Comment by tarballs-are-good** [comment]
Yep, this was poor QC on my part. It is a bootstrap issue. Will fix in the next day or so.

**Comment by tarballs-are-good** [comment]
Fixed.
