### ISSUE TITLE
Please add cl-xdg

### ISSUE THREAD

**Issue by eadmund** [quicklisp/quicklisp-projects#1169]
CL-XDG is a library to handle various freedesktop.org standards.  Right now it has support for the desktop entry & base directory specifications.

Author: Robert A. Uhl
Source: https://github.com/eadmund/cl-xdg.git
Documentation: https://github.com/eadmund/cl-xdg

**Comment by quicklisp** [comment]
Doesn't build for me - implicit dependency on sb-posix. http://report.quicklisp.org/2016-07-19/failure-report/cl-xdg.html  has build log.

**Comment by eadmund** [comment]
Ah, I always have SB-POSIX loaded. I've corrected the ASDF definition, and tested under SBCL with `--no-userinit -- no-sysinit` & CLISP.

**Comment by eadmund** [comment]
I've added a test suite, and once again tested on SBCL & CLISP.

**Comment by eadmund** [comment]
I've also tested on AllegroCL & LispWorks.

**Comment by eadmund** [comment]
I've also tested against Clozure & ECL — all tests pass. I think that CLISP, SBCL, AllegroCL, LispWorks, Clozure & ECL are all the Linux Common Lisp implementations.

No idea how well it'll work on Windows or macOS.
