### ISSUE TITLE
Please add caveman2-widgets-bootstrap

### ISSUE THREAD

**Issue by ritschmaster** [quicklisp/quicklisp-projects#1170]
caveman2-widgets-bootstrap is an extension to my other library caveman2-widgets. It supplies Bootstrap widgets for the developer to speed up the work.

I have tested it for SBCL and CCL but I guess it should work on every plattform since it only needs caveman2 and caveman2-widgets.

The source is available at: https://github.com/ritschmaster/caveman2-widgets-bootstrap

**Comment by quicklisp** [comment]
Doesn't build for me - http://report.quicklisp.org/2016-07-19/failure-report/caveman2-widgets-bootstrap.html - missing :description in system file, and problems with the test system too.

**Comment by ritschmaster** [comment]
As the dependency [caveman2-widgets](https://github.com/ritschmaster/caveman2-widgets) already offers the used interface (which causes an error) I guess that the newest commits are not in Quicklisp yet. The problem is that  is under heavy development right now. This error will eventually disappear.
