### ISSUE TITLE
Please add cl-soil

### ISSUE THREAD

**Issue by cbaggers** [quicklisp/quicklisp-projects#1177]
Library can be found here: https://github.com/cbaggers/cl-soil/tree/release-quicklisp

Please use branch: `release-quicklisp`

Provided wrappers around the 'libSOIL` library which is a very lightweight image loading library that load to foreign data or gl textures

**Comment by quicklisp** [comment]
Can you please add :description, :license, and :author to the system file?

**Comment by cbaggers** [comment]
So sorry, I have fixed that now

**Comment by quicklisp** [comment]
http://report.quicklisp.org/2016-08-22/failure-report/cl-soil.html#cl-soil - can't build because of duplicate definition.

**Comment by cbaggers** [comment]
Jeez, I don't know how I managed to mess this up so badly, I wasnt seeing issues on my end. The wonderful PuercoPop has fixed this and running `(asdf:load-system :cl-soil :force t :verbose t)` on my machine is not showing any issues (for what that is worth)
