### ISSUE TITLE
Please add dirt

### ISSUE THREAD

**Issue by cbaggers** [quicklisp/quicklisp-projects#1178]
Dirt is a library that uses `cl-soil` to load images into CEPL c-arrays and textures.

It can be found here: https://github.com/cbaggers/dirt/tree/release-quicklisp

Please use the `release-quicklisp` branch

Thanks

**Comment by quicklisp** [comment]
Until cl-soil builds, this can't build. See my remarks on the #1177.

**Comment by cbaggers** [comment]
Should be resolved now, sorry again for these delays
