### ISSUE TITLE
Please add clTcl

### ISSUE THREAD

**Issue by nilqed** [quicklisp/quicklisp-projects#1189]
**Embed Tcl/Tk scripts in Common Lisp.**
_Summary_: Tcl/Tk provides a powerful GUI library. It is a combination of the scripting language Tcl and the cross-platform widget toolkit Tk.
Package clTcl provides an interface to Tcl/Tk via Tcl scripts embedded into Common Lisp. Program your GUI with Tcl as embedded language. Scripts can be run by choosing one of the various Tcl/Tk interpreters. Deployment is possible for many systems.

Url: https://github.com/nilqed/cltcl
:author Paul Griffioen
:license MIT, see file LICENSE
:source https://github.com/lisper99/cltcl

**Comment by nilqed** [comment]
Does it not work?

**Comment by quicklisp** [comment]
I screwed up and missed this project, sorry. It will be in the next update.

**Comment by nilqed** [comment]
No problem. Thank you.

**Comment by quicklisp** [comment]
Can you please add :author, :license, and :description metadata to the system file?

**Comment by nilqed** [comment]
Well, it should already be there.
The link is: https://github.com/nilqed/cltcl

Perhaps you tried the 'source' link? That is the link to the original which I
forked and prepared (with the permission of the author of course).

Thank you
Kurt
Am 10.10.2016 um 14:22 schrieb Zach Beane:
> Can you please add :author, :license, and :description metadata to the system file?
>

**Comment by quicklisp** [comment]
You're right, I took the wrong link. It builds properly now.
