### ISSUE TITLE
Please add cl-ascii-art

### ISSUE THREAD

**Issue by whalliburton** [quicklisp/quicklisp-projects#1191]
cl-ascii-art is a collection of utilities for generating ASCII art.

https://github.com/Blue-Sky-Skunkworks/cl-ascii-art

**Comment by quicklisp** [comment]
I saw #1149 and remarked on it there - this project does not build in SBCL. http://report.quicklisp.org/2016-09-05/failure-report/cl-ascii-art.html has a log.

**Comment by whalliburton** [comment]
Got it. Thanks. Will fix.

**Comment by whalliburton** [comment]
I believe it is loadable now.
