### ISSUE TITLE
please add cl-kanren

### ISSUE THREAD

**Issue by cage2** [quicklisp/quicklisp-projects#1198]
Quicklisp use as source a  -**AFAIK** outdated- repository on common-lisp.net.

I have made a patched version of this library available on:

https://github.com/cage2/cl-kanren

This is, a fork from:

https://github.com/Inaimathi/cl-kanren-trs

I asked to merge my patches to the owner of the repository above but with no luck for the last one.

Please could you consider add this version in quicklisp, i changed the name of the project so no conflict with the older project will arise (but i understand this can be still confusing for someone).

Thank you.
C.

**Comment by quicklisp** [comment]
Can you remove or rename the test system? It clashes with cl-kanren-trs.

**Comment by cage2** [comment]
On Thu, Sep 22, 2016 at 05:34:20AM -0700, Zach Beane wrote:
> Can you remove or rename the test system? It clashes with cl-kanren-trs.

Ops...Sorry. I think the last commit should fix this issue.

Thank you!
C.
