### ISSUE TITLE
Please add utility-arguments.

### ISSUE THREAD

**Issue by 95440b97d** [quicklisp/quicklisp-projects#1199]
The projects repository is located here:
  https://gitlab.com/fau/utility-arguments

HAED of master points to the most recent release.

Utility-Arguments is a Common Lisp (CL) software that handles command line arguments.  It is similar in nature to Command-Line-Arguments but does a little bit more.

**Comment by quicklisp** [comment]
There are many other command-line argument processing projects - can you be more specific about how this one distinguishes itself?

**Comment by 95440b97d** [comment]
Thanks for adding.
I updated the README to point out the distinguishing features.

**Comment by 95440b97d** [comment]
Please be advised that the Git repo was re-created. You may have to clone again depending on how you manage updates.

Sorry for the inconvenience.
