### ISSUE TITLE
Please add LISP-BINARY

### ISSUE THREAD

**Issue by heegaiximephoomeeghahyaiseekh** [quicklisp/quicklisp-projects#1208]
Lisp-Binary is a library for reading and writing complex binary data formats.

https://github.com/heegaiximephoomeeghahyaiseekh/lisp-binary

It provides the `DEFBINARY` macro, which provides a compact syntax similar to
that of `DEFSTRUCT` to specify the format. The data is read into, and written from Lisp `struct` objects.

It has built-in support for any size integer in both byte orders, floating point numbers in IEEE half, single, double, quadruple, and octuple precisions, and automatic handling of Pascal-style counted arrays, C-style terminated strings, and sub-byte bit fields. It can be extended by providing it with runtime reader/writer functions to read specific fields. 

It also provides primitive functions to read and write binary representations of integers and floating-point numbers, and a special Gray stream class from which it is possible to read or write one bit at a time. When using these streams, the integer primitives can read and write integer sizes that involve fractions of a byte.

**Comment by quicklisp** [comment]
Doesn't build on SBCL due to duplicate definition of RECURSIVE-FIND.

**Comment by heegaiximephoomeeghahyaiseekh** [comment]
Sorry about that. Fixed.

**Comment by heegaiximephoomeeghahyaiseekh** [comment]
So... where is it? When I do (ql:quickload :lisp-binary), I get the error `System "lisp-binary" not found.` This is on a fresh Quicklisp install.

**Comment by quicklisp** [comment]
My mistake for closing the issue - it does not build. The output is so voluminous that I don't know the direct cause, it's cut off in my logs. You should be able to see it with (asdf:load-system "lisp-binary"), though. I'll try that later and see if I can find the problem.

**Comment by heegaiximephoomeeghahyaiseekh** [comment]
I fixed all the issues. I couldn't see them with `ql:quickload`.

**Comment by heegaiximephoomeeghahyaiseekh** [comment]
You should be able to build it now.

**Comment by quicklisp** [comment]
Yes, it works fine, sorry for the confusion. It will be in the January update.

**Comment by heegaiximephoomeeghahyaiseekh** [comment]
:smiley:
