### ISSUE TITLE
Please add ulubis and associated libraries

### ISSUE THREAD

**Issue by malcolmstill** [quicklisp/quicklisp-projects#1211]
Ulubis is a Wayland compositor written in Common Lisp. 

Author: Malcolm Still
License: BSD 3-Clause
Code: https://github.com/malcolmstill/ulubis.git
Branch: master
---

cl-wayland provides bindings to libwayland and provides a binding generator for generating arbitrary Wayland protocols.

Author: Malcolm Still
License: BSD 3-Clause
Code: https://github.com/malcolmstill/cl-wayland.git
Branch: master
---

cl-xkb provides bindings to libxkbcommon on Linux.

Author: Malcolm Still
License: BSD 3-Clause
Code: https://github.com/malcolmstill/cl-xkb.git
Branch: master
---

`ulubis-drm-gbm` is a backend that allows ulubis to run without X. It depends on `cepl.drm-gbm`, `cl-drm`, `cl-gbm`, `cl-egl` and `cl-libinput`.

Author: Malcolm Still
License: BSD 3-Clause
Code: https://github.com/malcolmstill/ulubis-drm-gbm.git
Branch: master
---

`cepl.drm-gbm` is a new cepl backend used by `ulubis-drm-gbm`

Author: Malcolm Still
License: BSD 3-Clause
Code: https://github.com/malcolmstill/cepl.drm-gbm.git
Branch: master
---

`cl-drm` is an interface to the Linux DRM system.`

Author: Malcolm Still
License: BSD 3-Clause
Code: https://github.com/malcolmstill/cl-drm.git
Branch: master
---

`cl-gbm` is an interface to the Linux GBM system.`

Author: Malcolm Still
License: BSD 3-Clause
Code: https://github.com/malcolmstill/cl-gbm.git
Branch: master
---

`cl-egl` is a Common Lisp wrapper for libEGL.`

Author: Malcolm Still
License: BSD 3-Clause
Code: https://github.com/malcolmstill/cl-egl.git
Branch: master
---

cl-libinput provides bindings to libinput on Linux.

Author: Malcolm Still
License: BSD 3-Clause
Code: https://github.com/malcolmstill/cl-libinput.git
Branch: master
---

`ulubis-sdl` is a backend that allows ulubis to run under X via SDL2

Author: Malcolm Still
License: BSD 3-Clause
Code: https://github.com/malcolmstill/ulubis-sdl.git
Branch: master

**Comment by quicklisp** [comment]
I can't load cl-xkb because although I have libxkbcommon.so installed on my Debian 8 system, it is not found when building. It's located in `/usr/lib/x86_64-linux-gnu/libxkbcommon.so`.

Same problem for cl-gbm. It's installed but not found during build.

I can't build cl-libinput because there is an implicit dependency on sb-posix - if this project is meant to run on more than SBCL, you should use something other than sb-posix.

ulubis-sdl doesn't build because of an implicit package reference to ULUBIS-BACKEND.

Also, please add README files that are more than just stubs.

**Comment by quicklisp** [comment]
Oh, I see from the ulubis readme that it works only on SBCL. See the second point of http://blog.quicklisp.org/2015/01/getting-library-into-quicklisp.html - it needs to be more portable to get into Quicklisp.

**Comment by malcolmstill** [comment]
Thanks for the feedback. Tomorrow I will update the READMEs so that they are useful and figure out how to fix the implicit package reference.

I'll also add those Debian locations...I'm not sure if anyone knows a systematic way of getting these cffi library locations correct or is it simply a case of continually adding locations when someone can't get it to work?

Yeah I was struggling to find some of the unix functionality required in other Lisps. I'd looked briefly at the [osicat page](https://common-lisp.net/project/osicat/) and without looking at its github page thought it wasn't going to have what I need. After your comment I looked a bit more thoroughly and found that it has a lot more functionality than the homepage makes out and has most of the unix functionality that I require. However it doesn't include the `poll()` system call. I've opened a [pull request to add `poll()`](https://github.com/osicat/osicat/pull/17)  to [osicat](https://github.com/osicat/osicat) which I can then switch all the `sb-posix` calls to `osicat-posix` calls if they merge my request.

That should allow ulubis to run on any (Linux) implementation that supports [cepl](https://github.com/cbaggers/cepl).

**Comment by quicklisp** [comment]
I don't know a lot about FFI, but perhaps you are being too specific? The linker should be able to find it with just the library name, I think. You shouldn't have to add paths specific to every style used by every Linux distro.

iolib might help with multiplexing.

**Comment by malcolmstill** [comment]
I have removed all of the SBCL specific and have tested that ulubis works on CCL. Can you try rebuilding?
