### ISSUE TITLE
About portable-threads

### ISSUE THREAD

**Issue by binghe** [quicklisp/quicklisp-projects#1213]
Hi Xach,

Portable-threads is a portable threads API package, which is part of GBBopen project. But currently (ql:quickload :portable-threads) doesn't load it any more, what's left is the portable-threads-test system:

```
> (ql:system-apropos "portable-threads")
#<QL-DIST:SYSTEM portable-threads-test / gbbopen-20160929-svn / quicklisp 2016-09-29>
```

This is not good. For the reason, it's because "gbbopen portable-threads" is in the blacklist.txt.

According to CLiki (http://www.cliki.net/site/view-revision?article=Portable-Threads&date=3507058605), Portable-threads was packaged into a standalone package, as part of the "cl-containers" project. I guess some time ago Quicklisp actually use this version as the official portable-threads package in Quicklisp. But currently "cl-containers" project doesn't use on "portable-threads" any more, and  there's no "portable-threads.asd" in "cl-containers" project, thus (ql:quickload :portable-threads) fails to load.

There're two solutions:

1. Cancel the blacklist for GBBopen.
2. Use another version of standalone portable-threads from my Github: https://github.com/binghe/portable-threads

I prefer "portable-threads" than "bordeaux-threads" because "portable-threads" provided more APIs (e.g. atomic-incf), and I'm writing a new package which will heavily depend on "portable-threads".

Currently GBBopen is not actively maintained any more, I ever provided LispWorks 7.0 patch to GBBopen's maintainer (Dan Corkill) immediately after LW 7.0 release but he didn't merge my patch until today.   Besides  I contributed all recent code changes of "portable-threads" in last five years:

;;;  03-29-11 Added partial ABCL support (provided by Chun Tian (binghe);
;;;           thanks!)
;;;  06-24-11 Updates for Digitool MCL & ABCL (from Chun Tian (binghe))
;;;  10-24-16 Added support for LispWorks 7.0 (from Chun Tian (binghe))

So I have willings to take over the responsibility and keep maintaining "portable-threads". And I hope you can use my version as the official version of "portable-threads" on Quicklisp.

Regards,

Chun Tian (binghe)

**Comment by quicklisp** [comment]
I am up for adding your version of portable-threads to quicklisp. I noticed that when I compile I get this:

    ;;; ------------------------------------------------------------------------
    ;;;  Portable Threads Interface 2.3
    ;;;
    ;;;    Developed and supported by the GBBopen Project (http:/GBBopen.org/)
    ;;;    (See http://GBBopen.org/downloads/LICENSE for license details.)
    ;;; ------------------------------------------------------------------------

Might be good to adjust at least the "supported by" bit. And actually, probably good not to print such things during compile anyway.

**Comment by binghe** [comment]
Thanks! I'll cancel this message printing from the source code.

**Comment by binghe** [comment]
Load-time message printing cancelled. [1] I think we can close this ticket now.

I'll keep maintaining this important package and adding supports for more CL implementations (those bordeaux-threads supports but portable-threads doesn't, i.e. MKCL), starting from tomorrow.

[1] https://github.com/binghe/portable-threads/commit/a4ead202f8fc2af5c7191f1b402ac7fef2248ce7
