### ISSUE TITLE
Please remove "usocket-udp" and "asn.1" from Quicklisp

### ISSUE THREAD

**Issue by binghe** [quicklisp/quicklisp-projects#1214]
They're very old projects.

"usocket-udp" was a UDP extension for "usocket" project. It is replaced by "usocket" with UDP patch merged since 0.5.0 (March 2011)

The "asn.1" package was required by old versions of "snmp" for compiling SNMP MIB definitions to Lisp code, but now "snmp" (after version 6.0) includes all code of "asn.1".

After all these years, I don't believe anyone is still using above two packages, so please delete them.

**Comment by quicklisp** [comment]
I have removed asn.1. I will remove usocket-udp when cl-growl is updated in early November.

**Comment by binghe** [comment]
Thanks, that makes perfect sense.
