### ISSUE TITLE
Add bass bindings

### ISSUE THREAD

**Issue by resttime** [quicklisp/quicklisp-projects#1215]
Bindings to the Bass C library for all kinds of crossplatform audio and streaming functionality. A very fully featured audio libraries available that supports popular codecs and a simple way to play. Trumps a lot of the current options for Common Lisp right now in that respect.

http://www.un4seen.com/
https://github.com/resttime/bass

**Comment by quicklisp** [comment]
I can't build it in SBCL. There's an error with types-constants.lisp.

    error while parsing arguments to NIL DESTRUCTURING-BIND:odd number of elements in keyword/value list: (:COUNT)

More context here: http://report.quicklisp.org/2016-10-31/failure-report/bass.html

**Comment by resttime** [comment]
Oops, I had a symlink pointing to the wrong directory. I was wondering why I didn't catch that when I fixed that very same issue popping up elsewhere...

Okay it should be fixed now.

**Comment by resttime** [comment]
I've decided to restructure the bindings because some parts could stand to use a make over even though they currently work because I can't stand leaving in SWIG constants. I'll reopen the issue again when they're in good condition.
