### ISSUE TITLE
Please add omer-count

### ISSUE THREAD

**Issue by EclecticSoftwareEngineer** [quicklisp/quicklisp-projects#1218]
https://github.com/EclecticSoftwareEngineer/omer-count

**Comment by EclecticSoftwareEngineer** [comment]
I guess this didn't get into the latest dist because date-calc was removed? Will date-calc be gone permanently? (do you know?)

Thanks,
David

**Comment by quicklisp** [comment]
Yes, sorry about that. If someone wants to take over date-calc, it will come back, but until then, it is not part of Quicklisp.

**Comment by EclecticSoftwareEngineer** [comment]
No problem. I've switched the dependency from date-calc to local-time, so it should build fine again now.

Cheers,
David

**Comment by EclecticSoftwareEngineer** [comment]
This now depends on LOCAL-TIME, so should now build for Quicklisp.

Regards,
David

**Comment by antoszka** [comment]
@quicklisp Guess I could take over date-calc, does it need any major work at the moment other than stable hosting and maintenance?

**Comment by quicklisp** [comment]
This is in Quicklisp now.
