### ISSUE TITLE
Please add Graphic-Forms

### ISSUE THREAD

**Issue by ailisp** [quicklisp/quicklisp-projects#1224]
Graphic-Forms is a user interface library focusing on the Windows(R) platform.
 
Author: Jack Undue
Maintainer: Bo Yao
License: BSD
Code: https://gitlab.common-lisp.net/byao/Graphic-Forms

**Comment by quicklisp** [comment]
Sorry, I do not add Windows-only projects.

In the future I'd like to have a separate dist available for such things, but until then, I can't add graphic-forms.
