### ISSUE TITLE
Please add cl-digraph

### ISSUE THREAD

**Issue by sjl** [quicklisp/quicklisp-projects#1225]
[cl-digraph](http://sjl.bitbucket.org/cl-digraph) is an implementation of a directed graph data structure.  I got tired of reimplementing half-assed DAGs after the fourth time and made a library.  More info is in the README and docs.

Builds with no warnings in SBCL on OS X and Debian. Test suite passes in SBCL, CCL, ECL, and ABCL on OS X and Debian.  It should build/run on other OSes/implementations too -- I haven't tried.
License is MIT/X11.

Mercurial: https://bitbucket.org/sjl/cl-digraph/
Git mirror: https://github.com/sjl/cl-digraph/

Either one is fine to use as the source, they should be identical.

Thanks.

**Comment by quicklisp** [comment]
This doesn't build due to a reference to the QL package, which isn't present in the test build environment.

**Comment by sjl** [comment]
Quicklisp doesn't have quicklisp?  Okay, I removed the reference, it was just an old debugging function anyway.
