### ISSUE TITLE
Please add ahungry-fleece (small utility library)

### ISSUE THREAD

**Issue by ahungry** [quicklisp/quicklisp-projects#1229]
Please add Ahungry Fleece to Quicklisp, it aims to be a small utility library that adds convenience functions/classes to many things I find cumbersome to work with in the existing ecosystem.

Dependencies: cl-json, cl-yaml
License: GPLv3
Source: https://github.com/ahungry/ahungry-fleece
Branch: master

**Comment by ahungry** [comment]
I've added some new features to this (they should all be mentioned in the README).

Some of them are:
* file-get-contents / file-put-contents (easy way to provide a file path and string content and write it)
* ansi-colorize (give colorized output in shell)
* make-skelly-project (create a project with a similar setup as ahungry-fleece, complete with asd file showing one way to map out tests with the project, as well as makefile / build scripts to more easily integrate future projects into non-lisp environments)

Please let me know if you have any questions/opinions.

**Comment by quicklisp** [comment]
Out of curiosity, why is it file-put-contents rather than (setf (file-contents ...) ...)?

**Comment by ahungry** [comment]
Mostly since I didn't consider handling via setf after writing the distinct function :smile: 

But another reason is the function does have an optional key value for toggling if the file-put-contents call should overwrite or append to the file, and for new users of CL, it seems more natural (imo) to have a distinct function for each operation.

**Comment by quicklisp** [comment]
Why are sbcl contribs included in the source tree? They clash with existing sbcl contribs in Quicklisp.

**Comment by ahungry** [comment]
I've been working on getting the package to install well both via ql:quickload and roswell (ros install ahungry/ahungry-fleece) and was having some difficulty in getting roswell to properly require/find the contrib modules for the roswell saved core.

I renamed the packages so they shouldn't conflict at all (they don't use original names, they use names such as `af.contrib.sb-rotate-byte` etc.), as this also ensures certain features I'm now providing (coverage etc.) do not have dependent code break.

**Comment by quicklisp** [comment]
I don't see the renamed packages in the repo. Is there a pending push?

**Comment by ahungry** [comment]
Are you sure?  I didn't rename a file like 'cover.lisp' to 'af.contrib.cover.lisp', but you can see the updated defpackage in master branch:

https://github.com/ahungry/ahungry-fleece/blob/master/contrib/sb-cover/cover.lisp#L8
https://github.com/ahungry/ahungry-fleece/blob/master/contrib/sb-md5/md5.lisp#L34
https://github.com/ahungry/ahungry-fleece/blob/master/contrib/sb-md5/md5.lisp#L34

I left unaffected files from the contrib (the README/LICENSE and original asd files) untouched, so maybe you're looking at the asd files in these sub-directories?  (they aren't being used at all, as they aren't in anyone's load path).

You can see the custom package names being loaded as modules in my own asd:

https://github.com/ahungry/ahungry-fleece/blob/master/ahungry-fleece.asd#L39

**Comment by PuercoPop** [comment]
But the [defsystem](https://github.com/ahungry/ahungry-fleece/blob/master/contrib/sb-cover/sb-cover.asd#L3) is still named sb-cover

**Comment by ahungry** [comment]
That file isn't loaded at all, I am loading all the renamed `af.contrib.xxx` as modules file by file in my own defsystem.

I'll clean out of the repo so that is more apparent.
