### ISSUE TITLE
Add opticl-core and update opticl and retrospectiff

### ISSUE THREAD

**Issue by slyrus** [quicklisp/quicklisp-projects#1231]
I've created a new library [opticl-core](https://github.com/slyrus/opticl-core) which contains the core types and pixel getter/setter functions and macros. This is now used by opticl and retrospectiff.

**Comment by quicklisp** [comment]
It seems to have an implicit dependency on alexandria. Can't build without making it explicit

**Comment by slyrus** [comment]
Ok, guess I need to got some sort of CI running... In the meantime, this is fixed. Thanks for pointing it out.

**Comment by slyrus** [comment]
Xach, does this work for you now? Can you remove the cantbuild label if so?
