### ISSUE TITLE
Please Add CL-SPIDEV

### ISSUE THREAD

**Issue by Shinmera** [quicklisp/quicklisp-projects#1247]
This is a bindings library for the Linux SPIDEV kernel module as described on <https://www.kernel.org/doc/Documentation/spi/spidev>. It provides both direct low-level, and high-level convenient access.

Author: Nicolas Hafner
Source: https://github.com/Shinmera/cl-spidev.git
Documentation: https://shinmera.github.io/cl-spidev/

**Comment by quicklisp** [comment]
When I try to build, it fails. Log is here: http://report.quicklisp.org/2017-01-23/failure-report/cl-spidev.html

    ; caught WARNING:
    ;   Derived type of (SB-SYS:SIGNED-SAP-REF-32 SB-ALIEN::SAP (/ SB-ALIEN::OFFSET SB-VM:N-BYTE-BITS)) is (VALUES (SIGNED-BYTE 32) &OPTIONAL), conflicting with its asserted type SB-ALIEN-INTERNALS:ALIEN-VALUE.

**Comment by Shinmera** [comment]
Should be good now.
