### ISSUE TITLE
 Update to new version of anaphora

### ISSUE THREAD

**Issue by phmarek** [quicklisp/quicklisp-projects#1249]
`Anaphora` is now nearly 6 years old, and there've been a few changes in the meantime; eg. the ASDF metadata addition (:license).

Please update.
Thanks a lot!

**Comment by quicklisp** [comment]
I get anaphora from https://common-lisp.net/project/anaphora/files/anaphora-latest.tar.gz. Is anaphora getting updated with new releases without updating that file.

**Comment by phmarek** [comment]
Looks like it, https://github.com/tokenrove/anaphora/commits/master has a few more commits.

**Comment by quicklisp** [comment]
How are the two projects related?

**Comment by phmarek** [comment]
On https://common-lisp.net/project/anaphora/ the "The latest source may be obtained <from github>." link points to that repository.
