### ISSUE TITLE
Please add cl-str, a modern and consistent string manipulation library

### ISSUE THREAD

**Issue by vindarel** [quicklisp/quicklisp-projects#1250]
https://github.com/vindarel/cl-str

It is a terse and consistent string manipulation library.

discussion: https://www.reddit.com/r/learnlisp/comments/5mxv7v/sbcl_my_take_on_a_common_lisp_string_manipulation/

**Comment by quicklisp** [comment]
Does not build - the defsystem name must match the file name.

**Comment by vindarel** [comment]
I renamed asd and lisp files to `[test-]str.[asd, lisp]`.

Thanks.

**Comment by quicklisp** [comment]
Still does not build. Please test until it loads cleanly with: `(ql:quickload "str" :verbose t)`

**Comment by PuercoPop** [comment]
@vindarel the problem is that you are defining the str pacakge twice, once using asdf and the other using prove. You can solve that by defining the str ASDF system in the `#:asdf-user` package instead.

**Comment by vindarel** [comment]
Ok it loads correctly with verbose at t. (sorry, my bad in that).

@PuercoPop sounds interesting but I'm not sure I got it :D but it loads ok now.

**Comment by quicklisp** [comment]
I still can't load it due to package variance issues.

You should not define the "str" package in str.asd. It is better to remove the defpackage and use `(in-package #:asdf-user)` instead.

**Comment by vindarel** [comment]
I did what you said, hopefully: I removed

**Comment by vindarel** [comment]
I did (hopefully) what you mean:
```
-(in-package :cl-user)
-(defpackage str
-  (:use :cl :asdf))
-(in-package :str)

+(in-package #asdf-user)
```
it loads ok.
