### ISSUE TITLE
Please add bit-ops

### ISSUE THREAD

**Issue by guicho271828** [quicklisp/quicklisp-projects#1254]
https://github.com/guicho271828/bit-ops

Tools for writing optimized bit-vector routines (with a review article on the existing bit-vector libraries --- writing something like this for every quicklisp submission should be encouraged among lispers.).

**Comment by guicho271828** [comment]
Perhaps, like a scientific paper, having a `:related-work` section in the asdf file could reduce the choise paralysis...

**Comment by quicklisp** [comment]
Thank you for the review.

I can't build, though - in SBCL, getting an error about an unsupported DOCUMENTATION option.

http://report.quicklisp.org/2017-02-06/failure-report/bit-ops.html has the build log.

**Comment by guicho271828** [comment]
oh, I forgot that warnings are treated as errors in quicklisp submission. Will fix it before Feb updates.

**Comment by guicho271828** [comment]
Fixed.
