### ISSUE TITLE
Please add NAMED-READ-MACROS

### ISSUE THREAD

**Issue by williamyaoh** [quicklisp/quicklisp-projects#1256]
`NAMED-READ-MACROS` is a library which provides a definition facility to define read macros and attach them to symbols, avoiding the possibility of collisions in readtable characters.

Dependencies: `named-readtables`
License: BSD 3-Clause
Source: https://github.com/williamyaoh/named-read-macros
Branch:`master`

**Comment by guicho271828** [comment]
[cl-syntax](http://quickdocs.org/cl-syntax/) ?
