### ISSUE TITLE
Please add Agnostic Lizard

### ISSUE THREAD

**Issue by 38a938c2** [quicklisp/quicklisp-projects#1257]
Agnostic Lizard is a portable implementation of a code walker and in
particular of the macroexpand-all function (and macro) that makes a best
effort to be correct while not expecting much beyond what the Common Lisp
standard requires.

Source: https://gitlab.common-lisp.net/mraskin/agnostic-lizard.git
Branch: master
Dependencies: none
License: GPLv3+

Alternatives: `macroexpand-dammit` (only macroexpansion, removes `macrolet`), `hu.dwim.walker` (significant implementation-specific code, not all implementation support up to date), `trivial-macroexpand-all` (only macroexpansion, maximally implementation-specific but supports a lot of implementations), `swank` (implementation-specific but supports a lot of implementations, no code walker)

Thanks.

**Comment by quicklisp** [comment]
Can you please add :author to the system definition?

**Comment by 38a938c2** [comment]
Sorry, forgot to do it. Done now.
