### ISSUE TITLE
Please add CL:ZEROCONF

### ISSUE THREAD

**Issue by phmarek** [quicklisp/quicklisp-projects#1260]
Please add https://github.com/wiseman/cl-zeroconf.

Thank you very much!

**Comment by xach** [comment]
This is a very old repo from an author who does not do Common Lisp any more. Have you tried this project? Does it work properly?

**Comment by phmarek** [comment]
No, I didn't test it; you think that the zeroconf standard changed in the meantime?

I'll test that one (and perhaps https://code.google.com/archive/p/cl-dns-sd/source) and will get back to you.

Thanks a lot!

**Comment by phmarek** [comment]
Or, rather, https://github.com/jaeschliman/cl-dns-sd.
