### ISSUE TITLE
Please add freebsd-sysctl

### ISSUE THREAD

**Issue by shamazmazum** [quicklisp/quicklisp-projects#1268]
`freebsd-sysctl` is an interface to FreeBSD's `sysctl` kernel control mechanism for Common Lisp. I use it in my module for StumpWM to monitor CPU temperature. Maybe it will be useful for others.

Source: https://github.com/shamazmazum/freebsd-sysctl.git

**Comment by quicklisp** [comment]
Does this work only on FreeBSD? If so, I'm afraid I can't build and test it - I can only test things that run on Linux (as well as other systems).

**Comment by shamazmazum** [comment]
I cannot say for sure, but I think it can be built everywhere, but works
only in FreeBSD. As for CL implementation, it works anywhere where CFFI
works.

27 февр. 2017 г. 16:02 пользователь "Zach Beane" <notifications@github.com>
написал:

Does this work only on FreeBSD? If so, I'm afraid I can't build and test it
- I can only test things that run on Linux (as well as other systems).

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/quicklisp/quicklisp-projects/issues/1268#issuecomment-282713206>,
or mute the thread
