### ISSUE TITLE
change source of arnesi

### ISSUE THREAD

**Issue by bobbysmith007** [quicklisp/quicklisp-projects#1278]
The current source for arnesi elides its history.  There was a bug / maintainership request from fare here: https://github.com/vseloved/arnesi/issues/2

I will be maintaining arnesi indefinitely anyway, so I may as well be the official maintainer since there doesnt seem to be a vocal or active one.

Please change arnesi main repository to:
https://github.com/AccelerationNet/arnesi/
away from:
https://github.com/vseloved/arnesi

Cheers,
Russ

**Comment by quicklisp** [comment]
Can you please add a :description to the system definition?

**Comment by bobbysmith007** [comment]
I added a :description, :author, :license and :version to the asd file

**Comment by bobbysmith007** [comment]
Thanks for the heads up, this seems to have been a change in the update to asdf3.   I will see if this can simply be uncommented as a solution.

**Comment by bobbysmith007** [comment]
Uncommenting that line in the asd allowed me to build yaclml from quicklisp and seems to satisfy its "ENSURE-SYSTEM-HAS-FEATURE" call.  I also have an email out to Faré asking why that was commented out.

Cheers and thanks
