### ISSUE TITLE
Please fix 'asdf-package-system'

### ISSUE THREAD

**Issue by stykhanskyy** [quicklisp/quicklisp-projects#1279]
Currently this package (and all packages that depends on it, in particular I'm interested in `infix-math`) are failing because author replaced library with the stub that just checks ASDF to be of version "3.1.2" (https://gitlab.common-lisp.net/asdf/asdf-package-system/commits/master) and fails if it is not.

Would it be possible to lock this library to commit `9e1d75d17c42a551f2799443ef16b561efafecc5` (latest commit before stubbing) to keep it working until ASDF will be upgraded to v3?

**Comment by quicklisp** [comment]
If a project needs asdf 3 to work, and it does not come with your implementation, you will need to install it manually.

**Comment by stykhanskyy** [comment]
The project asdf-package-system itself doesn't need ASDF 3. It's purpose actually was to polyfill one of ASDF 3 features to ASDF 2.

Author of this package for some reason instead of just keeping project as is, removed all functionality and forced all clients to update to ASDF 3. So in that sense it's just useless now, but commit `9e1d75d17c42a551f2799443ef16b561efafecc5` would still work for dependent libraries.

**Comment by quicklisp** [comment]
If that is the author's wish, that is the author's wish. I do not want to choose a different version to bundle in Quicklisp.

**Comment by stykhanskyy** [comment]
I understand.
Thank you for such a quick response.
