### ISSUE TITLE
Please add cl-why

### ISSUE THREAD

**Issue by jpcima** [quicklisp/quicklisp-projects#1283]
Please add cl-why: (X)HTML generation macros, fork of CL-WHO
https://github.com/jpcima/cl-why

Tests pass in SBCL and ECL, and works in CLISP despite one minor failure.

    (ql:quickload :cl-why)
    (ql:quickload :cl-why-test)
    (cl-why-test:run-all-tests)

**Comment by quicklisp** [comment]
Please ensure each system definition has a :description, :author, and :license.

**Comment by jpcima** [comment]
I have added the missing metadata in cl-why and cl-why-tests.
