### ISSUE TITLE
Please, add cl-hamcrest

### ISSUE THREAD

**Issue by svetlyak40wt** [quicklisp/quicklisp-projects#1294]
This is a set of helpers to make unit tests more readable by using Hamcrest assertions.

Source: https://github.com/40ants/cl-hamcrest
Documentation: http://40ants.com/cl-hamcrest/

**Comment by quicklisp** [comment]
Oops, this does not actually build - I get this error:

    Error finding package for symbol "INDENT":
     The name "PROVE.REPORTER" does not designate any package.

**Comment by svetlyak40wt** [comment]
Oh, thank you for pointing to this issue.

Fixed in commit https://github.com/40ants/cl-hamcrest/commit/9bbfee10b8d6766e143a9d783a2267b02585ff29

**Comment by svetlyak40wt** [comment]
@quicklisp please, verify again.
