### ISSUE TITLE
Please add simple-routes

### ISSUE THREAD

**Issue by vancan1ty** [quicklisp/quicklisp-projects#1295]
Simple-routes provides a method for simple, centralized http routing on top of Hunchentoot.  When used in conjunction with hunchentoot this library takes priority over the default hunchentoot routing system but does not replace it.  If simple-routes does not match a handler to a given request, it will fall back to hunchentoot's other url routing methods (easy-handler, then the default static file service).

Author: Currell Berry
Source: https://gitlab.com/vancan1ty/simple-routes.git
Documentation: https://gitlab.com/vancan1ty/simple-routes/blob/master/README.md

**Comment by svetlyak40wt** [comment]
What is the difference between simple-routes and http://quickdocs.org/cl-routes/?

**Comment by vancan1ty** [comment]
I could not find an example of cl-routes in use, so I cannot provide a usage comparison without looking more into how cl-routes works.  Here are some differences just from cursorily looking at cl-routes.

- No code relation between the two packages
- cl-routes claims to be a reimplementation of the ruby-on-rails routing system, simple-routes does not have any relation to ruby on rails
- simple-routes's included examples show its usage -- it uses macros to compile route specifiers which are bound to functions invoked when the route specifiers are matched.  cl-routes is a larger and more complicated piece of software -- again, without a MWE I cannot say exactly how the user-experience compares.

simple-routes is basically a minimal way to declaratively bind HTTP URI's to handlers.
