### ISSUE TITLE
Who is maintaining puri?

### ISSUE THREAD

**Issue by binghe** [quicklisp/quicklisp-projects#1296]
Hi,

I'm using "puri" from Quicklisp, the full source directory name is "puri-20150923-git". I believe that I'm using the latest version. In the source code, one major method's body has used a strange declaration `(declare (ignore-if-unused ,var ,g-ignore))`, with "ignore-if-unused" undefined, and it caused a compiler warning (at least) in LispWorks:

;;;*** Warning in GX:LIST-ALL-URI-NAMEDSPACES: Don't know what to do with declaration (PURI::IGNORE-IF-UNUSED
                                                                                       GX::X
                                                                                       #:G4397).

I want to report this issue and suggest replacing all "ignore-if-unused" into "ignorable", but this project seems not maintained in GitHub, what I found is just this in Quicklisp project database, the "source.txt" of "puri" project:

kmr-git puri

I don't know how "kmr-git" is defined. So who should I contact with to get this issue fixed (if it's indeed an issue)?

Regards,

Chun Tian

**Comment by quicklisp** [comment]
Kevin Rosenberg maintains puri on on git.kpe.io. He can be contacted for
such suggestions.

**Comment by PuercoPop** [comment]
@binghe The repo you are looking for is, http://git.kpe.io/?p=puri.git;a=summary iit can be found in the [quicklisp-controller](https://github.com/quicklisp/quicklisp-controller/blob/02a6c0789498a639382646b86f520db820a7a09d/upstream-misc.lisp#L47). You can find the mail of the mantainer in the git commit. Also from mail addressed the clsql mailing I'm guessing the puri mailing list, if there is one, is `puril at boa.kpe.io`

**Comment by binghe** [comment]
Thanks very much! I'll contact Kevin Rosenberg or post into PURI's mailing list shortly.
