### ISSUE TITLE
I cannot open https://www.quicklisp.org/ because of SSL Cert issue

### ISSUE THREAD

**Issue by veer66** [quicklisp/quicklisp-projects#1298]
I cannot open https://www.quicklisp.org/ because of SSL Cert issue.

![quicklisp](https://cloud.githubusercontent.com/assets/370688/25564458/d5b21b5e-2ddd-11e7-9b2a-40bd6d1d151f.png)

**Comment by Hexstream** [comment]
For what it's worth, I can't reproduce on Chrome and Firefox, and an SSL labs test seems to be saying that everything is in order:
https://www.ssllabs.com/ssltest/analyze.html?d=www.quicklisp.org&hideResults=on

You seem to be using Firefox, did you try with Chrome or other browsers?
I'm not sure if trying with extensions disabled could help...

It couldn't hurt to specify what exact versions of operating systems and browsers you're using, etc.

Hope this helps.

**Comment by guicho271828** [comment]
I can access it from Japan, Ubuntu 16.04 Firefox. Perhaps a regional issue? Is it from Thailand?

**Comment by veer66** [comment]
It works now. 

Yesterday I also used Chromium and accessed it from a server in Paris but it didn't work but when I tried again after 1 hour, it worked.

**Comment by veer66** [comment]
Sometimes I can reproduce it by even using cURL. From Bangkok, Paris and Singapore.

````
curl -O https://beta.quicklisp.org/quicklisp.lisp

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (60) SSL certificate problem: certificate has expired
More details here: https://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
````

**Comment by veer66** [comment]
And now it works!

````
curl -O https://beta.quicklisp.org/quicklisp.lisp
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 57144  100 57144    0     0  86755      0 --:--:-- --:--:-- --:--:-- 86713
````

I will try curl for 1 day and show you when it doesn't work.

**Comment by quicklisp** [comment]
The certificate expired over the weekend. I updated www.quicklisp.org a few days ago and beta.quicklisp.org a few hours ago. Please let me know if you see any lingering SSL failures.

**Comment by veer66** [comment]
Thank you.
