### ISSUE TITLE
Please move cl-cffi-gtk.

### ISSUE THREAD

**Issue by Ferada** [quicklisp/quicklisp-projects#1302]
The original repository at https://github.com/crategus/cl-cffi-gtk is unmaintained since ~one year.

I'm maintaining a copy at https://github.com/Ferada/cl-cffi-gtk which fixes several of the existing open issues and aims to improve the bindings; I did contact Dr. Dieter Kaiser to get permissions to push to the original repository, however that didn't happen after some months due to time constraints, presumably.

Therefore I'm requesting a switch for the source in Quicklisp so that improvements are more visible. In case Dieter or anyone else wants to take over again I'm more than happy to let them do that too.

**Comment by quicklisp** [comment]
Please make sure all system definitions have :author, :description, and :license.

**Comment by Ferada** [comment]
I've put additional info on all files, they have those fields now.

**Comment by stacksmith** [comment]
It would be a great help to the community.  cl-cffi-gtk has many issues that can be fixed; it is a very large library that is full of issues without a responsive maintainer. @Ferada has been both actively maintaining his branch, and a great help with resolving problems.
