### ISSUE TITLE
Please update ironclad

### ISSUE THREAD

**Issue by phoe** [quicklisp/quicklisp-projects#1303]
The source repository for Ironclad needs to be updated as the current one is no longer maintained.
https://github.com/glv2/ironclad/issues/1

**Comment by quicklisp** [comment]
Who is "glv2"?

**Comment by glv2** [comment]
I'm one of the contributors to Ironclad.

As @froydnj decided to stop maintaining his Common Lisp libraries, I sent him an email a few weeks ago to ask him if he could give write access to the Ironclad repository to @eadmund and me (we are the main contributors) so that we could continue maintaining the library in the original repository.
I didn't get any response yet.

**Comment by quicklisp** [comment]
I would prefer to wait some more for @froydnj's response.

**Comment by quicklisp** [comment]
@glv2 Would you be up for maintaining it under the sharplispers umbrella?

**Comment by glv2** [comment]
Yes, maintaining it with the sharplispers seems like a good idea.

**Comment by eadmund** [comment]
Ditto. It's a pity we've not heard back from Nathan; Ironclad really is a
nice library.

Bob

**Comment by phoe** [comment]
@eadmund It seems we have heard from him, just on a different medium. @xach can possibly give more detail.

**Comment by froydnj** [comment]
Sorry for the delayed response.  Found these messages in my spam folder!

I'm more than happy for the location for Ironclad (and any other libraries) to point someplace else; I'm also happy to actually transfer ownership of the repository (if that's a thing) out of my account into somebody else's hands.

**Comment by Hexstream** [comment]
Finally!

Yes, you can easily transfer ownership of the repository, the option is at the bottom of https://github.com/froydnj/ironclad/settings.

That will preserve all stars, watchers, etc, as well as redirecting from the old location to the new one. That would be a very great thing to do...

**Comment by quicklisp** [comment]
This is now taken from the sharplispers repo.

**Comment by eadmund** [comment]
We'll need to do the same with the nibbles library as well.

**Comment by quicklisp** [comment]
Nibbles has already moved.
