### ISSUE TITLE
Please Add cl-soloud

### ISSUE THREAD

**Issue by Shinmera** [quicklisp/quicklisp-projects#1304]
This is a bindings library to [SoLoud](http://sol.gfxile.net/soloud/) which allows easy cross-platform mixing and playback.

Author: Nicolas Hafner
Source: https://github.com/Shirakumo/cl-soloud
Documentation: https://shirakumo.github.io/cl-soloud/

**Comment by quicklisp** [comment]
Do you know of a debian packaging of soloud? I looked at building the source, but it requires some build tools I don't have.

**Comment by Shinmera** [comment]
Do you need to build the source? It should load out of the box as I include the binaries as usual.

I don't know of any ready to use packages of SoLoud for any distribution unfortunately, and indeed the build system is rather annoying as it needs an obscure python script to actually generate a makefile first.

**Comment by quicklisp** [comment]
It doesn't build out of the box for me, it complains about missing foreign libraries. I see that there are binaries in the source, but for whatever reason, they are not found during the build for me.

**Comment by Shinmera** [comment]
Hmm. Might be due to missing dependencies. What's your debian version? I'll see if I can reproduce it as soon as I can.

**Comment by quicklisp** [comment]
I'm using Debian 8. "ldd" shows this:

    /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.9' not found

**Comment by Shinmera** [comment]
Alright, I've recompiled the binary for linux on a clean system. It loads now in my Debian 8 VM.
