### ISSUE TITLE
Please add simple-logger

### ISSUE THREAD

**Issue by mfiano** [quicklisp/quicklisp-projects#1305]
This is a very simple means of logging messages of the usual verbosity levels to standard output. It was created as a simple alternative to others available, although nowhere near as feature-complete. This is meant to be extremely lightweight. If you want something a little more advanced, I would recommend verbose (https://github.com/Shinmera/verbose)

https://github.com/mfiano/simple-logger

**Comment by Shinmera** [comment]
I'm not sure what this is about. I added the necessary features you requested to bypass the threading behaviour in Verbose following Shinmera/verbose#2

**Comment by mfiano** [comment]
@Shinmera I did not mean any offense by this. I appreciate a lot of your software a lot. We did follow up on that fix, and encountered more inconveniences, which I do not recall but I don't think they could be called bugs. We just wrote something extremely simple. Thank you for your contributions to Lisp. I mean that.

**Comment by Shinmera** [comment]
Alright. I still would liked to hear about the inconveniences you've encountered, should you remember them at some point.
