### ISSUE TITLE
Please add fs-utils

### ISSUE THREAD

**Issue by mfiano** [quicklisp/quicklisp-projects#1307]
fs-utils is a (as of yet) small collection of functions for dealing with file paths, that I continue to find useful. Its primary use is for referencing assets relative to a project, which works for both a running image via ASDF and a dumped image binary via UIOP.

https://github.com/mfiano/fs-utils

**Comment by cbaggers** [comment]
I'll pop this here although it would apply to many of your recent requests:

> In the issue, please provide a brief description of what your project is for and where to fetch its sources.

See also [here](http://blog.quicklisp.org/2015/01/getting-library-into-quicklisp.html)

I can't find a reference too it now, but it can be nice to explain how your lib differs from any of the others when the implementations overlap significantly

**Comment by mfiano** [comment]
@cbaggers Thanks, I normally remember to do this, but I was in a hurry last night. Apologies
