### ISSUE TITLE
Please add doplus again

### ISSUE THREAD

**Issue by alessiostalla** [quicklisp/quicklisp-projects#1320]
doplus, the high-level, extensible iteration construct used to be in Quicklisp, but it was removed following the demise of Google Code where it used to be hosted.
The project however is hosted on BitBucket: https://bitbucket.org/alessiostalla/doplus
You can check the code out using Mercurial, the repository is located at https://bitbucket.org/alessiostalla/doplus (same as the project home).

Thanks in advance.

**Comment by cbaggers** [comment]
@alessiostalla if it's of any use, I backed up a bunch of projects from gitorious and a few from google code when they were shutting down https://github.com/GitoriousLispBackup

**Comment by alessiostalla** [comment]
@cbaggers thanks, I should have everything hosted on BitBucket, but if I find anything missing it's reassuring to know about your repositories :)
