### ISSUE TITLE
Please add TRIVIAL-SWANK

### ISSUE THREAD

**Issue by stacksmith** [quicklisp/quicklisp-projects#1334]
TRIVIAL-SWANK is a library that establishes and manages a connection to a SWANK server using the SLIME protocol.  BSD simplified license.

https://github.com/stacksmith/trivial-swank/tree/quicklisp

**Comment by Shinmera** [comment]
How does this differ from https://github.com/eudoxia0/swank-protocol ?

**Comment by stacksmith** [comment]
To be honest, I could not find in my notes why I wound up writing it, but I did have a reason (I remember being agitated about it).  I had some thread-related issues at the time with cl-cffi-gtk, so possibly that.  TRIVIAL-SWANK uses a separate receiver thread.  
My favorite thing: it lets you make remote calls ( emacs-rex or eval) and pass a closure to handle the response at a later time.

**Comment by quicklisp** [comment]
There seems to be an implicit dependency on swank as the swank package is referenced in trivial-swank.lisp.

**Comment by stacksmith** [comment]
It was not a dependency, just some fooling around/test/comparison code I guess; I was having some problems with presentations a long time back.   I took it out.  Thanks
