### ISSUE TITLE
Please Add Deploy

### ISSUE THREAD

**Issue by Shinmera** [quicklisp/quicklisp-projects#1337]
This is a system to help you easily and quickly deploy standalone common lisp applications as binaries. Specifically it is geared towards applications with foreign library dependencies that run some kind of GUI.

Author: Nicolas Hafner
Source: https://github.com/Shinmera/deploy
Documentation: https://shinmera.github.io/deploy/

**Comment by Hexstream** [comment]
Suitably 1337! Sorry. :)
