### ISSUE TITLE
:drakma project is not up to date...

### ISSUE THREAD

**Issue by brendandburns** [quicklisp/quicklisp-projects#1347]
There is a release 2.0.3, but quicklisp is stuck on 2.0.2

I'm happy to do the update if you send a pointer...

Thanks!

**Comment by quicklisp** [comment]
Quicklisp is updated every month, and will automatically pick up the 2.0.3 update in time.

**Comment by aarvid** [comment]
> (defclass ediware-http-source (predictable-http-source) ()
>   (:default-initargs
>    :location-template "http://weitz.de/files/~A.tar.gz"))
> 
> 

The problem is that "http://weitz.de/files/drakma.tar.gz" is still version 2.0.2 whereas github is 2.0.3 In fact, the [drakma](http://weitz.de/drakma/#install) page still considers 2.0.2 as the current version.

I will open an issue on drakma's github.

**Comment by quicklisp** [comment]
My mistake! I thought I was using the latest github release already. I can fix it on my end.
