### ISSUE TITLE
Searchable list of projects not up to date?

### ISSUE THREAD

**Issue by dfmorrison** [quicklisp/quicklisp-projects#1353]
I notice that some of the recently added projects are not included in

https://www.quicklisp.org/beta/releases.html

Does this normally lag behind a bit, or is this perhaps a bug in whatever is supposed to update it?

And while I'm at it, thanks ever so much for Quicklisp. It really is wonderful.

**Comment by quicklisp** [comment]
I updated it today, thanks for the reminder.

**Comment by dfmorrison** [comment]
I'm not sure the update has completely taken. While things appear in the list, when you look for them with the search box they don't show up. For example

sanitized-params is now in Quicklisp, and does appear in the text on that page

But typing "sanitized-params" or "sanitized" into the search box turns up nothing, and "params" turns up only quri.
