### ISSUE TITLE
Please add lisp-chat

### ISSUE THREAD

**Issue by ryukinix** [quicklisp/quicklisp-projects#1354]
Lisp-chat is a experimental chat which provides the server and the client.

https://github.com/ryukinix/lisp-chat

**Comment by quicklisp** [comment]
The source refers to "QL:", which isn't available in the quicklisp build environment. You could protect it with #-quicklisp or just rely on the system definition to ensure usocket is loaded.

**Comment by quicklisp** [comment]
Please reopen if this gets fixed.

**Comment by ryukinix** [comment]
@quicklisp I fixed that on the master right now. You can try again?

**Comment by quicklisp** [comment]
Looks better now!

**Comment by ryukinix** [comment]
Thanks for adding!
I tried to build and works as expected. I'm close that issue since was solved.
