### ISSUE TITLE
Please update cl-ssdb

### ISSUE THREAD

**Issue by muyinliu** [quicklisp/quicklisp-projects#1357]
I'm sorry to tell you that [cl-ssdb](https://github.com/muyinliu/cl-ssdb/) released in quicklisp dist 2017-06-30 has a serious bug: not support data with non-ASCII character. I made a fix at 2017-07-01. Could you please update cl-ssdb to newest version? 

Thank you.

**Comment by quicklisp** [comment]
This will be updated automatically in the next release.

**Comment by muyinliu** [comment]
Thank you.
