### ISSUE TITLE
Please add trivial-file-size

### ISSUE THREAD

**Issue by ruricolist** [quicklisp/quicklisp-projects#1363]
https://github.com/TBRSS/trivial-file-size

A library that lets you somewhat portably stat a file's size.

**Comment by vindarel** [comment]
hi, were you aware of osicat-posix and its `stat-size` function ?

- https://lispcookbook.github.io/cl-cookbook/files.html#getting-file-attributes-size-access-time-with-the-osicat-library
- shamefully not documented: https://github.com/osicat/osicat/issues/20#issuecomment-321828659

**Comment by ruricolist** [comment]
Thanks. I am aware of Osicat, but I thought there was still a place for a trivial-X library that exposes what is, in many (most?) Lisps, built-in functionality.
