### ISSUE TITLE
Please add TRIVIAL-PROJECT

### ISSUE THREAD

**Issue by stacksmith** [quicklisp/quicklisp-projects#1366]
`git clone -b quicklisp https://github.com/stacksmith/trivial-project.git`

https://github.com/stacksmith/trivial-project/tree/quicklisp

A simple tool for creating new 'projects' populated with files.  Starting with reasonable defaults, almost every aspect of the project generation is configurable, including multi-pass key-value substitution of text in files, filename renaming, specification of manifests, and even the syntax of the substitution engine.
 
@xach - consider it an alternative to your wonderful quickproject that uses a  different approach.

**Comment by quicklisp** [comment]
The current Quicklisp dist build process does not include quicklisp itself. Is it possible to omit or conditionalize the Quicklisp-referencing portions of the project?

**Comment by stacksmith** [comment]
I just noticed it this morning.  
What is the recommended way of getting the local project directories of ASDF?  I think that's the only reference to quicklisp.

**Comment by stacksmith** [comment]
Did not mean to sound presumptuous... I am having trouble figuring out the correct way to get the local project path(s), outside of looking at quicklisp's.  The more I look, the more confusing it gets.  Can you suggest a portable way of doing so?

**Comment by josrr** [comment]
I use asdf:component-pathname and asdf:find-system.

**Comment by stacksmith** [comment]
@josrr - These are useful to find the path of the currently running system.  asdf:system-relative-pathname is also useful.

But I am looking for the path of the user's local projects...  like quicklisp's *local-project-directories*, but asdf's.

**Comment by stacksmith** [comment]
@xach - I made quicklisp conditional; it should work now.

I still don't know if asdf exports its view of user's local directories. It seems that it goes through a lot of trouble to get at them and really should expose its findings...
