### ISSUE TITLE
Please add TRIVIAL-RENAMER

### ISSUE THREAD

**Issue by stacksmith** [quicklisp/quicklisp-projects#1369]
quicklisp branch of https://github.com/stacksmith/trivial-renamer.git

TRIVIAL-RENAMER is a component for rule-based regex renaming and maintenance of named Lisp objects, such as files, MP3 headers, or  FFI symbols and types.

Depends on cl-ppcre

Thanks

**Comment by guicho271828** [comment]
Is it a sort of a refactoring tool?

**Comment by stacksmith** [comment]
@guicho271828 It is more of a toolmaker's tool for any number of things.  It does not actually rename anything; it creates a one-to-one mapping between your strings and rule-generated strings.  You can then use it to do the actual 'renaming'.  I just couldn't think of a better name for it; renamer communicates the nature of the activity better than other ideas I had.

Ig uses rules and regexes, and maked sure that there are no collisions in either forward or backward mapping.  For instance, if you want to rename files in a directory, you can create rules that are file-extension based to leave some alone, and rename some, say, .lisp files that start or contain a substring to something else, making sure that your rules don't rename more than one file to the same name. 

I don't think it's easy to rename lisp symbols, if that's what you mean by refactoring...

Personally I use it to generate lisp names for c identifiers in an ffi generator.

**Comment by guicho271828** [comment]
thank you for the explanation.
