### ISSUE TITLE
Please add POIU

### ISSUE THREAD

**Issue by phmarek** [quicklisp/quicklisp-projects#1376]
http://www.cliki.net/poiu

    poiu is an asdf extension that builds in parallel.

Apart from being useful for the end-user already, QL might use POIU by itself, too.

**Comment by Hexstream** [comment]
`https://gitlab.common-lisp.net/qitab/poiu.git` appears to be the official location for the `poiu` repository, found at https://common-lisp.net/project/qitab/.
