### ISSUE TITLE
Please add OSCAR

### ISSUE THREAD

**Issue by binghe** [quicklisp/quicklisp-projects#1378]
OSCAR [1] is a reasoner (just like ACL2) but for Defeasible Logic. It's developed by John L. Pollock in 1990s. OSCAR implemented a sophisticated system of defeasible reasoning that enables it to deal defeasibly with:

- perception
- change and persistence
- causation
- probabilities
- plan construction and evaluation

The area is "Strong AI" and "rational agents".  Two years ago someone (I don't know him) put the original source code in Github without any modifications, then several days ago I created ASDF definitions and made the code loadable in major CL platforms. The original development platform is Macintosh Common Lisp 4.2, if you run these code in latest Rosetta-based MCL (RMCL) 5.2 or 6.0 in Mac OS X 10.5 or 10.6, there's even a GUI interface (but half-broken now).

The original author has passed away in 2013, and I'm going to maintain this project from now on. The LICENSE is the same as in the original website, copyright belongs to Lilian Jacques <support@johnpollock.us>. Use with cautions.

Any way, the project repository is here:

    https://github.com/binghe/OSCAR-Lisp

The initial version is 4.0. Please do not use snapshots on master branch, instead please use the released tarballs. I hope every time when I push a new release in Github, Quicklisp also uses this new release.

Regards,

Chun Tian

[1] http://johnpollock.us/ftp/OSCAR-web-page/oscar.html

**Comment by quicklisp** [comment]
Hi,

This license is too restrictive for inclusion in Quicklisp, sorry.

**Comment by binghe** [comment]
Thanks.
