### ISSUE TITLE
Please move aws-sign4, cl-html5-parser, gettext, json-streams and secret-values

### ISSUE THREAD

**Issue by bakketun** [quicklisp/quicklisp-projects#1390]
The following projects have moved to new locations:

aws-sign4: git https://github.com/rotatef/aws-sign4.git
cl-html5-parser: git https://github.com/rotatef/cl-html5-parser.git
gettext: git https://github.com/rotatef/gettext.git
json-streams: git https://github.com/rotatef/json-streams.git
secret-values: git https://github.com/rotatef/secret-values.git

**Comment by quicklisp** [comment]
Can you tell me more about this move?

**Comment by bakketun** [comment]
The repositories have been moved to a new organization on github. The old urls still work, github redirects to the new url.

https://github.com/copyleft belongs to the company Copyleft Solutions, my former employer.

I've started my own business with focus on making high quality libraries for Common Lisp. https://github.com/rotatef will be the default location for my projects.
