### ISSUE TITLE
Please add flac-metadata

### ISSUE THREAD

**Issue by mfiano** [quicklisp/quicklisp-projects#1392]
flac-metadata is a utility for reading metadata embedded in FLAC audio files.

https://github.com/mfiano/flac-metadata

**Comment by quicklisp** [comment]
The mismatch between the system file name (flac-read) and the system name (flac-metadata) means ASDF can't deal with it. Please leave a comment when it's in sync.

**Comment by mfiano** [comment]
This is fixed.
