### ISSUE TITLE
Suggestion for additional documentation

### ISSUE THREAD

**Issue by alphapapa** [quicklisp/quicklisp-projects#1393]
Hi Zach,

After developing some Emacs packages for a while, I've decided to venture into CL territory.  It's a different world, indeed.  :)  It seems like a lot of documentation out there is outdated, e.g. *Practical Common Lisp* doesn't even mention DEFSYSTEM.

I haven't done a very exhaustive search yet, but one of the most helpful, straightforward resources I've found is this blog post of yours from seven years ago:

http://xach.livejournal.com/278047.html

I'd like to suggest that the information there be linked on the Quicklisp site.  It seems to be several of the missing pieces that a new user needs.

Of course, it might be better to clean it up and post it as a document somewhere than to link to the blog post.  If you like, I'll volunteer to extract and edit the instructions from the blog post so you can post it elsewhere--with the caveat that I am still completely new to the CL packaging systems, so you would want to proofread it carefully.  :)

Thanks for your work on Quicklisp.

By the way, here's another post of yours that I found helpful: https://groups.google.com/d/msg/quicklisp/Zyi26fsMkg4/3_pk-55pnn8J

**Comment by antoszka** [comment]
Tako rzecze alphapapa (2017-10-28, 19:31):

> After developing some Emacs packages for a while, I've decided to venture into
> CL territory. It's a different world, indeed. :) It seems like a lot of
> documentation out there is outdated, e.g. *Practical Common Lisp* doesn't even
> mention DEFSYSTEM.

Practical Common Lisp isn't very practical in the sense of actually getting
things to run in realistic environments or packaging for deployment; you might
want to check out the excellent new book by Edi Weitz (himself an author of some
very good CL libraries): “Common Lisp Recipes” [1].

[1] http://weitz.de/cl-recipes/

**Comment by ryukinix** [comment]
@antoszka thanks for sharing it! Seems a awesome book! I like Practical Common Lisp to learn about the language, but the sense of "Practical" use here in comparison of the meaning used in nowadays is just misleading.

**Comment by alphapapa** [comment]
Yeah, thanks for sharing that.  Seems a bit expensive, but it does have a lot of pages.  I wish there were better samples available for viewing.

**Comment by ryukinix** [comment]
> Yeah, thanks for sharing that. Seems a bit expensive, but it does have a lot of pages. I wish there were better samples available for viewing.

[Sample on GitHub](https://github.com/clojurians-org/lisp-ebook/blob/master/Common%20Lisp%20Recipes(Apress%2C2015).pdf)

**Comment by alphapapa** [comment]
Thanks.  That appears to be the whole book, with a `www.allitebooks.com` watermark on it.  I'm guessing that shouldn't be on GitHub...

**Comment by ryukinix** [comment]
Well, if you buy later, just treat the file as a sample to convince you to buy or not. But indeed ... this should not be on GitHub, but it be here, what can we do?

**Comment by quicklisp** [comment]
I'll look into sharing more resources in more places soon.
