### ISSUE TITLE
Please add CCL-COMPAT and CCLDOC

### ISSUE THREAD

**Issue by phoe** [quicklisp/quicklisp-projects#1399]
https://github.com/Clozure/ccldoc
https://github.com/phoe/ccl-compat

CCLDOC is a documentation generator from CCL project.
CCL-COMPAT is a module for CCL compatibility, created to port CCLDOC outside CCL.

**Comment by quicklisp** [comment]
ccldoc.asd needs :author, :description, and :license fields first.

**Comment by phoe** [comment]
https://github.com/Clozure/ccldoc/issues/13

**Comment by phoe** [comment]
Done.
