### ISSUE TITLE
Please add specialization-store.

### ISSUE THREAD

**Issue by markcox80** [quicklisp/quicklisp-projects#1404]
https://github.com/markcox80/specialization-store/tree/v0.0.1

The specialization store system provides a new kind of function, called a store function, whose behavior depends on the types of objects passed to the function.

**Comment by quicklisp** [comment]
Should I use exactly v0.0.1, or whatever the latest tag/release is?

**Comment by markcox80** [comment]
Version 0.0.1 please. I will create an issue when there is an update.

**Comment by quicklisp** [comment]
This does not build due to an implicit dependency on alexandria. Build log is here: http://report.quicklisp.org/2017-11-20/failure-report/specialization-store.html

**Comment by markcox80** [comment]
https://github.com/markcox80/specialization-store/tree/v0.0.2
Sorry about that.
