### ISSUE TITLE
Please add qbase64

### ISSUE THREAD

**Issue by chaitanyagupta** [quicklisp/quicklisp-projects#1407]
https://github.com/chaitanyagupta/qbase64

It is a fast and flexible base64 encoding and decoding library for CL.

**Comment by guicho271828** [comment]
curious to see the speed comparison against http://quickdocs.org/cl-base64/ and http://quickdocs.org/s-base64/

**Comment by chaitanyagupta** [comment]
I was in fact writing some benchmarks today 😄. For me both speed and keeping memory use to a minimum was important. That said, I am quite pleased with the results: https://github.com/chaitanyagupta/qbase64/wiki/Benchmarks-vs-other-CL-libraries
