### ISSUE TITLE
Please add cl-libdsfmt

### ISSUE THREAD

**Issue by macdavid313** [quicklisp/quicklisp-projects#1408]
Common Lisp binding for dSFMT, a double precision SIMD oriented Fast Mersenne Twister pseudorandom number generator. 

Author: David Gu
Source: https://github.com/macdavid313/cl-libdsfmt

**Comment by quicklisp** [comment]
Where is the best place to get dSFMT? It's not easily available in Debian for me.

**Comment by macdavid313** [comment]
Hello,

the C files of dSFMT have already been included and will be compiled by `uiop:run-program` during loading. I just made some modifications today, please be sure you have pulled from the lasted git repo.

**Comment by quicklisp** [comment]
This does not build for me - there is a build-breaking WARNING in SBCL. 

    ; caught WARNING:
    ;   Derived type of #:TEMP1 is (VALUES (SIMPLE-VECTOR 2) &OPTIONAL), conflicting with its asserted type (OR CONS SYMBOL SB-KERNEL:CLASSOID CLASS).
    ;   See also:
    ;     The SBCL Manual, Node "Handling of Types"

Log is here: http://report.quicklisp.org/2017-11-30/failure-report/cl-libdsfmt.html

**Comment by xach** [comment]
Whatever happened to this project?
