### ISSUE TITLE
Add recommendation to README

### ISSUE THREAD

**Issue by azzamsa** [quicklisp/quicklisp-projects#1410]
Hi Xach.

What if we add to [README](https://github.com/quicklisp/quicklisp-projects#to-add-a-project-to-quicklisp) description, that after someone ask to add any library to Quicklisp, we recommend them also to make PR to [awesome-cl](https://github.com/CodyReichert/awesome-cl).
Because it will be faster and easier to build things when we have enough library :).

**Comment by quicklisp** [comment]
I don't know anything about awesome-cl, sorry, and don't want to get involved with it.

**Comment by azzamsa** [comment]
Thank you.
