### ISSUE TITLE
Please add sdraw

### ISSUE THREAD

**Issue by azzamsa** [quicklisp/quicklisp-projects#1411]
SDRAW - draws cons cell structures.

https://www.cs.cmu.edu/~dst/Lisp/sdraw/sdraw.generic

**Comment by quicklisp** [comment]
There are a few issues with adding sdraw. 

First, it's not a regular project with a download, a system file, and a README. That means extra work for packaging it up for quicklisp.

Second, there is no clear licensing information in the code, so it's not clear I can redistribute it as part of Quicklisp.

**Comment by azzamsa** [comment]
For the second problem, I can ask the license to the author for you.

But I think [draw-cons-tree](https://github.com/cbaggers/draw-cons-tree) already included in [Quicklisp relase](https://www.quicklisp.org/beta/releases.html), so I can use this package which has the same functionality as Sdraw.

**Comment by cbaggers** [comment]
@azzamsa For future projects please have a quick peek at http://blog.quicklisp.org/2015/01/getting-library-into-quicklisp.html & http://blog.quicklisp.org/2015/01/some-problems-when-adding-libraries-to.html

It's a few small talks but they make a world of difference :)

**Comment by guicho271828** [comment]
@xach , ISSUE_TEMPLATE.md #1103 should greatly reduce this type of work. Have a try?

**Comment by cbaggers** [comment]
If you use `quickproject` most of it is done for you. Again it's a tiny amount of effort, after you have done it a few times it will take at most 5 minutes.

**Comment by azzamsa** [comment]
@cbaggers You mean, it is better for me to package `sdraw` with the policy of `quicklisp`, so I can ask Qucklisp maintainer to consider to include that package in next quicklisp release ?

**Comment by aesyondu** [comment]
> For the second problem, I can ask the license to the author for you.
> 
> But I think [draw-cons-tree](https://github.com/cbaggers/draw-cons-tree) already included in [Quicklisp relase](https://www.quicklisp.org/beta/releases.html), so I can use this package which has the same functionality as Sdraw.

For beginners like me desperate to know how this person made draw-cons-tree work:
```lisp
CL-USER> (ql:quickload :draw-cons-tree)
CL-USER> (draw-cons-tree:draw-tree '(1 2 3))
```

Next step could be adding `(ql:quickload :draw-cons-tree)` to `.emacs.d/init.el`, or where the emacs init file is. Unfortunately this doesn't work and I don't know how to do that yet.

**Comment by phoe** [comment]
I don't think you want to add initialization code for Common Lisp into Emacs configuration files.

It's not an issue for Quicklisp discussion though; you might want to join `#lisp` on Freenode or the [Lisp Discord server](https://discord.gg/D987gaZ) for some beginner guidance for dealing with Common Lisp.
