### ISSUE TITLE
Please add org.xoanonos.gui.garnet

### ISSUE THREAD

**Issue by earl-ducaine** [quicklisp/quicklisp-projects#1412]
Fork of ancient CL GUI Toolkit, Garnet, updated for ASDF and cleanup up for Quicklisp.  

https://github.com/earl-ducaine/cl-garnet

Currently only runs on SBCL, but ECL is close to working as is ccl.  Still generates some warnings but (ql:quickload :org.xoanonos.gui.garnet :verbose t) compiles without interruption on SBCL.  This is my first quicklisp request (YAY!) So, I'm sure I'm missing something!

**Comment by quicklisp** [comment]
Sorry, if it is SBCL-only, it is not suitable for Quicklisp. Please reopen this issue when it works on other implementations,

**Comment by earl-ducaine** [comment]
Oops, my bad.  Didn't read the Quicklisp FAQ attentively enough to see that running multiple CLs is a requirement not just a 'suggestion'.  Updated the library to run on CCL.

**Comment by earl-ducaine** [comment]
Also, just checking.  by 

> Please reopen this issue when it works on other implementations,

Do you mean reopen this ticket? (I don't appear to have permission, but I might be missing something).  Or do you mean open a new one?

**Comment by quicklisp** [comment]
Does this require an X server running to build?

I get this: `DISPLAY environment variable is not set`

**Comment by earl-ducaine** [comment]
Yes, unfortunately it does.  It's a long standing issue with Garnet that I've been working to fix.  Garnet precompiles various aspects of the display environment to improve performance, of the runtime system.  

But, most of the techniques that it uses are either obsolete or not relevant any longer on modern systems from a performance perspective.  I've got a branch which resolves this issue that should be ready to promote shortly.

**Comment by earl-ducaine** [comment]
I've update the master branch with modifications that allow it to be compiled even if the running CL instance doesn't have access to a  running X11 server instance, e.g. I was able to compile it in a Docker container.

**Comment by quicklisp** [comment]
I can't build it on my SBCL - I get `The variable GEM::*DEFAULT-X-DISPLAY* is unbound.`
