### ISSUE TITLE
Please add cl-proj

### ISSUE THREAD

**Issue by vityok** [quicklisp/quicklisp-projects#1415]
Please add cl-proj, a CFFI wrapper for the Proj.4 geographic projections library.

Mercurial repository can be cloned from: https://bitbucket.org/vityok/cl-proj

It requires latest libproj to be installed on your system as it also provides wrappers for Geodesic functions that were added to the libproj library not so long ago.

This package has been removed from Quicklisp-projects list for the sin of being hosted on Sourceforge. But it was moved to Bitbucket and significantly updated since then.

**Comment by quicklisp** [comment]
It was removed because it no longer builds for me due to a missing geodesic.h header. I don't know where to get geodesic.h -- it's not in any debian package.

If you can tell me where to get the foreign library requirements, I can set up my build environment so it is available once more in Quicklisp.

**Comment by vityok** [comment]
Hi,

the `geodesic.h` file is installed along with the latest Proj.4 library distribution that must be downloaded and manually built/installed.

The libproj sources can be downloaed from: http://proj4.org/download.html

Meanwhile, is there a way to check if that specific header file is present and depending on it fine-tune the groverler to process or ignore specific functions? I'll be glad to introduce this check into the `cl-proj` if it is not too complex.

I think it would be nice for backwards compatibility with the mainstream Linux/BSD distributions.

Thanks

**Comment by quicklisp** [comment]
I don't know if there's a way to check for headers, sorry. That sounds like a good approach though.

I'll get that proj.4 library and see if that fixes the build.

**Comment by vityok** [comment]
Just realized that it might be possible to move geodesic code into a different ASDF system. Therefore users will have an option to use plain Proj.4 wrapper or, if they so desire, load an additional system with geodesic wrappers in it.

Please let me know what you think.

Thanks

**Comment by quicklisp** [comment]
From my perspective (aggregating the software, not using it), there is no real difference.
