### ISSUE TITLE
Please add cl-editdistance

### ISSUE THREAD

**Issue by phmarek** [quicklisp/quicklisp-projects#1417]
https://github.com/belambert/cl-editdistance

Thank you very much!

**Comment by quicklisp** [comment]
How does this differ from the existing levenshtein library?

**Comment by phmarek** [comment]
This one offers a fast mode (similar to `levenshtein`) and a slow one, where the differences can be returned as a sequence for further analysis; eg. `foo1` vs. `foo2` gives

```lisp
((:MATCH #\f #\f) (:MATCH #\o #\o) (:MATCH #\o #\o) (:SUBSTITUTION #\1 #\2))
```

Thanks a lot for the quick answer!
