### ISSUE TITLE
Please add trivial-argv

### ISSUE THREAD

**Issue by asciian** [quicklisp/quicklisp-projects#1423]
It's just parser for arguments.
https://github.com/asciian/trivial-argv
Thanks!

**Comment by asciian** [comment]
Canceled.

**Comment by fstamour** [comment]
why?

**Comment by asciian** [comment]
Because we already have unix-opts . I wanted to treat a list of arguments and didn’t know that unix-opts have a option to treat it, and I wanted to replace apply-argv. Now I think that Unix-opts is the best of parsers. 
If you know advantages, I’ll reopen this issue.
