### ISSUE TITLE
Pull Edi Weitz's libraries from Github instead of weitz.de

### ISSUE THREAD

**Issue by neil-lindquist** [quicklisp/quicklisp-projects#1424]
[weitz.de](weitz.de) no longer provides downloads of Edit Weitz's libraries, with a message to use the projects on https://github.com/edicl instead.

I created a fork using the github versions and can create a pull request for that:  https://github.com/neil-lindquist/quicklisp-projects

**Comment by xach** [comment]
I handled that by changing how I interpret ediware sources to use github. No other patch needed.
