### ISSUE TITLE
Please add clinenoise

### ISSUE THREAD

**Issue by jasom** [quicklisp/quicklisp-projects#1425]
https://github.com/jasom/clinenoise

I originally wrote it just to scratch my own itch, but apparently other people are using it despite it not being in quicklisp, so I figure I can make it easier to use

**Comment by vityok** [comment]
Hi @jasom could you please drop a sentence or two what this library is and what it does?

**Comment by jasom** [comment]
It's a rudimentary line-input library for unix terminals.  It can show a prompt, allows simple editing via the arrow keys, has simple tab-completion and manages the history of values entered

**Comment by vindarel** [comment]
Were you aware of [cl-readline](https://github.com/mrkkrp/cl-readline) ? Is clinenoise different ?

ps: I think Vityok meant to drop a line… in the readme ;) Examples also would be welcome.

**Comment by aarvid** [comment]
One possible reason: the license is different  (BSD-2 vs GPL3).

from the original [Linenoise](https://github.com/antirez/linenoise)
> A minimal, zero-config, BSD licensed, readline replacement used in Redis, MongoDB, and Android.

**Comment by fstamour** [comment]
Every time I've seen Linenoise used instead of gnu's readline it was because of the difference of license.
