### ISSUE TITLE
Please add sycamore

### ISSUE THREAD

**Issue by avodonosov** [quicklisp/quicklisp-projects#1431]
https://github.com/ndantam/sycamore

**Comment by fstamour** [comment]
> In the issue, please provide a brief description of what your project is for and where to fetch its sources.

From the `asd` file: "Purely Functional Trees, Etc."
From the readme: A fast, purely functional data structure library in Common Lisp.

Maybe you could update the `asd` file? :P

**Comment by xach** [comment]
I can't build - http://report.quicklisp.org/2018-01-26/failure-report/sycamore.html

**Comment by avodonosov** [comment]
Fixed: https://github.com/ndantam/sycamore/issues/1#issuecomment-365511384

**Comment by quicklisp** [comment]
Actually, there's another problem - it depends on cl-fuzz, but cl-fuzz doesn't have `:author` or `:license` metadata.

**Comment by ndantam** [comment]
Metadata added to cl-fuzz in https://github.com/ndantam/cl-fuzz/commit/acb14a22cc759af1f5d0a5c589b5a80e030fd4c1
