### ISSUE TITLE
Please add print-licenses

### ISSUE THREAD

**Issue by vindarel** [quicklisp/quicklisp-projects#1432]
This utility allows to print licenses used by the given project and its dependencies.

You can fetch its sources from

https://github.com/vindarel/print-licenses.git

Example:

~~~lisp
  (print-licenses 'fast-io)
  =>
  alexandria           | Public Domain / 0-clause MIT
  babel                | MIT
  cffi                 | MIT
  cffi-grovel          | MIT
  cffi-toolchain       | MIT
  fast-io              | NewBSD
  static-vectors       | MIT
  trivial-features     | MIT
  trivial-gray-streams | MIT
  uiop                 | Unspecified
~~~

It's a project put together from other people's utilities, full credit is given. MIT.

**Comment by xach** [comment]
This is a great idea, but the current build environment does not include quicklisp itself.

Is there any way to display this info from just ASDF operations?

**Comment by vindarel** [comment]
I don't know yet ! I'll answer when I can.

**Comment by koji-kojiro** [comment]
Can we use `#-ql` to avoid such problems?

**Comment by vindarel** [comment]
I just merged a PR by Ruricolist that should address this: https://github.com/vindarel/print-licenses/pull/6
