### ISSUE TITLE
Please add cl-grnm

### ISSUE THREAD

**Issue by ecp-rigetti** [quicklisp/quicklisp-projects#1433]
With permission from the author, we (Rigetti Computing) have re-hosted an implementation of Nelder-Mead, a differentiation-free numerical method for finding local minima of multivariate functions, at https://github.com/rigetticomputing/cl-grnm . It includes both classical Nelder-Mead as well as a "grid-restrained" variant that guarantees convergence. It's authored under the MIT license, a permissive use license.

We would really appreciate its inclusion into Quicklisp. :)

**Comment by xach** [comment]
Can you please add the :description and :license options to the system definition?

**Comment by ecp-rigetti** [comment]
Absolutely. I've now added these with a fresh push.
