### ISSUE TITLE
Please add slynk

### ISSUE THREAD

**Issue by anquegi** [quicklisp/quicklisp-projects#1435]
I would ask in order to add the library [slynk](https://github.com/joaotavora/sly)  slynk is written by [João Távora](https://github.com/joaotavora) and is part of the sly project. Sly as you write in[ your posts](http://lispblog.xach.com/post/165078221528/september-of-sly) is a slime but cooler, and Slynk is the Swank for sly. so I think it would be interesting to get easily this library using quicklisp and get this advantages in any place

**Comment by xach** [comment]
I am still looking into this.

**Comment by joaotavora** [comment]
I was going through SLY's issues and stumbled on this.  Is anything blocking this?

**Comment by Levenson** [comment]
+1 I also would like to have it.

**Comment by quicklisp** [comment]
@joaotavora Is it possible to change the "slynk/foo" systems in slynk.asd to explicitly depend on slynk? If someone were to try to load "slynk/util" directly, for example, it would not automatically load slynk first.

**Comment by joaotavora** [comment]
> @joaotavora Is it possible to change the "slynk/foo" systems in slynk.asd to explicitly depend on slynk? If someone were to try to load "slynk/util" directly, for example, it would not automatically load slynk first.

OK. I did this in https://github.com/joaotavora/sly/commit/c3d6f127005c4c416744d8950d616285ff746bf0.  AFAIK`slynk/util` was the only such `slynk/foo` system.
