### ISSUE TITLE
Help understanding quicklisp build failure

### ISSUE THREAD

**Issue by joaotavora** [quicklisp/quicklisp-projects#1437]
Apologies if this is not the correct bug tracker to ask this:

In http://report.quicklisp.org/2018-01-26/failure-report/hunchensocket.html, there is a note of a build failure for the `hunchentsocket-tests` ASDF system, which is a secondary system defined in `hunchensocket.asd` (the main system being `hunchensocket` itself).

Although the subsystem specifies `fiasco`, another quicklisp project and ASDF system, as a dependecy, the report hints that somehow it wasn't loaded. I can load hunchensocket-tests without any problem with quicklisp and SBCL 1.4.1. What is happening here?

**Comment by quicklisp** [comment]
I don't see the string "fiasco" in hunchensocket.asd at
https://github.com/joaotavora/hunchensocket/blob/master/hunchensocket.asd -
am I looking in the wrong place?

**Comment by joaotavora** [comment]
Oh, you're right! I was looking at these uncommited changes! :man_facepalming: 

```diff
diff --git a/hunchensocket.asd b/hunchensocket.asd
index 96d03d7..69569d7 100644
--- a/hunchensocket.asd
+++ b/hunchensocket.asd
@@ -18,9 +18,9 @@
    (:file "hunchensocket")))
 
 (asdf:defsystem :hunchensocket-tests
-    :description "Tests for Hunchensoket"
+  :description "Tests for Hunchensoket"
   :version #.(with-open-file (f "VERSION") (string (read f)))
-  :depends-on (:stefil
+  :depends-on (:fiasco
                :hunchensocket)
   :serial t
   :components
```

**Comment by joaotavora** [comment]
Should be fixed in the next dist.
