### ISSUE TITLE
Please add cl-darksky

### ISSUE THREAD

**Issue by 0xk175un3** [quicklisp/quicklisp-projects#1443]
https://github.com/0xk175un3/cl-darksky
Dark Sky (formerly forecast.io) weather API wrapper written in common lisp.

**Comment by quicklisp** [comment]
This no longer builds - there's a reference to a missing "util" component.

**Comment by quicklisp** [comment]
Any word on this?

**Comment by 0xk175un3** [comment]
Sorry for long reply. I remove this component and use 'alexandra' instead. Now there are 2 modules, and forget to remove it from a .asd file. Now it should work.

**Comment by quicklisp** [comment]
Still no luck - http://report.quicklisp.org/2018-03-07/failure-report/cl-darksky.html#cl-darksky shows there is a duplicate definition of FORECAST in one file.

**Comment by 0xk175un3** [comment]
Check plz, now it should be ok.

**Comment by 0xk175un3** [comment]
So?
