### ISSUE TITLE
Please add cl-selenium-webdriver

### ISSUE THREAD

**Issue by TatriX** [quicklisp/quicklisp-projects#1456]
https://github.com/TatriX/cl-selenium-webdriver is a binding library to the Selenium 2.0

**Comment by quicklisp** [comment]
The selenium.asd clashes with the existing selenium.asd from
https://github.com/html/cl-selenium

**Comment by TatriX** [comment]
Looks like `cl-selenium` is not maintained and basically unusable. It uses very old selenium api.

Is it possible to somehow retire it from the quicklisp as it's just a bad experience for a new users of the cl ecosystem?

**Comment by quicklisp** [comment]
Even if the old system is removed, I'd still prefer a different name for
the new system.

**Comment by TatriX** [comment]
`selenium` is the most obvious and easy for newcomers, but we'll try to find another one. Thanks!

**Comment by TatriX** [comment]
I renamed the project to `cl-selenium`.
