### ISSUE TITLE
Problem with cl-selenmium

### ISSUE THREAD

**Issue by anquegi** [quicklisp/quicklisp-projects#1465]
I thing that there is a problem with the cl-selenium system:

There are two systems 

the oldest that doesn't work

[OLD SELENIUM](https://github.com/html/cl-selenium)

and the newes that get shadoweds by the first:

[NEW SELENIUM](https://github.com/TatriX/cl-selenium-webdriver)

**Comment by quicklisp** [comment]
The old on is named "selenium", the new one is named "cl-selenium".
