### ISSUE TITLE
Please add cl-notebook

### ISSUE THREAD

**Issue by inaimathi** [quicklisp/quicklisp-projects#1474]
https://github.com/inaimathi/cl-notebook

**Comment by quicklisp** [comment]
This doesn't build because src/model.lisp references the QL package, which is not available in the test build environment.

**Comment by thephoeron** [comment]
@inaimathi for cl-notebook, it might make more sense to use Qlot for package-local, versioned library dependencies, right?

**Comment by inaimathi** [comment]
I think doing this right might require non-trivial changes. I'll close this for now and reopen it when I've fixed the issue.

**Comment by inaimathi** [comment]
I've made some changes; does this resolve the issue?
