### ISSUE TITLE
Please change which branch glsl-spec is pulled from

### ISSUE THREAD

**Issue by cbaggers** [quicklisp/quicklisp-projects#1479]
Currently [glsl-spec](https://github.com/cbaggers/glsl-spec) is pulled from master.  Please pull from the [release-quicklisp](https://github.com/cbaggers/glsl-spec/tree/release-quicklisp) branch instead.

https://github.com/cbaggers/glsl-spec/tree/release-quicklisp

An issue caught by the quicklisp rss issue feed brought me here. Thanks again for that :)

**Comment by quicklisp** [comment]
Closed in 3152a0d45175f8fd8dad7e57ab50ebae0c18a770 (though with an incorrect commit message).
