### ISSUE TITLE
Please upgrade to latest version of xmls

### ISSUE THREAD

**Issue by svillemot** [quicklisp/quicklisp-projects#1480]
The `xmls` project is at version 1.7 in QL, but version 3.0.2 is available.

See https://common-lisp.net/project/xmls/

It would be nice to upgrade.

Best,

N.B.: I'm not related to the author of the library.

**Comment by quicklisp** [comment]
The latest version actually breaks a number of projects, which is why it hasn't been updated sooner. The broken projects might be abandoned, though. I'll look into it further soon.

**Comment by svillemot** [comment]
Thanks for your feedback. I was just mentioning this in case it had been overlooked. No rush though.
