### ISSUE TITLE
Please add the cl-swagger-codegen library

### ISSUE THREAD

**Issue by incjung** [quicklisp/quicklisp-projects#1494]
Please add the cl-swagger-codegen library, which is available from https://github.com/incjung/cl-swagger-codegen

cl-swagger-codegen is a project which contains a template-driven engine to generate API client.

The homepage is https://github.com/incjung/cl-swagger-codegen

**Comment by fstamour** [comment]
there's a typo in the first URL: it's missing a `n` at the end.

**Comment by quicklisp** [comment]
This doesn't build because it references the QL package in package.lisp. If you need cl-mustache, add it to the system definition.

**Comment by incjung** [comment]
sorry, I updated/modified it. Please add cl-swagger library again.
