### ISSUE TITLE
Please add cl-arrowz

### ISSUE THREAD

**Issue by eschulte** [quicklisp/quicklisp-projects#1495]
This is a drop in replacement for cl-arrows (https://github.com/nightfly19/cl-arrows) which actually has a license and a maintainer.  The cl-arrows maintainer no longer maintains that library, and hasn't replied to email or issue requests for some months now.

https://github.com/eschulte/cl-arrowz.git

Thanks,
Eric

**Comment by mfiano** [comment]
You can also consider using `arrow-macros`: https://github.com/hipeta/arrow-macros

It is more complete, and doesn't suffer from the problems associated with cl-arrows.

**Comment by eschulte** [comment]
Ah, you're right.  I wasn't aware of the existence of the arrow-macros library.  I've just switched my local projects to use arrow-macros.  Thanks!

Given this I no longer request that cl-arrowz be added to quicklisp.
