### ISSUE TITLE
Please add cl-mecab

### ISSUE THREAD

**Issue by carrotflakes** [quicklisp/quicklisp-projects#1502]
Please add cl-mecab to quicklisp.

https://github.com/carrotflakes/cl-mecab

This is an interface of [MeCab](https://github.com/jordwest/mecab-docs-en) that is a morphological analyzer.
It is confirmed operation on ubuntu.

**Comment by quicklisp** [comment]
Please add a `:description` to the system definition.

**Comment by carrotflakes** [comment]
I added a description. Please make sure.
