### ISSUE TITLE
Please add massung's utilities

### ISSUE THREAD

**Issue by phoe** [quicklisp/quicklisp-projects#1521]
http://codeninja.blog/2018/lisp-code/

Some of them may need modification to make them work on SBCL.

All of them seem to need unit tests.

Should I make separate issues for each of them?

https://github.com/massung/future
https://github.com/massung/lazy :heavy_check_mark: 
https://github.com/massung/queue :heavy_check_mark: 
https://github.com/massung/heap :heavy_check_mark: 
https://github.com/massung/huffman :heavy_check_mark: 
https://github.com/massung/base64 :heavy_check_mark: 
https://github.com/massung/sha1 :heavy_check_mark: 
https://github.com/massung/parse :heavy_check_mark: 
https://github.com/massung/re
https://github.com/massung/lexer
https://github.com/massung/csv
https://github.com/massung/json
https://github.com/massung/date
https://github.com/massung/markup
https://github.com/massung/xml
https://github.com/massung/url
https://github.com/massung/html
https://github.com/massung/http
https://github.com/massung/rss
https://github.com/massung/targa :heavy_check_mark:

**Comment by quicklisp** [comment]
Pasting all repo URLs into this issue's description would help (adding them in a new comment wouldn't).

**Comment by phoe** [comment]
Done - thanks.

**Comment by quicklisp** [comment]
Some projects work, but many don't. 

The biggest issue is that massung's lexer.asd clashes with cl-lexer's lexer.asd, and massung's libraries that depend on massung's lexer don't build as a result. That includes markup, xml, html, and others.

Another issue is implicit dependencies. url has an implicit dependency on base64. json has an implicit dependency on re. csv has an implicit dependency on parse.

rss.asd clashes with cl-rss's rss.asd. future.asd clashes with clml's future.asd.

**Comment by quicklisp** [comment]
I've added what I can - the rest need some work.

**Comment by phoe** [comment]
Okay - I'll fork and PR the remaining ones.
