### ISSUE TITLE
Please add Petalisp

### ISSUE THREAD

**Issue by equwal** [quicklisp/quicklisp-projects#1537]
https://github.com/marcoheisig/Petalisp
AGPLv3 license.
Known to work on SBCL and Lispworks at least.
Parallelization library based on strided arrays.

**Comment by marcoheisig** [comment]
Petalisp is still under heavy development.  But if Zach doesn't mind that, I think we can also add it right now.

@equwal Thank you for your interest in my project.  Feel free to contact me if you have any ideas or suggestions.
