### ISSUE TITLE
Please add cl-collider 

### ISSUE THREAD

**Issue by byulparan** [quicklisp/quicklisp-projects#1538]
`cl-collider` is SuperCollider client for CommonLisp.
SuperCollider is synthesis / algorithm composition engine.
https://github.com/byulparan/cl-collider

`sc-extensions` is additional library  collection for cl-collider.
It include many musical functions and extensions.
https://github.com/byulparan/sc-extensions

**Comment by quicklisp** [comment]
I have a problem with sc-extensions - build log is here: http://report.quicklisp.org/2018-08-31/failure-report/sc-extensions.html#sc-extensions

**Comment by quicklisp** [comment]
Can you please submit sc-extensions separately when it is fixed?

**Comment by byulparan** [comment]
That's cl-collider's bug(not sc-extensions) to occur when  user not installed SuperCollider.
It fixed now. Can you please re-examine it. If It have problem yet, then I'll submit it next time. 
sorry and thank you!
