### ISSUE TITLE
Please fix trivial-ssh

### ISSUE THREAD

**Issue by Khong-Ten** [quicklisp/quicklisp-projects#1540]
This used to work:
(ql:quickload :trivial-ssh)

The project contains two asd files:
trivial-ssh-libssh2.asd
trivial-ssh.asd

I don't know why quicklisp is not detecting one of them, trivial-ssh.asd.
`* (ql:quickload :trivial-ssh)

debugger invoked on a QUICKLISP-CLIENT:SYSTEM-NOT-FOUND in thread
#<THREAD "main thread" RUNNING {10005505B3}>:
  System "trivial-ssh" not found

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [CONTINUE] Try again
  1: [ABORT   ] Give up on "trivial-ssh"
  2:            Exit debugger, returning to top level.

((LABELS QUICKLISP-CLIENT::RECURSE :IN QUICKLISP-CLIENT::COMPUTE-LOAD-STRATEGY) "trivial-ssh")
   source: (CERROR "Try again" 'SYSTEM-NOT-FOUND :NAME NAME)
0] 
`

**Comment by quicklisp** [comment]
It isn't in Quicklisp because of the lack of response to https://github.com/eudoxia0/trivial-ssh/issues/5

**Comment by Khong-Ten** [comment]
Ok thanks.
