### ISSUE TITLE
Please add arrows

### ISSUE THREAD

**Issue by Harleqin** [quicklisp/quicklisp-projects#1544]
Please add "arrows" from https://gitlab.com/Harleqin/arrows.

This is a drop-in replacement for "cl-arrows".  The latter has no licensing information and several attempts of contacting the owner of the repository failed.

**Comment by vindarel** [comment]
+1, the owner is unreachable (https://github.com/nightfly19/cl-arrows/pull/6).

note: another drop-in replacement candidate is https://github.com/eschulte/cl-arrowz

**Comment by Harleqin** [comment]
@xach was there some specific reason that this did not get included in the august update?  Did the conversation maybe leave the false impression that something was unclear?

**Comment by quicklisp** [comment]
@Harleqin I ran out of time, sorry. It will be in the next update.
