### ISSUE TITLE
Please add cl-dotenv

### ISSUE THREAD

**Issue by ollelauribostrom** [quicklisp/quicklisp-projects#1559]
https://github.com/ollelauribostrom/cl-dotenv

Tiny utility library for loading .env files & getting/setting environment variables.

**Comment by PuercoPop** [comment]
There is also an undeclared dependency to uiop

**Comment by ollelauribostrom** [comment]
@quicklisp `cl-dotenv` has now been fixed/rewritten with the help of @PuercoPop
