### ISSUE TITLE
Help packaging SLIME/SWANK for Guix

### ISSUE THREAD

**Issue by Ambrevar** [quicklisp/quicklisp-projects#1561]
Please redirect me if this is the wrong place to ask.

I've been trying to package some Common Lisp packages for [Guix](https://guix.info/) which depend on SLIME (e.g. `mgl-pax`) but it seems that the SLIME `.asd` does not work properly to build SWANK in order to be used as dependency for other packages.

I've opened an issue on SLIME's repository: https://github.com/slime/slime/issues/457.

I've figured that it works with Quicklisp, so maybe the Quicklisp team has some insight about how to package SWANK "manually".  I know nothing about the Quicklisp internals so I'd be curious about how Quicklisp processes SLIME / SWANK.

Thanks in advance!

**Comment by fstamour** [comment]
I think a better place to ask is on [lisp's irc](https://www.cliki.net/IRC) channel, [lisp's discord](https://www.reddit.com/r/lisp/comments/63pox8/lisp_discord_server/) channel, [nixos's irc](https://nixos.org/nixos/community.html) channel or [guix's irc](https://www.gnu.org/software/guix/help/) channel. If you have more specific questions, you can ask them on StackOverflow. And there's also a bunch of subreddit pages that could apply: [guix subreddit](https://www.reddit.com/r/GUIX/), [lisp](https://www.reddit.com/r/lisp/), etc.

Have you looked at how they dealt with lisp/quicklisp/packages in NixOS?

[/pkgs/development/lisp-modules/Readme.txt](https://github.com/NixOS/nixpkgs/blob/5048b0d1f9e908665a01c35f49b2d9816128e089/pkgs/development/lisp-modules/README.txt)

[/pkgs/development/lisp-modules/quicklisp-to-nix.nix](https://github.com/NixOS/nixpkgs/blob/5048b0d1f9e908665a01c35f49b2d9816128e089/pkgs/development/lisp-modules/quicklisp-to-nix.nix)

[/pkgs/development/lisp-modules/quicklisp-to-nix-output/swank.nix](
https://github.com/NixOS/nixpkgs/blob/5048b0d1f9e908665a01c35f49b2d9816128e089/pkgs/development/lisp-modules/quicklisp-to-nix-output/swank.nix)

**Comment by Ambrevar** [comment]
Thank you very much, @fstamour !

Actually Andy Patterson found the issue just now: https://issues.guix.info/issue/32770.
So it turns out that the .asd file contains some definitions that must be preserved into the compiled bundle.

The links you've sent about Nix are most insightful: note the
``` lisp
  asdFilesToKeep = ["swank.asd"];
```
line in `swank.nix` which I guess is the Nix approach to preserve those definitions.  I should have looked into the Nix approach before.

Problem solved!
