### ISSUE TITLE
Change cxml repository to sharplispers/cxml

### ISSUE THREAD

**Issue by scymtym** [quicklisp/quicklisp-projects#1566]
Please use the master branch of the https://github.com/sharplispers/cxml repository for the cxml project. 

It is actively maintained and has already received several improvements and important bug fixes.

CC: @slyrus @lichtblau @ruricolist

**Comment by ruricolist** [comment]
This should probably apply to all the repositories in the CXML project:

https://github.com/sharplispers/closure-common
https://github.com/sharplispers/xpath
https://github.com/sharplispers/cxml-stp

**Comment by quicklisp** [comment]
This change has broken a number of things. See http://report.quicklisp.org/2018-10-01/failure-report.html for a list of them.

**Comment by slyrus** [comment]
You need this new repo as well at the same time: https://github.com/sharplispers/cxml-stp/

**Comment by quicklisp** [comment]
@slyrus That's what I'm using.

**Comment by slyrus** [comment]
Ok, can you see if my latest commit to cxml-stp fixes things?
