### ISSUE TITLE
regular-type-expression  

### ISSUE THREAD

**Issue by jimka2001** [quicklisp/quicklisp-projects#1571]
Please add regular-type-expression  

The repo is https://gitlab.lrde.epita.fr/jnewton/regular-type-expression.git
The quicklisp branch is named export-to-quicklisp

**Comment by quicklisp** [comment]
Lots of failures when trying to build this. A build log here: http://report.quicklisp.org/2018-10-02/failure-report/regular-type-expression.html

**Comment by quicklisp** [comment]
For the sb-posix errors, expressing a dependency on sb-posix in the system file (conditionalized on sbcl) will help clear it up.

**Comment by jimka2001** [comment]
Hi Zach,

A month or so ago, I made some libraries available to quicklisp.  There
were originally compilation issues, which I sorted out.  I don't see any
issues in the newest failure report
http://report.quicklisp.org/2018-11-05/failure-report.html

The issue has been marked as resolved:
https://github.com/quicklisp/quicklisp-projects/issues/1571

However, I don't see the libraries listed in the releases list
https://www.quicklisp.org/beta/releases.html

And according to the main quicklisp page, the libraries haven't been
updated since
July 11, 2018.

Can you tell me when (or if) these libraries will become available?

Jim

**Comment by quicklisp** [comment]
They're available now. I need to update the pages. If you updated the dist
(via (ql:update-dist "quicklisp")) and quickload a system (via e.g.
(ql:quickload "rte")), they are loadable.

Zach

**Comment by jimka2001** [comment]
Ah, perhaps there's a problem because I already have the code (including
the asdf systems) in my home directory.  Asdf loads them from there.
So It looks like (ql:quickload :regular-type-expression) does nothing.
Which ql function should I use to download the regular-type-expression code
even if asdf finds the systems elsewhere?

**Comment by jimka2001** [comment]
Oh, does (ql:update-dist "quicklisp")  upload the list of which libraries
are available?   I though it only updated the quicklisp implementation
code.

**Comment by quicklisp** [comment]
update-dist updates the libraries. ql:update-client updates the
implementation code.

There's no way to have quicklisp-provided systems override
locally-available systems.

**Comment by quicklisp** [comment]
Well, you can really rearrange things, but it's a bit lower-level than you
usually want. It requires messing with
asdf:*system-definition-search-functions*.
