### ISSUE TITLE
Please update CFFI

### ISSUE THREAD

**Issue by phoe** [quicklisp/quicklisp-projects#1572]
The CFFI version on Quicklisp is over a year old.

See https://bugs.launchpad.net/cffi/+bug/1796570 for the related CFFI ticket. I have asked the CFFI maintainers to make a new release.

**Comment by phoe** [comment]
The CFFI ticket is now in progress.

**Comment by quicklisp** [comment]
I will continue to use the latest release of CFFI until the CFFI maintainers request otherwise. If you'd like more frequent updates, please help and encourage the CFFI maintainers to make it happen.

**Comment by phoe** [comment]
CFFI 0.20.0 is now out.

https://bugs.launchpad.net/cffi/+bug/1796570

Should this ticket be reopened, or should I make a new one?

**Comment by quicklisp** [comment]
It will be updated automatically.

Zach
