### ISSUE TITLE
Please update Gendl

### ISSUE THREAD

**Issue by genworks** [quicklisp/quicklisp-projects#1576]
The current devo branch (default branch) from

  https://gitlab.common-lisp.net/gendl/gendl

should be building cleanly against latest zacl (with pending merge request merged) from:

  https://gitlab.common-lisp.net/zbeane/zacl

and newly introduced zaserve from #1578.

**Comment by quicklisp** [comment]
There are many system failures, here's a build log: http://report.quicklisp.org/2018-10-23/failure-report/gendl.html

**Comment by quicklisp** [comment]
All the failures look related, though. The sb-posix one is easy to fix with a conditional dependency in the system definition. Don't know about the `:CURRENT-ID` thing though.

**Comment by gendl** [comment]
Sorry, I forgot to run the build with `(ql:quickload :gendl :verbose t)`.

I just pushed a 7861a04f which hopefully will yield a clean build for you (it does for me).

**Comment by genworks** [comment]
Geysr issue should be fixed now.

**Comment by genworks** [comment]
Other issues should be fixed now. Test build on vanilla sbcl succeeds.
