### ISSUE TITLE
Please add Zaserve

### ISSUE THREAD

**Issue by gendl** [quicklisp/quicklisp-projects#1578]
Please add [zaserve](https://github.com/gendl/aserve)  -- master branch. 

This depends on [zacl](https://gitlab.common-lisp.net/zbeane/zacl/tree/master) -- master branch --being updated with the pending [merge request](https://gitlab.common-lisp.net/zbeane/zacl/merge_requests/1) and updated in Quicklisp as well.

**Comment by quicklisp** [comment]
Please add `:author`, `:license`, and `:description` info to the system file.
