### ISSUE TITLE
Please add pjlink

### ISSUE THREAD

**Issue by Zulu-Inuoe** [quicklisp/quicklisp-projects#1579]
https://github.com/Zulu-Inuoe/pjlink

PJLink is a CL client library for communicating with PJLink compliant devices to get/set various parameters over a TCP/IP interface.

Currently one of the dependencies [ip-interfaces](https://github.com/elliottslaughter/ip-interfaces) causes warnings on compile and runtime (on Windows) but I'm working with the author of that library to fix those.

Tested on SBCL x86/x86-64 on Windows so far. On a followup version I'll be adding unit tests that are able to somehow mock socket connections and threading.

**Comment by quicklisp** [comment]
Please add a real `:description` to the system file.

**Comment by Zulu-Inuoe** [comment]
Done, sorry, and thank you.
