### ISSUE TITLE
Please add with-shadowed-bindings

### ISSUE THREAD

**Issue by Hexstream** [quicklisp/quicklisp-projects#1585]
with-shadowed-bindings establishes a new lexical context within which specified bindings are explicitly shadowed, making it clear that they are not referenced within, thereby reducing cognitive load.

Project's home: https://www.hexstreamsoft.com/libraries/with-shadowed-bindings/

GitHub: https://github.com/Hexstream/with-shadowed-bindings

Quicklisp should pull from the tarball: https://tarballs.hexstreamsoft.com/libraries/latest/with-shadowed-bindings_latest.tar.gz

**Comment by Hexstream** [comment]
`with-shadowed-bindings` seems to have been mistakenly added as `shadowed-bindings`.

https://github.com/quicklisp/quicklisp-projects/commit/fe274fcd3ac7de1ec43c0a78207ef1222fbb54fe

**Comment by quicklisp** [comment]
Sorry about that. I will fix it in the next release.
