### ISSUE TITLE
Please add literate-lisp

### ISSUE THREAD

**Issue by jingtaozf** [quicklisp/quicklisp-projects#1587]
literate-lisp is a literate programming tool to write common lisp codes in org mode.

https://github.com/jingtaozf/literate-lisp

Thanks.

**Comment by jingtaozf** [comment]
I still can't install literate-lisp via latest quicklisp,is it anything wrong?

Thanks.

**Comment by quicklisp** [comment]
It will be in the January update. Sorry for the confusion.
