### ISSUE TITLE
please add trivial-sockets

### ISSUE THREAD

**Issue by avodonosov** [quicklisp/quicklisp-projects#1590]
http://ftp.linux.org.uk/pub/lisp/cclan/trivial-sockets.tar.gz

**Comment by avodonosov** [comment]
A place it is used in: the old cl+ssl test suite: https://github.com/cl-plus-ssl/cl-plus-ssl/blob/master/test.lisp

**Comment by quicklisp** [comment]
There are a couple of problems:

- I don't want to add more http sources

- No `:description` in the system file

**Comment by avodonosov** [comment]
Well, that's a historically formed situation.

**Comment by avodonosov** [comment]
There is a darcs mirror at https://common-lisp.net/project/clbuild/mirror/trivial-sockets/, but it's synced from the same http source (as described here https://common-lisp.net/project/clbuild/mirror/). 

Or sharplispers: @arbv, @binghe, @dkachmaski, @khirbat, @luisimbo, @nikodemus, @skymtym, @sionesku, @slyrus, @xach, would you take trivial-socket under your umbrella?

**Comment by avodonosov** [comment]
> Quicklisp news — December 2018 Quicklisp dist update now available
    New projects:
    - ...
    - trivial-sockets — trivial-sockets — MIT
    - ...

Thank you.

**Comment by binghe** [comment]
> There is a darcs mirror at https://common-lisp.net/project/clbuild/mirror/trivial-sockets/, but it's synced from the same http source (as described here https://common-lisp.net/project/clbuild/mirror/).
> 
> Or sharplispers: @arbv, @binghe, @dkochmanski, @khirbat, @luismbo, @nikodemus, @scymtym, @sionescu, @slyrus, @xach, would you take trivial-socket under your umbrella?

I'd like to take over under "usocket" project on GitHub [1].  The darcs repository doesn't contain any historical commit logs, so I directly copied all code into Git without using any Darcs-to-git migration tools. The code base is quite simple, I have confidences to fix potential bugs reported by users. 

I also found some patches on Cliki [2], I'll see if they're safe to be merged.

I must apologize that, I'm not quite active these years as a Lisper (currently I'm mainly focusing on Standard ML and theorem provers).   If anyone wants to join "usocket" maintenance team, feel free contact me for write access.

[1] https://github.com/usocket/trivial-sockets
[2] https://www.cliki.net/trivial-sockets
