### ISSUE TITLE
Wilbur package

### ISSUE THREAD

**Issue by arademaker** [quicklisp/quicklisp-projects#1593]
The repo https://github.com/lisp/de.setf.wilbur/ seems to be abandoned. How to update Quicklisp? Should we fork it and ask for updating the 'official' repo? Does anyone is taking care of that?

**Comment by quicklisp** [comment]
I'd check with the author by email before forking. If they don't want to maintain it any more, it could be added to sharplispers or any other suitable place for continued maintenance.

**Comment by quicklisp** [comment]
If you do take over the project, please open a new issue with the new location and I will make the update.
