### ISSUE TITLE
New Parenscript release

### ISSUE THREAD

**Issue by vsedach** [quicklisp/quicklisp-projects#1597]
2.7 Released on December 1:

https://common-lisp.net/project/parenscript/release/parenscript-2.7.tgz

https://common-lisp.net/project/parenscript/release/parenscript-2.7.tgz.sig

**Comment by quicklisp** [comment]
This breaks a number of weblocks-related systems: http://report.quicklisp.org/2018-12-02/failure-report.html

Do you know if they're easy to fix?

**Comment by phoe** [comment]
From what I see, this is a deprecation warning that gets promoted to an error during compilation.
```
; caught WARNING:
;   Parenscript symbol WINDOW.OPENER.DOCUMENT.WIDTH contains one or more dot operators.
;   This compound naming convention is deprecated and will be removed!
;   Use GETPROP, @, or CHAIN instead.
```

**Comment by vsedach** [comment]
I will take a look.

**Comment by vsedach** [comment]
What Common Lisp implementation is this?

**Comment by quicklisp** [comment]
SBCL.

**Comment by quicklisp** [comment]
So if this is a deprecated thing, but hasn't been removed, I think it should be a style-warning or something less than a full warning to give people some time to transition.

**Comment by vsedach** [comment]
Indeed, it should have been a style-warning.

Here is the update:

https://common-lisp.net/project/parenscript/release/parenscript-2.7.1.tgz
https://common-lisp.net/project/parenscript/release/parenscript-2.7.1.tgz.sig
