### ISSUE TITLE
Please add package pipe-operator

### ISSUE THREAD

**Issue by sheepduke** [quicklisp/quicklisp-projects#1599]
Package `pipe-operator` provides an operator to chain a series of functions.

The home page is https://github.com/sheepduke/pipe-operator

**Comment by phoe** [comment]
Curious question - doesn't https://gitlab.com/Harleqin/arrows provide the same functionality? It seems that your library implements a threading macro.

**Comment by sheepduke** [comment]
The functionality is duplicated with https://gitlab.com/Harleqin/arrows
