### ISSUE TITLE
Please add rpcq

### ISSUE THREAD

**Issue by ecp-rigetti** [quicklisp/quicklisp-projects#1602]
Hello! We've developed a cross-platform RPC library that we'd like to be available as part of QuickLisp. Here's a link to the git repository: https://github.com/rigetti/rpcq/ .

Please let me know if there are missing pieces we need to put in to make it acceptable. Thanks very much!

**Comment by ecp-rigetti** [comment]
(`pzmq` is the culprit demanding those things, and it's already part of QuickLisp.)

**Comment by xach** [comment]
If I can install the prerequisites I add them.
