### ISSUE TITLE
Please update April

### ISSUE THREAD

**Issue by phantomics** [quicklisp/quicklisp-projects#1605]
Could you update to the latest version of [my April APL compiler](https://github.com/phantomics/april)? I've improved it considerably since you added it in July. Tested on SBCL, ABCL and LispWorks.

**Comment by handicraftsman** [comment]
Just use github's releases (git's tags map to them). QuickLisp server should pull new releases every month.

**Comment by phantomics** [comment]
Will do, thanks for letting me know.

**Comment by quicklisp** [comment]
April is updated automatically for each release. It pulls from the master branch every day to test and build. The latest dist update has a version from December 10.
