### ISSUE TITLE
Please add nodgui

### ISSUE THREAD

**Issue by cage2** [quicklisp/quicklisp-projects#1606]
Hello!

Please can you add nodgui?

https://notabug.org/cage/nodgui

This library us TCL/TK to render a GUI for lisp program and, yes, is a fork of LTK :)

Bye!
C.

**Comment by quicklisp** [comment]
This doesn't build for me any more - what's the best way to report problems?

**Comment by cage2** [comment]
Hello!

Probably the problem originated from the fact that i forgot to push some changes that was sitting on my computer for a couple of weeks. :( The latest commits should, in my opinion, fix this issue. 

Sorry for the inconvenience!
C.

**Comment by quicklisp** [comment]
Thanks, but how should I report problems in the future?

**Comment by cage2** [comment]
On Fri, Jun 21, 2019 at 04:43:11AM -0700, Zach Beane wrote:

Hi!

> Thanks, but how should I report problems in the future?

There is an issue tracker on notabug.org:

https://notabug.org/cage/nodgui/issues

To post an issue a registration is required though, i hope this is not
too much an hassle.

Bye!
C.
