### ISSUE TITLE
Please add sucle

### ISSUE THREAD

**Issue by pupcraft** [quicklisp/quicklisp-projects#1611]
This is an game engine/interactive app/graphics library for games, editors, terminal emulators

Author: terminal625
Source: [https://github.com/terminal625/sucle](https://github.com/terminal625/sucle)
License: MIT

**Comment by quicklisp** [comment]
`doubly-linked-list.asd` clashes with the existing `doubly-linked-list` project in Quicklisp.

**Comment by quicklisp** [comment]
So a lot of the components of this project don't build. See a report here: http://report.quicklisp.org/2019-01-03/failure-report/sucle.html

* uncommon-lisp
* text-subsystem
* sandbox
* reverse-array-array
* reverse-array-array-example
* bundler-quicklisp
* broad

**Comment by terminal625** [comment]
This [commit](https://github.com/terminal625/sucle/commit/ecd6c101aca281a3e02cf4cd9997edcf586ad674) should fix the build error. It lets each ASDF component be loaded individually.

Sorry I was not aware that each ASDF component had to built individually. I should have read [http://blog.quicklisp.org/2015/01/some-problems-when-adding-libraries-to.html](http://blog.quicklisp.org/2015/01/some-problems-when-adding-libraries-to.html) more closely.

Thanks,

terminal625
