### ISSUE TITLE
Please add eclecticse.iso-8601-date

### ISSUE THREAD

**Issue by EclecticSoftwareEngineer** [quicklisp/quicklisp-projects#1615]
The code is licensed LLGPL and is available to git clone at: 
    https://gitlab.com/DataLinkDroid/iso-8601-date.git

**Comment by phoe** [comment]
I get a 404.

![zrzut ekranu z 2018-12-23 10-46-32](https://user-images.githubusercontent.com/15045546/50382464-0599a480-06a0-11e9-9c6a-c4a5a3d46e0b.png)

**Comment by phoe** [comment]
I no longer get a 404.
