### ISSUE TITLE
GNU CLISP install quicklisp failed

### ISSUE THREAD

**Issue by c4dr01d** [quicklisp/quicklisp-projects#1617]
I use curl download the quicklisp.lisp, and write a lisp file to call the installer to install quicklisp. after download asdf.lisp, CLISP raise:
Continuable Error
DEFPACKAGE QL-CLISP: There is no symbol EXT::DELETE-DIR .

**Comment by c4dr01d** [comment]
But I use sbcl to install quicklisp is normal, no exception raised

**Comment by phoe** [comment]
This issue should be moved to https://github.com/quicklisp/quicklisp-client

**Comment by quicklisp** [comment]
This should be fixed with the latest quicklisp-client update.
