### ISSUE TITLE
Please add Lem

### ISSUE THREAD

**Issue by gmasching** [quicklisp/quicklisp-projects#1624]
[https://github.com/cxxxr/lem](https://github.com/cxxxr/lem)
License: MIT

Lem is an editor for Common Lispers

**Comment by quicklisp** [comment]
This doesn't build for me because it refers to Quicklisp.

**Comment by phoe** [comment]
https://github.com/cxxxr/lem/pull/400 should fix compile-time dependencies on Quicklisp and therefore make it buildable.

**Comment by quicklisp** [comment]
I get a bunch of  errors. Log is here: http://report.quicklisp.org/2019-06-25/failure-report/lem.html

The foreign library errors are not a big deal, but the other errors are.

**Comment by gmasching** [comment]
https://github.com/cxxxr/lem/issues/359#issuecomment-574792878
