### ISSUE TITLE
Please add cl-proj

### ISSUE THREAD

**Issue by ayild** [quicklisp/quicklisp-projects#1630]
Please add cl-proj, a CFFI wrapper for the Proj.4 geographic projections library.

https://github.com/ayild/cl-proj

This repository got imported from https://bitbucket.org/vityok/cl-proj. I added CI (continuous integration) support via Travis CI for this clone that can be found at https://travis-ci.org/ayild/cl-proj. It runs smoke tests after building the library and its dependencies.

Regarding not-found geodesic.h file issue (https://github.com/quicklisp/quicklisp-projects/issues/1415), it looks like this issue occurs on older debian or ubuntu versions. But for those distros, I fixed the issue by manually building proj library using its latest release that comes with the header file. Please find https://github.com/ayild/cl-proj/blob/master/.travis.yml for the instructions that might help fix the issue on your end!

**Comment by quicklisp** [comment]
What happened to this repo?
