### ISSUE TITLE
Please add cl-ruby

### ISSUE THREAD

**Issue by Ninjacop** [quicklisp/quicklisp-projects#1631]
This is an FFI between Ruby and Common Lisp, where Ruby scripts can be used in CL, and Ruby variables, constants and functions can be declared and called in CL.

Documentation - [https://github.com/Ninjacop/cl-ruby/tree/master/doc](https://github.com/Ninjacop/cl-ruby/tree/master/doc)
Repository - [https://github.com/Ninjacop/cl-ruby](https://github.com/Ninjacop/cl-ruby)

**Comment by quicklisp** [comment]
How can I get libruby.so on Debian 9?

**Comment by Ninjacop** [comment]
Hello! Sorry for the late reply -- it seems that you can just do `sudo apt-get install ruby` in a terminal, or download from the Debian package site [here](https://packages.debian.org/search?keywords=libruby).

**Comment by quicklisp** [comment]
That installs libruby-2.3.so but cl-ruby looks for "libruby.so". I can see
no package that provides bare libruby.so.

**Comment by quicklisp** [comment]
Feel free to ping me if you find a way to install libruby.so or if there's some other way forward.
