### ISSUE TITLE
Please add trivial-monitored-thread

### ISSUE THREAD

**Issue by ediethelm** [quicklisp/quicklisp-projects#1636]
A Common Lisp library offering a way of spawning threads and being informed when any of them crash and die.

https://gitlab.com/ediethelm/trivial-monitored-thread

Thanks!

**Comment by quicklisp** [comment]
Please add description info to the system definition.

**Comment by ediethelm** [comment]
Description was added.

**Comment by ediethelm** [comment]
> Please add description info to the system definition.

Description was added.
