### ISSUE TITLE
Please add quicksys

### ISSUE THREAD

**Issue by ryukinix** [quicklisp/quicklisp-projects#1654]
`quicksys` it's a simple tool to track quicklisp distributions overworld.

https://github.com/commonlispbr/quicksys

Let's say we want [trivial-gamekit] which is provided by the
org.borodust.bodge dist, we can acomplish that with quicksys using
this:

```
(ql:quickload 'quicksys)
(qs:quickload 'trivial-gamekit :dist 'bodge)
```
The resolution method to :bodge is a handcrafted assoc list with
plists as values. The objective of the repository is being a catalog
of quicklisp's dists to help installing external systems.

[trivial-gamekit]: https://github.com/borodust/trivial-gamekit

**Comment by quicklisp** [comment]
I'm working out some issues related to adding this. In the Quicklisp dist build environment, Quicklisp itself is not available. But I am working on a way to make it available for projects like this.

**Comment by ryukinix** [comment]
Thank you @quicklisp!

**Comment by quicklisp** [comment]
I am going to close this for now. When I work out the system for projects that require quicklisp, I will write about it on blog.quicklisp.org.

**Comment by ryukinix** [comment]
Any news for projects like that?

**Comment by Hexstream** [comment]
Great question, but I am assuming the top priority is fixing the several months long release cadence.
