### ISSUE TITLE
Please add skeleton-creator

### ISSUE THREAD

**Issue by noloop** [quicklisp/quicklisp-projects#1656]
Create projects from a skeleton directory and automatic license your files.

https://github.com/noloop/skeleton-creator

**Comment by phoe** [comment]
Curious question: how does this differ from quickproject?

**Comment by noloop** [comment]
I did not know the quickproject, I read about it now, I'm not sure how it works, because I did not try it, but I believe it is different, the skeleton-creator is based on a configuration directory, where there is a configuration file skeleton-creator.conf file, you can add the tags you want, not just author and license. In addition to being interactive with the user. Everything is customized: licenses, warnings and markings as well as the skeleton directory.
