### ISSUE TITLE
hu.dwim.util has no :AUTHOR

### ISSUE THREAD

**Issue by phoe** [quicklisp/quicklisp-projects#1671]
According to the Quicklisp's guidelines:

> The system definition(s) for the project should include :DESCRIPTION, :AUTHOR, and :LICENSE options.

The systems of `hu.dwim.util` do not have the `:AUTHOR` field in their ASD file:

http://dwim.hu/live/hu.dwim.util/hu.dwim.util.asd

**Comment by mfiano** [comment]
The bigger issue as to why it shouldn't be included in Quicklisp, is it taints an SBCL image because it does:

```lisp
(sb-ext::without-package-locks
  (defun sb-impl::line-length (&optional (stream *standard-output*))
    (declare (ignore stream))
    160))
```

**Comment by phoe** [comment]
`The bigger issue as to why it shouldn't be included in Quicklisp`

Anyone can have their code included in Quicklisp, since the repository is not curated.

Also, for correctness, the above code is from `hu.dwim.asdf`, not `hu.dwim.util`.

**Comment by phoe** [comment]
Somewhat-related SBCL ticket: https://bugs.launchpad.net/sbcl/+bug/501075

**Comment by attila-lendvai** [comment]
sorry for the mess! it's removed now and should be gone in the next ql update.

**Comment by attila-lendvai** [comment]
as of the original issue: once `hu.dwim.util` is loaded, it should get a default value into its `author` and `licence` slots inherited from its superclass `hu.dwim.system`.

**Comment by phoe** [comment]
Oh - is that what the `:class "hu.dwim.asdf:hu.dwim.system"` line does? I need to read up on that part of ASDF one day. Thanks!
