### ISSUE TITLE
Please add digikar-utilities

### ISSUE THREAD

**Issue by digikar99** [quicklisp/quicklisp-projects#1676]
The project and the README is available on [github](https://github.com/digikar99/cl-digikar-utilities).

**Comment by quicklisp** [comment]
Please add a `:description` to the system file.

**Comment by digikar99** [comment]
Added.

**Comment by digikar99** [comment]
Is it possible to remove this library? I realize from [discussion over reddit](https://www.reddit.com/r/Common_Lisp/comments/bmxa6i/digikarutilities_code_and_ideology_review_request/) that this is not a particularly useful (or adhering to conventions) library, and I think it'd be better for the community to not have such a library. 

Also, what is the preferred way to update links for libraries on quicklisp? Or to update library versions? Say, can we instruct to have the library picked up from the "latest" release?

**Comment by quicklisp** [comment]
I can remove it.

The quicklisp dist building software checks for updates daily and automatically.

**Comment by digikar99** [comment]
So, if I change the default branch on Github, does that mean quicklisp will pickup the updates without any changes?

Also, does it pick up from the "Release" section, or from the default branch?

**Comment by digikar99** [comment]
Please remove this library.
