### ISSUE TITLE
Link to new s-xml-rpc repo

### ISSUE THREAD

**Issue by Ambrevar** [quicklisp/quicklisp-projects#1679]
New maintained version:

https://source.atlas.engineer/view/repository/s-xml-rpc

Fixes error handling and boolean support.
I've asked the author, he authorized me to take over maintenance.

I'm planning to add support for Unix sockets and/or usocket.

[Next browser](https://next.atlas.engineer/) depends on this.

Thanks!

**Comment by quicklisp** [comment]
That link times out for me. Does it work for you?

**Comment by Ambrevar** [comment]
Yes it does.  It's the home page.
The git repository is https://source.atlas.engineer/public/s-xml-rpc.
@jmercouris: any idea what it would be blocked for Zach?

**Comment by phoe** [comment]
Works for me from Poland.

**Comment by jmercouris** [comment]
Works for me now, just tested it. Also able to clone from it via HTTPS without issue. There is no geoblocking within the server config, maybe just got unlucky. 

@quicklisp are you able to execute: `git clone https://source.atlas.engineer/public/s-xml-rpc`?
