### ISSUE TITLE
Please update array-operations

### ISSUE THREAD

**Issue by bendudson** [quicklisp/quicklisp-projects#1683]
The original author (@tpapp) is no longer maintaining this library, but a maintained and extended version is here:
https://github.com/bendudson/array-operations

The original library (https://github.com/tpapp/array-operations) now points to this maintained fork.

Includes tests, run on Travis with SBCL and CCL. CLISP currently fails, probably due to a problem with the unit testing framework, clunit.

**Comment by tpapp** [comment]
Just to confirm: I am fine with this, @bendudson: thanks for taking over.

**Comment by quicklisp** [comment]
Using this repo breaks a bunch of stuff: http://report.quicklisp.org/2019-05-20/failure-report/cl-num-utils.html#cl-num-utils and http://report.quicklisp.org/2019-05-20/failure-report/lla.html#lla for example. Do you know how it could be fixed?

**Comment by bendudson** [comment]
Thanks, I'll look into it and try fixing it. I had thought we kept backward compatibility, but clearly not.

**Comment by bendudson** [comment]
ok, should be fixed now. Both LLA and cl-num-utils load now. A symbol was removed, replaced with a different function, and I've now added it back. Thanks!

**Comment by quicklisp** [comment]
New failure: http://report.quicklisp.org/2019-05-20/failure-report/lla.html#lla

When testing, please use asdf directly or `(ql:quickload ... :verbose t)` - that will make sure warnings trigger failures as they should.

**Comment by bendudson** [comment]
Sorry I missed that. I've added back the `let+` dependency. Now LLA loads with `:verbose t` without warnings. One more try? Thanks very much.

**Comment by bendudson** [comment]
Thanks, and sorry for the breakages.
