### ISSUE TITLE
add youtube

### ISSUE THREAD

**Issue by mihaiolteanu** [quicklisp/quicklisp-projects#1695]
Please consider adding `youtube`, a library for playing songs from youtube given a youtube url or a search string. Uses youtube-dl and the mpv player.

Author: Mihai Olteanu
Repository (with README/documentation): [https://github.com/mihaiolteanu/youtube](https://github.com/mihaiolteanu/youtube)

**Comment by quicklisp** [comment]
http://report.quicklisp.org/2019-06-20/failure-report/youtube.html

**Comment by quicklisp** [comment]
Failure log here: http://report.quicklisp.org/2019-06-20/failure-report/youtube.html

**Comment by mihaiolteanu** [comment]
Fixed.
