### ISSUE TITLE
add lastfm

### ISSUE THREAD

**Issue by mihaiolteanu** [quicklisp/quicklisp-projects#1696]
Please consider adding the lastfm library, an interface to the last.fm API. I know there is cl-lastfm. That wasn't useful for me since it's not complete, does not include authentication and I couldn't manage to get it off the ground and do some useful work with it. 

Author: Mihai Olteanu
Repository (with README/documentation): https://github.com/mihaiolteanu/lastfm

**Comment by quicklisp** [comment]
I get a build failure: http://report.quicklisp.org/2019-06-11/failure-report/lastfm.html

**Comment by mihaiolteanu** [comment]
`Couldn't load #P"~/.config/.lastfm.lisp": file does not exist`

Yes, this is the user supplied config file needed by the last.fm API (api-key, shared-secred and username) as specified in the [install instructions](https://github.com/mihaiolteanu/lastfm#step-three)

**Comment by quicklisp** [comment]
Ok. If it doesn't build without extra manual setup work, I can't add it to Quicklisp.

Would it be possible to have it build without this file but signal a runtime error if it isn't configured?

**Comment by mihaiolteanu** [comment]
Would creating the config file, as a template for the user to fill in the API details, if the file does not exist, be reasonable? Of course, if the user then doesn't fill in its details, the calls to last.fm would just be rubbish and that would just return, well, nothing, if my math is right.

**Comment by quicklisp** [comment]
If I were making it, I think I would make calls that reference an absent
config file signal a continuable error that indicates what must be done,
rather than filling in the file with unusable initial values.

But as far as Quicklisp is concerned, any solution that does not require
pre-build configuration is fine.

**Comment by mihaiolteanu** [comment]
There is no point in any of the exported interfaces if that config file is not available. So I went with the first option, creating a template file if one doesn't exist. 

Also found a small bug or two in the process :)

**Comment by quicklisp** [comment]
It builds now, but there are some problems lurking in the future.

First, `load-rc-file` might be called when `*package*` does not relate to the lastfm package, so the `config` symbol will not be `lastfm::config`, and calling it will be an error.

Second, the "~" pathname syntax is popular but not standard. A portable solution would use `user-homedir-pathname`.

Third, creating the config file will fail if `~/.config` does not exist.

**Comment by quicklisp** [comment]
See also https://github.com/eudoxia0/trivial-open-browser for more cross-platform browser opening.

**Comment by mihaiolteanu** [comment]
First point. Ok. Is there any standard way to create/load user config files? I've searched and searched but in the end I've used my own little contraption.

On the second point, yes, I've changed it to use the `user-homedir-pathname`

Third. Ok. Moved/renamed to `~/.lastfmrc`

Fourth. Nice. Using the trivial-open-browser now.

Fifth. I'm still calling the `md5sum` with run-program. I've tried the `:md5` package, but I'm not getting the results I'm getting with the `md5sum` and last.fm doesn't seem to like it either. Maybe I don't know how to use it. Any thoughts on this one?

**Comment by phoe** [comment]
Don't clutter the user's homedir with dotfiles - see my [reddit comment](https://www.reddit.com/r/linux/comments/amxtji/dotfiles_are_everywhere_weve_lost_control_of_our/efq24je/) on the issue. Use `(uiop:xdg-config-pathnames)` instead - it will give you a platform-specific configuration directory on each supported system.

**Comment by mihaiolteanu** [comment]
Ok, point taken. I see there are a bunch of similar `uiop` functions for this, like `(uiop:xdg-config-pathnames)` and `(uiop:xdg-config-pathname)` and `(uiop:xdg-config-home)`.
