### ISSUE TITLE
Please add fiveam-asdf

### ISSUE THREAD

**Issue by rpgoldman** [quicklisp/quicklisp-projects#1697]
This system lets the user automatically link FiveAM tests into the ASDF `TEST-OP`, for use with `TEST-SYSTEM`.

License is Lisp LGPL.

GitHub repo is here: https://github.com/rpgoldman/fiveam-asdf

I have added a `release` branch in the hopes that will make things easier.

Thanks!

**Comment by quicklisp** [comment]
Can you please add a `:description` to the system definition?

**Comment by rpgoldman** [comment]
OK, done!

**Comment by rpgoldman** [comment]
I just tested and was able to install the system using `ql:quickload` so I'm closing this.

Thanks, Xach!
