### ISSUE TITLE
Adding cl-ipfs-api2

### ISSUE THREAD

**Issue by JadedCtrl** [quicklisp/quicklisp-projects#1698]
Please consider adding cl-ipfs-api2, a set of bindings for IPFS'es HTTP API.

It's available at https://git.eunichx.us/cl-ipfs-api2.git , and can be cloned with [this URL](https://git.eunichx.us/c/cl-ipfs-api2).  It's also mirrored on Github [here](https://github.com/JadedCtrl/cl-ipfs-api2).

**Comment by quicklisp** [comment]
This does not build on SBCL.

**Comment by quicklisp** [comment]
Failure log here: http://report.quicklisp.org/2019-06-20/failure-report/cl-ipfs-api2.html

**Comment by nodefunallowed** [comment]
@JadedCtrl from a quick skim, I think you forgot to paste in the option alist here:

```lisp
(defun filestore-dups ()
  "List blocks that're both in the filestore and standard block storage.
  /ipns/docs.ipfs.io/reference/api/http/#api-v0-filestore-dups"
  (bind-api-alist (ipfs-call "filestore/dups") >>> `(,(if cid (list "arg" cid)) <<<))
```

**Comment by JadedCtrl** [comment]
@nodefunallowed Ah, thanks. :)
@quicklisp I just pushed a commit that _should_ address the failure.
