### ISSUE TITLE
Please add linear-programming

### ISSUE THREAD

**Issue by neil-lindquist** [quicklisp/quicklisp-projects#1703]
This is a solver for [linear programming problems](https://en.wikipedia.org/wiki/Linear_programming), written in Common Lisp.

Repository: https://github.com/neil-lindquist/linear-programming/

**Comment by guicho271828** [comment]
Not a bridge to the existing MILP solver? (you know, it is virtually impossible to beat the commercial MILP solvers like Gurobi and CPLEX)

**Comment by neil-lindquist** [comment]
Well, I originally started the code because I didn't want to fight to get the GNU library for CL-GLPK working on Windows.  So, pure CL was a design goal.
For small problems, it's plenty fast. (In my original application, it parses and solves about 4100 trivial problems in about .2 seconds).  It wouldn't be hard to refactor it to have a configurable backend with the same end API, if there's interest in solving large problems.

**Comment by guicho271828** [comment]
Sorry perhaps I sounded rude, but I do some ORs myself so couldn't help but.
I at least suggest making the API not a macro. `make-linear-problem` should really be a function that takes a list instead of being a macro. If this is for optimization, you should then use the compiler macro.

As a side note, you could look up SMT (Satisfiable Modulo Theory) and its API.

**Comment by guicho271828** [comment]
The scalability issue could be noted somewhere in the README, but I agree that the agileness is a virtue, so it can also be noted in the README. It only clarifies the purpose of the library and benefit users.

**Comment by neil-lindquist** [comment]
I appreciate the feedback.

The function `parse-linear-problem` is a function version of `make-linear-problem`.  `make-linear-problem` is really just a convenience wrapper that lets you skip quoting the forms (It probably could actually be removed, since the `with-solved-problem` macro is more convenient for that anyways).

I'll adds notes about `parse-linear-problem` and scalability in the README.
