### ISSUE TITLE
Please add trivial-coverage

### ISSUE THREAD

**Issue by ediethelm** [quicklisp/quicklisp-projects#1708]
A simple Common Lisp library to print out the code coverage collected by sb-cover. As such it only supports SBCL.

[https://gitlab.com/ediethelm/trivial-coverage](https://gitlab.com/ediethelm/trivial-coverage)

Thanks!

**Comment by quicklisp** [comment]
It is my policy not to add projects that work only on one implementation, sorry.

**Comment by Hexstream** [comment]
@ediethelm You could easily add your project to [Ultralisp](https://ultralisp.org/), an alternative Quicklisp dist with even more liberal policies and instant updates.
