### ISSUE TITLE
please add cardiogram

### ISSUE THREAD

**Issue by shapesncats** [quicklisp/quicklisp-projects#1713]
Please add Cardiogram. A unit testing framework with test combination dependencies and introspection.

https://gitlab.com/a.aguilar/cardiogram

**Comment by quicklisp** [comment]
Why should someone use this instead of one of the many existing systems?

**Comment by phoe** [comment]
Related: all the frameworks available at https://cliki.net/Test%20Framework

**Comment by shapesncats** [comment]
I believe Cardiogram's kit allows for a different, freer, wilder style of writing unit tests.

Cardiogram is able to build tests suites hopefully eliminating such mental burdens as  "How am I going to order all of this that I need to test?"  or  "I made a new feature that needs to be tested in the middle of all of this!" by simply telling lisp to "test this before that, now this after that, but don't test that if this other thing fails....".

What other packages may call test suites, cardiogram calls combinations. These try to emulate Common Lisp's method combinations, so one can very intuitively tell a REPL to test something before, around or after something else. This concept also somewhat applies to a test's dependencies, one can define dependencies to a test when defining it or even after. Tests in Cardiogram are funcallable objects, this makes them very easy to explore using their slots accessors which are exported symbols. So one can define a test and edit every aspect of it after the fact.

Also, like many other test frameworks it offers a way to define one's own report format and test predicates (valuations), as well as simple but useful wraps around `unwind-protect` to fix the environment. Though these features were added mainly so one doesn't miss a feature from another suite, they follow the philosophy of making changing code as simple as posible.

Lastly, Cardiogram's own code is very simple, a feature I think will make it easier to read, understand, extend and rewrite.

**Comment by guicho271828** [comment]
If the unit test requires so much dependency, is it a *unit* test? sounds like an integration test...

**Comment by shapesncats** [comment]
Yeah. I suppose somewhere along the way the capabilities of this thing grew but, out of ignorance or absent mindedness, the name I had for them didn't.

A concrete example of such a test would be when one would like to test the correctness of an API endpoint's response after it's been proven that one can send a request, but only if either one gets  a response or there's a response already stored for testing.
