### ISSUE TITLE
please add orizuru-orm

### ISSUE THREAD

**Issue by cage2** [quicklisp/quicklisp-projects#1717]
Hello!

please can you considering adding orizuru-orm? It is an ORM for postgreSQL derived from crane¹.

This library lose the chance to use multiple database as backend but gained a better migration support, i think.

Thank you!
Bye!
C.

¹ https://github.com/eudoxia0/crane/

**Comment by quicklisp** [comment]
Where can I find orizuru-orm?

**Comment by cage2** [comment]
On Mon, Aug 12, 2019 at 09:39:30AM -0700, Zach Beane wrote:
> Where can I find orizuru-orm?

Oh, i am sorry! i forgot the link!! :((

https://notabug.org/cage/orizuru-orm

C.
