### ISSUE TITLE
Please ACUTE-TERMINAL-CONTROL

### ISSUE THREAD

**Issue by emanrdesu** [quicklisp/quicklisp-projects#1726]
http://verisimilitudes.net/acute-terminal-control.tgz
This package exports miscellaneous functions for control of terminal devices.
Depends on CL-ECMA-48

**Comment by emanrdesu** [comment]
tgz does not unpack to current dir

**Comment by quicklisp** [comment]
Failure log here: http://report.quicklisp.org/2019-11-20/failure-report/acute-terminal-control.html
