### ISSUE TITLE
Please add horse-html

### ISSUE THREAD

**Issue by ralt** [quicklisp/quicklisp-projects#1728]
horse-html is a ParenScript extension to generate HTML inside your ParenScript code. This typically replaces your usage of `PS:WHO-PS-HTML`.

The main difference is that instead of generating strings, horse-html will generate parenscript code creating DOM elements. This is a stark difference because with ps:who-ps-html, you need to wait until the elements are rendered in the DOM before adding event handlers on them.

Gitlab repository with code, documentation, and a TODO app example: https://gitlab.com/ralt/horse-html

Thanks!

**Comment by quicklisp** [comment]
I get a failure when building: http://report.quicklisp.org/2019-09-26/failure-report/horse-html.html#horse-html

**Comment by ralt** [comment]
@quicklisp oof, sorry about that, I forgot to remove debug code. It should be good now.
