### ISSUE TITLE
add cl-libiio

### ISSUE THREAD

**Issue by mihaiolteanu** [quicklisp/quicklisp-projects#1748]
CFFI bindings for Analog Device's [libiio ](https://wiki.analog.com/resources/tools-software/linux-software/libiio_internals).

Author: Mihai Olteanu
Repo: https://github.com/mihaiolteanu/cl-libiio

Thank you,
Mihai

**Comment by quicklisp** [comment]
Failure log here: http://report.quicklisp.org/2019-10-14/failure-report/cl-libiio.html

**Comment by mihaiolteanu** [comment]
Fixed.

**Comment by mihaiolteanu** [comment]
There's still the issue of not being able to load the package if libiio.so is not installed,

> Unable to load foreign library (LIBIIO).
>   Error opening shared object "/usr/lib/libiio.so.0.18":
>   /usr/lib/libiio.so.0.18: cannot open shared object file: No such file or directory.

If, in the case of .rc files, I could create them if they didn't exist and avoid any possible errors on the user's side, I am not seeing the same solution working in case of missing .so files. Or are there any standard approaches for these kinds of errors?

**Comment by quicklisp** [comment]
There isn't a standard approach other than to instruct the user to install the prerequisite foreign library first. That might be a .so, a .dylib, or a .dll, on many different platforms, and I don't see an easy way to make it automatic.

**Comment by quicklisp** [comment]
Also, it's not great to encode a detailed path for a library like that - it's often better to use a short name and let the dynamic linker translate it in a suitable way for the user's system.

**Comment by mihaiolteanu** [comment]
Agree. Fixed as well. Fixed/updated some other parts of the library and now I'm having some 

`note: deleting unreachable code`

from a captured variable in macro calls. The macro does expand as I'm expecting it to and the function behaves like I'm expecting it to, as well. I understand that these notes are not actually errors or not even warnings, but it still bugs me.

Thanks for your support.

**Comment by phoe** [comment]
As for the `note: deleting unreachable code`, you can manually check which forms emit these notes. Once you do, macroexpand them, and evaluate them again; SBCL will give you better location for the unreachable code blocks, which in turn should help you with diagnosing where exactly unreachable code is generate.

**Comment by mihaiolteanu** [comment]
Nice! Compiling the macroexpansion itself led to a better note indeed.
I found how to fix it, too. 

Thank you.
