### ISSUE TITLE
Please add cacau

### ISSUE THREAD

**Issue by noloop** [quicklisp/quicklisp-projects#1752]
Test Runner in Common Lisp.

Other test runner???!

Read the README of the cacau and see the diferences. I struggled to document it well in two languages. I hope cacau will also be useful to others besides me.

https://github.com/noloop/cacau

**Comment by quicklisp** [comment]
Failure log here: http://report.quicklisp.org/2019-11-16/failure-report/cacau.html

**Comment by noloop** [comment]
Strange:

```
(defun arglist (fn)
  "Return the signature of the function."
  #+allegro (excl:arglist fn)
  #+clisp (sys::arglist fn)
  #+(or cmu scl)
  (let ((f (coerce fn 'function)))
    (typecase f
      (STANDARD-GENERIC-FUNCTION (pcl:generic-function-lambda-list f))
      (EVAL:INTERPRETED-FUNCTION (eval:interpreted-function-arglist f))
      (FUNCTION (values (read-from-string (kernel:%function-arglist f))))))
  #+cormanlisp (ccl:function-lambda-list
                (typecase fn (symbol (fdefinition fn)) (t fn)))
  #+gcl (let ((fn (etypecase fn
                    (symbol fn)
                    (function (si:compiled-function-name fn)))))
          (get fn 'si:debug))
  #+lispworks (lw:function-lambda-list fn)
  #+lucid (lcl:arglist fn)
  #+sbcl (sb-introspect:function-lambda-list fn)
  #-(or allegro clisp cmu cormanlisp gcl lispworks lucid sbcl scl)
  (error 'not-implemented :proc (list 'arglist fn)))
```
I thought every SBCL already makes this function available, I will provide a change to not need this "arglist" function comming soon.

**Comment by noloop** [comment]
@quicklisp Okay, arglist is no more a problem. I refactored not to need it. Now it must be working.

**Comment by phoe** [comment]
> I thought every SBCL already makes this function available

@noloop `sb-introspect` is a contrib. You must either `require` it or [depend on it](https://github.com/sbcl/sbcl/blob/master/contrib/sb-introspect/sb-introspect.asd) in your ASD file for it to be loaded.

**Comment by noloop** [comment]
@phoe thanks, but I already refactored it, this function was unnecessary anyway, I was about to refactor and not use it at all.
