### ISSUE TITLE
Please add with-user-abort

### ISSUE THREAD

**Issue by compufox** [quicklisp/quicklisp-projects#1754]
Hi! Could you please add https://github.com/compufox/with-user-abort to Quicklisp?

It's a package that provides a portable way to handle user-interrupts.

Thanks!

(edit: changed my username, updated repo link)

**Comment by Plisp** [comment]
For those writing terminal applications already employing foreign calls, another way to catch C-c is to mask out BRKINT in the `termios` struct, allowing you to read C-c normally.
