### ISSUE TITLE
plain-odbc repository update

### ISSUE THREAD

**Issue by elliottjohnson** [quicklisp/quicklisp-projects#1755]
Plain-odbc has a new maintainer.  See https://github.com/quicklisp/quicklisp-projects/issues/84

**Comment by quicklisp** [comment]
The project needs a `:description`, `:license`, and `:author` in the system file. It's missing at least `:description`.

**Comment by elliottjohnson** [comment]
Zach,

I apologize about not responding sooner.  I do not have write access to this library, so the best I could do is try to infer what the current maintainer wants and create a pull request.  I hope that this ticket leads to something.

Best,
Elliott
