### ISSUE TITLE
Please add jingoh and its dependencies.

### ISSUE THREAD

**Issue by hyotang666** [quicklisp/quicklisp-projects#1759]
[jingoh](https://github.com/hyotang666/jingoh)
DSL to notate specification, rather than test framework. 

[resignal-bind](https://github.com/hyotang666/resignal-bind)
Tiny signal capturing facility for common lisp.
Useful for better error handling and better error messages.

[millet](https://github.com/hyotang666/millet)
Wrapper for implementation dependent tiny utilities. 

[matrix-case](https://github.com/hyotang666/matrix-case)
Control flow macros which writing nested CASE easily. 

[check-bnf](https://github.com/hyotang666/check-bnf)
macro arguments checker for common lisp.

[structure-ext](https://github.com/hyotang666/structure-ext)
Tiny structure extensions for common lisp

[core-reader](https://github.com/hyotang666/core-reader)
Utilities for stream oriented reader. Useful to implement reader macros.

[read-as-string](https://github.com/hyotang666/read-as-string)
Reading S-Expression string from stream. Useful to static analyze lisp codes.

[null-package](https://github.com/hyotang666/null-package)
Safe and robust S-Expression reader. Useful to read from unfaithful stream/socket. 

Jingoh includes add-on systems.
These are the dependencies for it.

[prompt-for](https://github.com/hyotang666/prompt-for)
Type safe user input. 

To run test for null-package, additional dependencies.

[trestrul](https://github.com/hyotang666/trestrul)
Tiny utilities for TREe-STRUctured-List. 

[bnf](https://github.com/hyotang666/bnf)
BNF example generator. Useful to test parser.

Dependencies above are listed as :serial t, except jingoh itself.

As known issue, included add-on system jingoh.generator depends on quikclisp.

Thanks.

**Comment by quicklisp** [comment]
That code is hard to read due to the unconventional formatting. Would you consider formatting it like other Common Lisp code?

**Comment by quicklisp** [comment]
Sorry this did not get into the latest release. It will be added in December.

**Comment by hyotang666** [comment]
Now every codes are reFormatted.
Please check it.

**Comment by phoe** [comment]
I still see a bit of unformatted code in READMEs, such as https://github.com/hyotang666/resignal-bind/blob/master/README.md - the Lisp files seem reformatted though.

**Comment by hyotang666** [comment]
Ooops I forgot to fix it. Thank you.
Now fixed.

**Comment by quicklisp** [comment]
Failures:

* prompt-for has implicit dependency on sb-posix, log here http://report.quicklisp.org/2020-05-30/failure-report/prompt-for.html#prompt-for

**Comment by hyotang666** [comment]
Thank you. Fixed.
