### ISSUE TITLE
Please add reader

### ISSUE THREAD

**Issue by digikar99** [quicklisp/quicklisp-projects#1761]
[Github repo](https://github.com/digikar99/reader)

**Comment by digikar99** [comment]
Also please remove [cl-digikar-utilities](https://github.com/digikar99/cl-digikar-utilities) if it has not been removed already - just a reminder from [here](https://github.com/quicklisp/quicklisp-projects/issues/1676#issuecomment-545900038).

**Comment by quicklisp** [comment]
Failure log here: http://report.quicklisp.org/2019-12-14/failure-report/reader.html
