### ISSUE TITLE
CLX-TRUETYPE disappeared

### ISSUE THREAD

**Issue by phoe** [quicklisp/quicklisp-projects#1774]
The repository at https://github.com/filonenko-mikhail/clx-truetype gives me HTTP 404.

I've mailed @filonenko-mikhail about it.

**Comment by PuercoPop** [comment]
It has been missing for at least a couple of months now. The forks are still there in case someone wants to 'adopt' it. ej. https://github.com/l04m33/clx-truetype

**Comment by phoe** [comment]
Got a response:

> Hi,
Sorry for long time answer. It seems that I removed repo in some "garbage collection" process.
I think the most appropriate is to use this fork.
https://github.com/JMC-design/truetype-clx

**Comment by quicklisp** [comment]
That project doesn't have system file metadata like :author.

**Comment by phoe** [comment]
https://github.com/JMC-design/truetype-clx/issues/1
