### ISSUE TITLE
Please add cl-tui

### ISSUE THREAD

**Issue by naryl** [quicklisp/quicklisp-projects#1777]
It's a high-level library for making Text User Interfaces with ncurses (binding used is cl-charms).

https://github.com/naryl/cl-tui/

**Comment by naryl** [comment]
Oh, there's a problem. It needs a patch to cl-charms (a few functions from ncurses were missing). I submitted a PR but its developer seems to be unresponsive. What should I do?

**Comment by phoe** [comment]
The repository at https://github.com/HiTECNOLOGYs/cl-charms seems inactive, just like its owner.

1. Perhaps it would be worth it to fork it over to sharplispers instead?
2. If not, It seems that @stylewarning has push access to that repo - one could perhaps ask him for support.

**Comment by naryl** [comment]
cl-charms now has a low-level and a high-level component. I'm ok with maintaining the low-level one since that's what cl-tui uses. The high-level one wasn't even there 6 years ago when I started cl-tui.

**Comment by phoe** [comment]
If these two components are separable (and it seems they are), perhaps it would be preferable to separate them as ASDF systems (unless they already are)? This way you could have your own repo that only contains one of the two, and have this single low-level part uploaded to Quicklisp for `cl-tui` to depend on.

**Comment by naryl** [comment]
Low-level: https://github.com/naryl/cl-charms-ll
High-level and examples: https://github.com/naryl/cl-charms
cl-charms
I only updated the README on the first one. I can transfer the second one to sharplispers.

**Comment by phoe** [comment]
> I can transfer the second one to sharplispers.

I guess that sharplispers would prefer to maintain both packages in case some breakage occurs that requires changes in the low-level part.

@quicklisp This request also requires `cl-charms` to be fetched from the new repository and `cl-charms-ll` to be added. Some breakage may occur as a part of this change.

**Comment by stylewarning** [comment]
Hello, I do have push access to `cl-charms`. I can help with that.

**Comment by stylewarning** [comment]
@phoe @naryl I don't see a PR by either of you regarding a change to CL-CHARMS. Does one exist or is this much ado about nothing?

**Comment by phoe** [comment]
https://github.com/HiTECNOLOGYs/cl-charms/pull/54

**Comment by stylewarning** [comment]
@phoe The PR has been open for 5 days and the author closed it today. Does the author want it merged or not? Why was it closed?

**Comment by phoe** [comment]
@stylewarning If I understand this thread correctly, then @naryl went with the way of forking cl-charms, modifying their local fork, and working further to split it into two layers. So modifying the original might no longer be required.

**Comment by stylewarning** [comment]
@phoe Sounds somewhat uncollaborative.

**Comment by phoe** [comment]
@stylewarning The blame for this could probably be placed on me - I suggested this way forward in https://github.com/quicklisp/quicklisp-projects/issues/1777#issuecomment-572588169 under the assumption that the repository was as dead as the original owner's GitHub timeline.

**Comment by stylewarning** [comment]
Anyway, whatever the way forward, I'm happy to review and merge PRs. CL-CHARMS has been useful to me and I'd love for it to be further improved!

**Comment by naryl** [comment]
@stylewarning Greetings! I'm sorry, I've been too quick with the decision too. I'll make the PR again in a few minutes.

**Comment by naryl** [comment]
HiTECNOLOGYs/cl-charms#55

**Comment by quicklisp** [comment]
Failure log here: http://report.quicklisp.org/2020-01-11/failure-report/cl-tui.html

**Comment by naryl** [comment]
It's because the PR above is not accepted yet.

**Comment by naryl** [comment]
Should be good now, with cl-charms's master.
