### ISSUE TITLE
Please add cl-zyre and ratmath

### ISSUE THREAD

**Issue by jesseoff** [quicklisp/quicklisp-projects#1784]
I've written 2 new Lisp packages I'd like to request quicklisp inclusion of:

1. https://github.com/jesseoff/cl-zyre - "Lisp binding for the Zyre service discovery and network messaging library"
2. https://github.com/jesseoff/ratmath - "Utilities for rational approximations and interval arithmetic"

**Comment by quicklisp** [comment]
Failure log here: http://report.quicklisp.org/2020-01-24/failure-report/cl-zyre.html

**Comment by phoe** [comment]
Seems like a foreign library must be built from source for this to work.

https://github.com/zeromq/zyre#building-on-linux

**Comment by jesseoff** [comment]
There is a prebuilt package for Zyre for macOS on home-brew:

`brew install zyre`
 
I'm not sure why the Linux distro's haven't picked this project up yet.

**Comment by jesseoff** [comment]
I've pushed some changes to git that fix the missing :author in the .asd and also should quiet a couple warnings, but nothing can change the need for the C library.
