### ISSUE TITLE
Please add minilem

### ISSUE THREAD

**Issue by gregcman** [quicklisp/quicklisp-projects#1787]
**Description**: Minimal version of lem, emacs-like editor.  A minimal self-modifying Common Lisp editor.
**License**: MIT
**Author**: cxxxr 
**Contributors**: snmsts, fukamachi, gos-k, Hamayama, jessymilare, t-cool, jessymilare, t-cool, stacksmith, t-sin, nz-tcoder, myaosato, svetlyak40wt, kenoss, picospuch, koji-kojiro, asood123, KeenS, gmasching, g000001, talenbartlett, masatoi, i-makinori, agmm, Hexstream, FemtoEmacs, Fedreg

https://github.com/gmasching/minilem

**Comment by Hexstream** [comment]
It's "Hexstream", and I only contributed one 1-line commit...

**Comment by gmasching** [comment]
Everyone who takes part in the process of creating a project, whether or not their code remains in the end, is a contributor.
