### ISSUE TITLE
Please add s-dot

### ISSUE THREAD

**Issue by jingtaozf** [quicklisp/quicklisp-projects#1791]
s-graphviz is a s-expression presentation of AT&T GraphViz DOT language, to draw graph visualization in Common Lisp.
https://github.com/jingtaozf/s-graphviz

Thanks.

**Comment by quicklisp** [comment]
How does this relate to http://martin-loetzsch.de/S-DOT/ ?

**Comment by jingtaozf** [comment]
This is a S-expression presentation of AT&T GraphViz. The original idea is from http://www.martin-loetzsch.de/S-DOT, but with a full compatiblity of original DOT syntax by following DOT lang definition.

**Comment by quicklisp** [comment]
Please use a different name to avoid confusion with the original project.

**Comment by jingtaozf** [comment]
I have changed the package name from s-dot to s-graphviz.

s-graphviz is a s-expression presentation of AT&T GraphViz DOT language, to draw graph visualization in Common Lisp.
https://github.com/jingtaozf/s-graphviz

Thanks.
