### ISSUE TITLE
Please add Lispcord

### ISSUE THREAD

**Issue by naryl** [quicklisp/quicklisp-projects#1793]
https://github.com/lispcord/lispcord Implementation of Discord's web and Gateway APIs. Somewhat more full than cl-harmony.

**Comment by quicklisp** [comment]
Failure log here: http://report.quicklisp.org/2020-02-06/failure-report/lispcord.html

**Comment by naryl** [comment]
How did you do it? There's actually an error but SBCL never complained for me.

Fixed.

**Comment by phoe** [comment]
Curious question: why do you shadow `CL:INLINE`? I haven't seen it used anywhere in your code except for where I would expect `CL:INLINE` to be used.

**Comment by naryl** [comment]
I didn't do it, and that's exactly why I didn't fix it properly when CCL complained. But it is used here: https://github.com/lispcord/lispcord/blob/master/src/classes/embed.lisp#L144

**Comment by Hexstream** [comment]
For what it's worth, I like to use names like "%inline" for slot names and
some other internal stuff.

**Comment by naryl** [comment]
It's an API wrapper and `inline` is what the official docs have.
