### ISSUE TITLE
Please add Magic (ed)

### ISSUE THREAD

**Issue by alxnorden** [quicklisp/quicklisp-projects#1795]
Editing facility for Common Lisp REPL

Magic (ed) is a tiny editing facility for Common Lisp, where you can directly load, edit, manipulate and evaluate file or file content from REPL, such as (ed "file-to-edit.lisp").

Url: https://github.com/sanel/magic-ed
License:MIT License. 
Author:  Sanel Zukan

**Comment by quicklisp** [comment]
Failure log here: http://report.quicklisp.org/2020-02-06/failure-report/magic-ed.html

**Comment by alxnorden** [comment]
Apologies, the .asd file has been updated and  now contains information as per the instructions. It has also been tested with (ql:quickload "magic-ed" :verbose t).

 :DESCRIPTION, :AUTHOR, and :LICENSE options
:name "magic-ed"
  :version "0.2"
  :author "Sanel Zukan. https://github.com/sanel/magic-ed/"
  :licence "MIT"
  :description "Edit your code from REPL."
