### ISSUE TITLE
Please add rs-colors

### ISSUE THREAD

**Issue by ralph-schleicher** [quicklisp/quicklisp-projects#1797]
Please add the rs-colors library available from
https://github.com/ralph-schleicher/rs-colors.git

The rs-colors library provides a color data type for Common Lisp.
The home page is https://github.com/ralph-schleicher/rs-colors.

**Comment by quicklisp** [comment]
Failure log here: http://report.quicklisp.org/2020-02-11/failure-report/rs-colors.html

**Comment by ralph-schleicher** [comment]
Fixed.
