### ISSUE TITLE
Please add fakenil

### ISSUE THREAD

**Issue by Hexstream** [quicklisp/quicklisp-projects#1805]
fakenil provides a canonical stand-in for NIL for contexts where NIL means "no value".

Project's home: https://www.hexstreamsoft.com/libraries/fakenil/

GitHub: https://github.com/Hexstream/fakenil

Quicklisp should pull from the tarball: https://tarballs.hexstreamsoft.com/libraries/latest/fakenil_latest.tar.gz

**Comment by equwal** [comment]
Is this an attempt at satire?

**Comment by Hexstream** [comment]
> Is this an attempt at satire?

No. I've come to believe that extreme modularity is a necessary ingredient to great software engineering. See [my libraries](https://www.hexstreamsoft.com/libraries/) for explorations of this concept.

> Why are there five tests

Why not? I had initially removed the unit tests directory from [my usual template](https://github.com/Hexstream/hexstream-project-template), but then I could not just `(asdf:test-system "fakenil")` like I can do for all my other projects, which was extremely annoying. Instead of just adding an empty unit tests template, I thought I might as well [write some tests](https://github.com/Hexstream/fakenil/blob/master/tests/tests.lisp), since it's cost-free.

**Comment by equwal** [comment]
Okay, message taken.

**Comment by Hexstream** [comment]
Those who may still be puzzled about the existence of this library may find further rationale [here](https://github.com/Hexstream/fakenil/issues/2#issuecomment-599254305).

**Comment by equwal** [comment]
> Those who may still be puzzled about the existence of [fakenil](https://www.hexstreamsoft.com/libraries/fakenil/) may find further rationale [here](https://github.com/Hexstream/fakenil/issues/2#issuecomment-599254305).

There you will also find our discussion and complaints about this package.

I don't see any reason to attempt to not publish it, other than for wasting everyone's time with a pointless package.

**Comment by Hexstream** [comment]
@equwal You could *silently* go for fuck yourself, thereby saving everyone's time.

You [are](https://github.com/quicklisp/quicklisp-projects/issues/1805#issuecomment-599234666) an [egregious](https://github.com/Hexstream/fakenil/issues/1) [crybaby](https://github.com/Hexstream/fakenil/issues/2#issuecomment-599257808).
