### ISSUE TITLE
Disappeared project x.let-star needs a new home

### ISSUE THREAD

**Issue by vindarel** [quicklisp/quicklisp-projects#1808]
Hi,

The project x.let-star disappeared from Github: https://github.com/ks/X.LET-STAR.git and that broke some Quicklisp projects (at least cl-transmission and consequently cl-torrents, cl-fixtures, x.fdatatypes)

I couldn't find a fork, but fortunately Quickdocs has an archive (http://quickdocs.org/x.let-star/), which I pushed here: https://github.com/lisp-mirror/x.let-star

Except if you have a better idea for a new home, I invite you to update its source url.

Thanks

**Comment by phoe** [comment]
I have mailed the repository owner and the repo was made public.

Thanks for the quick response, @ks!

**Comment by vindarel** [comment]
Oh, the mail was simply in the asd. Thanks.
