### ISSUE TITLE
Please add trucler

### ISSUE THREAD

**Issue by equwal** [quicklisp/quicklisp-projects#1813]
It is a portable implementation of [cltl2 8.5 Environments](https://www.cs.cmu.edu/Groups/AI/html/cltl/clm/node102.html#SECTION001250000000000000000)

Source: 
https://github.com/s-expressionists/Trucler/

This is depended on by https://github.com/robert-strandh/SICL

**Comment by marcoheisig** [comment]
I just did a quick round of polishing.  Trucler (and especially trucler-native) should now work both on CCL and SBCL.

I think Trucler is now ready to be released on Quicklisp.

**Comment by equwal** [comment]
> I just did a quick round of polishing. Trucler (and especially trucler-native) should now work both on CCL and SBCL.
> 
> I think Trucler is now ready to be released on Quicklisp.

Thanks for getting on that so quickly. Looks like a lot of great work you did.
