### ISSUE TITLE
Please add functional-trees to QuickLisp

### ISSUE THREAD

**Issue by eschulte** [quicklisp/quicklisp-projects#1815]
Hi,

Can you please add the `functional-trees` package to Quicklisp?  The repository is located at the following URL.
https://github.com/GrammaTech/functional-trees

Thanks!

**Comment by quicklisp** [comment]
What's up with the copy of sb-texinfo in a submodule?

**Comment by eschulte** [comment]
We use this simple Makefile infrastructure to easily build and test CL projects, especially from within our CI system.  It's up at https://github.com/grammatech/cl-make (although I wouldn't necessarily recommend anyone use it).  This cl-make submodule uses our own fork of sb-texinfo (up at https://github.com/grammatech/sb-texinfo), which at some point we'll clean up and try to merge back to build texinfo, html, and PDF documentation.

Users of the library should never have to pull or use these submodules.  They just exist so that we could stop copying our CI infrastructure around from project to project.

**Comment by quicklisp** [comment]
Ah, I see. A while ago I started including submodules in projects because a few projects require them. They are unconditionally included right now. I can update the software to conditionally include them, and exclude them from this project and others from GrammaTech.

**Comment by eschulte** [comment]
Great, thanks.  Please let me know if there is anything I can do to help make this more automatic.
