### ISSUE TITLE
Please add Keystone to Quicklisp

### ISSUE THREAD

**Issue by eschulte** [quicklisp/quicklisp-projects#1819]
The KEYSTONE package provides CFFI bindings to the Keystone assembler, and layers on a simple CLOS-based API which exposes a more idiomatic Common Lisp API. Keystone is a vey popular assembler which is useful for assembler instructions to machine-code bytes. It has support for many instruction set architectures.

Keystone homepage: http://www.keystone-engine.org

KEYSTONE package: https://github.com/GrammaTech/keystone

Thanks!
Eric

**Comment by quicklisp** [comment]
Hmm, I'm getting a segfault trying to build libkeystone.so. I'll keep trying.

**Comment by eschulte** [comment]
Oh no.  I'm on Arch Linux where keystone is in the package manager.  I think this Dockerfile should build Keystone on Ubuntu (if that happens to help).

[Dockerfile.txt](https://github.com/quicklisp/quicklisp-projects/files/4371391/Dockerfile.txt)

**Comment by quicklisp** [comment]
Thanks, I was able to use that dockerfile to generate a deb that gets me the dependency.
