### ISSUE TITLE
Please add cl-liballegro

### ISSUE THREAD

**Issue by resttime** [quicklisp/quicklisp-projects#1821]
https://github.com/resttime/cl-liballegro

CFFI bindings to the Allegro5 game programming library

**Comment by quicklisp** [comment]
I can't get it to build: http://report.quicklisp.org/2020-03-25/failure-report/cl-liballegro.html#cl-liballegro

**Comment by resttime** [comment]
Allegro5 splits code into it's main codebase and then separate addons. The build error seems to be trying to load one of the addons. I checked it out and looks like on Ubuntu and maybe other distros the main code does not have a dependency on the addons so installing all the missing addon libraries should work: 

`sudo apt install liballegro-acodec5.2 liballegro-audio5.2 liballegro-dialog5.2 liballegro-image5.2 liballegro-physfs5.2 liballegro-ttf5.2 liballegro-video5.2`

**Comment by quicklisp** [comment]
Thanks for the prompting. I had those packages installed, but had conflicting packages in another path that caused a problem. I resolved the conflict and cl-liballegro will be back in Quicklisp for the next release.

**Comment by resttime** [comment]
Awesome, thanks!
