### ISSUE TITLE
Project fucc is now hosted at GitHub

### ISSUE THREAD

**Issue by monoid** [quicklisp/quicklisp-projects#1822]
Hi!
I've revived my old project fucc after portability bug-report: https://github.com/monoid/fucc/issues/1
I've lost access to common-list.net long time ago, now project lives at GitHub at https://github.com/monoid/fucc/

I see quicklisp can get sources from GitHub.  How can I define release version?  With tag, for example?

**Comment by quicklisp** [comment]
Github has a "release" option that blesses some revision as a release. See https://github.com/monoid/fucc/releases for some links to how it works. I can configure Quicklisp to fetch the latest github release if you choose to use them.

**Comment by monoid** [comment]
Exactly what I need! Yes, I will use GitHub releases. I've created GitHub release v0.2.2.

**Comment by quicklisp** [comment]
Hmm, it looks like there is a tag, but no official release yet. Note that https://api.github.com/repos/monoid/fucc/releases is empty still. I think you have to go to your releases page and use "Draft a new release".

**Comment by monoid** [comment]
Indeed, I have created the release manually.
