### ISSUE TITLE
Please add cl-aubio

### ISSUE THREAD

**Issue by Lautaro-Garcia** [quicklisp/quicklisp-projects#1832]
Hello!

I would like to add cl-aubio to Quicklisp.
It's a project with the bindings for the C [aubio library](https://aubio.org/), used for audio signal processing. The API isn't fully ported yet, but I think I already have the most juicy parts (like note, pitch and onset detection). I checked and I didn't find them already in Quicklisp.

Source, documentation, and usage examples: https://github.com/Lautaro-Garcia/cl-aubio

Thank you!

**Comment by quicklisp** [comment]
I installed the libaubio dev libraries on my system, but I could not build. It worked when I changed the asd to fall back to libaubio.so.5 instead of (or in addition to) plain libaubio. Could you make that change upstream?

**Comment by Lautaro-Garcia** [comment]
Thank you! I made a change adding "libaubio.so.5" for `:unix` systems and "libaubio" as the default library name. I think that has to do it.
