### ISSUE TITLE
Please add clj

### ISSUE THREAD

**Issue by inaimathi** [quicklisp/quicklisp-projects#1848]
https://github.com/inaimathi/clj

**Comment by phoe** [comment]
`IF-LET` and `WHEN-LET` are provided by https://gitlab.common-lisp.net/alexandria/alexandria/
Arrow macros are provided by https://github.com/hipeta/arrow-macros

**Comment by inaimathi** [comment]
> `IF-LET` and `WHEN-LET` are provided by https://gitlab.common-lisp.net/alexandria/alexandria/
> Arrow macros are provided by https://github.com/hipeta/arrow-macros

Cool. I'm aware of `alexandria`, but it has enough unrelated things that I don't generally include it. I wasn't aware of `arrow-macros`; I'll try to incorporate those rather than rolling my own. I'm not aware of libraries that do the other stuff I'm planning to put together here.

**Comment by inaimathi** [comment]
Updated
