### ISSUE TITLE
com.dvlsoft.clon -- QL compile error

### ISSUE THREAD

**Issue by mon-key** [quicklisp/quicklisp-projects#185]
com.dvlsoft.clon -- QL compile error

This afternoon I tried loading com.dvlsoft.clon
The system failed to load on both SBCL 1.0.47.1 and SBCL 1.0.49.65-a3c77b1

I pasted backtraces for SBCL 1.0.47.1 here: 
  http://paste.lisp.org/+2N4P

I pasted backtraces for 1.0.49.65-a3c77b1 here: 
 http://paste.lisp.org/+2N4P/1

I pasted some notes as to some possible points of failure here:
 http://paste.lisp.org/+2N4P/2

**Comment by 275761919** [comment]
Hello, have you sovled this problem?
I encounter this error now.
