### ISSUE TITLE
please add magicffi

### ISSUE THREAD

**Issue by guicho271828** [quicklisp/quicklisp-projects#1862]
https://github.com/guicho271828/magicffi

The older repo by dochang no longer builds and was removed in the past.
now it is CI tested.
https://travis-ci.org/guicho271828/magicffi

**Comment by quicklisp** [comment]
magicffi builds fine for me. Have you discussed taking over maintenance from the original owner?

**Comment by guicho271828** [comment]
I sent an email but there was no answer.

**Comment by guicho271828** [comment]
email on 3/13.

**Comment by guicho271828** [comment]
AFAIK the original repository was removed from quicklisp because it failed.

**Comment by guicho271828** [comment]
http://blog.quicklisp.org/2017/10/

**Comment by guicho271828** [comment]
I tested the original repository now and it fails to compile.
```
Subprocess #<UIOP/LAUNCH-PROGRAM::PROCESS-INFO {1010540DC3}>
 with command ("cc" "-o"
               "/home/masataro/.cache/common-lisp/sbcl-2.0.5-linux-x64/home/masataro/repos/lisp/magicffi/grovel__grovel-tmpJAIDFZTC.o"
               "-c" "-g" "-Wall" "-Wundef" "-Wsign-compare"
               "-Wpointer-arith" "-O3" "-D_LARGEFILE_SOURCE"
               "-D_LARGEFILE64_SOURCE" "-D_FILE_OFFSET_BITS=64"
               "-Wunused-parameter" "-fno-omit-frame-pointer"
               "-momit-leaf-frame-pointer" "-fPIC"
               "-I/home/masataro/.roswell/lisp/quicklisp/dists/quicklisp/software/cffi_0.20.1/"
               "/home/masataro/.cache/common-lisp/sbcl-2.0.5-linux-x64/home/masataro/repos/lisp/magicffi/grovel__grovel.c")
 exited with error code 1
```

just made sure to update the quicklisp dist, same results.

**Comment by guicho271828** [comment]
It seems magicffi is still not visible in quicklisp.
I have the latest version of quicklisp from 2020-07-15.
I find it odd that the source.txt is present even before proposing this change but it was still not visible in quicklisp.
Is there a feature that is potentially blocking/blacklisting magicffi?
I remember the asdf name / package name / asdf file name mismatch may cause such issues, but this is not the case in magicffi.

**Comment by guicho271828** [comment]
ah, it is blacklisted.
https://github.com/quicklisp/quicklisp-projects/blob/master/qlc-meta/blacklist.txt#L155

**Comment by quicklisp** [comment]
Thank you, that should be enough to help me fix it.
