### ISSUE TITLE
Please add py4cl2

### ISSUE THREAD

**Issue by digikar99** [quicklisp/quicklisp-projects#1864]
https://github.com/digikar99/py4cl2

It's a bunch of [backward incompatible improvements](https://digikar99.github.io/py4cl2/#changes-over-py4cl) over [py4cl](https://github.com/bendudson/py4cl). `py4cl` enables use of python libraries in common lisp using stream based interprocess communication. Feature compatibility for py4cl2 across implementations varies; [last release Travis build](https://travis-ci.org/github/digikar99/py4cl2/builds/700316466); and is documented [here](https://digikar99.github.io/py4cl2/#changes-over-py4cl).

**Comment by quicklisp** [comment]
I'm worried that the name will make people think that it is a new version of py4cl, rather than a fork. Is there another name you would consider?

**Comment by digikar99** [comment]
I'm still debating whether `py4cl2` should exist separate from `py4cl`. There are a few more improvements that could be backported to py4cl since the last backport, but with the other things, it'd simply need people to not upgrade quicklisp-dist / need to maintain a local copy of py4cl until they make sure their projects work.

`python-process` is another name that occurs to me; any other suggestions?

**Comment by digikar99** [comment]
Put this on hold until the next-to-next release - so, avoid putting it in the July 2020 dist.

**Comment by quicklisp** [comment]
I like whimsical (or stupid, depending on your preferences) names. So maybe something like "snakecharmer". (If that's not already taken by something wildly popular in approximately the same space.)

**Comment by digikar99** [comment]
Oh, nothing about the name; I hope to take out time in the upcoming month to discuss the things with py4cl's author.

**Comment by digikar99** [comment]
Okay, you can add in the next release; the original author has agreed to let the remain as `py4cl2`
