### ISSUE TITLE
Please add colored

### ISSUE THREAD

**Issue by Shinmera** [quicklisp/quicklisp-projects#1866]
This is a library for representing and mapping colours between their various spaces.

Author: Nicolas Hafner
License: zlib
Homepage: https://shinmera.github.io/colored
Sources: https://github.com/Shinmera/colored.git

**Comment by quicklisp** [comment]
Failure log here: http://report.quicklisp.org/2020-07-09/failure-report/colored.html

**Comment by Shinmera** [comment]
Sorry about that, should be fixed.

**Comment by quicklisp** [comment]
Still a minor issue - log here: http://report.quicklisp.org/2020-07-10/failure-report/colored.html#colored-test

**Comment by Shinmera** [comment]
Fixed for sure this time.
