### ISSUE TITLE
Please add math

### ISSUE THREAD

**Issue by mnasoft** [quicklisp/quicklisp-projects#1881]
Math is a mathematical library that implements some algorithms of linear algebra, statistics, finding approximating polynomials on Common Lisp

Author: Nick Matvyeyev
License: GNU GENERAL PUBLIC LICENSE Version 3, 29 June 2007
Homepage: https://github.com/mnasoft/math
Sources: https://github.com/mnasoft/math.git

**Comment by quicklisp** [comment]
Failure log here: http://report.quicklisp.org/2020-08-12/failure-report/math.html

**Comment by quicklisp** [comment]
New failure:  The name "CL-UTILITIES" does not designate any package.

Log here: http://report.quicklisp.org/2020-08-24/failure-report/math.html#math

**Comment by mnasoft** [comment]
:CL-UTILITIES added as dependency.

пн, 24 авг. 2020 г. в 14:13, Zach Beane <notifications@github.com>:

**Comment by quicklisp** [comment]
There are still a number of systems in this project that don't build.
