### ISSUE TITLE
Suggestion: Add an issue template to this repository

### ISSUE THREAD

**Issue by fstamour** [quicklisp/quicklisp-projects#1898]
Adding an issue template to this repository would reduce the back and forth.

https://docs.github.com/en/enterprise/2.14/user/articles/creating-issue-templates-for-your-repository

**Comment by quicklisp** [comment]
What back and forth?

**Comment by fstamour** [comment]
Moslty when somebody doens't leave enough information on a package to add.

**Comment by quicklisp** [comment]
That has not to date been an issue warranting a template.

**Comment by fstamour** [comment]
Fine by me
