### ISSUE TITLE
Please add cl-data-structures

### ISSUE THREAD

**Issue by sirherrbatka** [quicklisp/quicklisp-projects#1907]
Cl-data-structures offers a set of data structures with a uniform API along with stream-like ranges and algorithms operating on those.

Github: https://github.com/sirherrbatka/cl-data-structures
Licence: Simplified BSD

**Comment by quicklisp** [comment]
Failure log here: http://report.quicklisp.org/2020-11-26/failure-report/cl-data-structures.html

**Comment by sirherrbatka** [comment]
If I understand this correctly, error is caused by a lack of :description in the asd files. I corrected it.

**Comment by quicklisp** [comment]
There's a new error:
http://report.quicklisp.org/2020-11-28/failure-report/cl-data-structures.html#cl-data-structures

Why does the repo not support issues?

**Comment by sirherrbatka** [comment]
No reason. I will setup issues.

**Comment by sirherrbatka** [comment]
Anyway, this was a little bit shameful, but there were a couple of other warnings on top of that. I think that I would have never fix them if not for this particular issue.

**Comment by sirherrbatka** [comment]
@quicklisp I am pretty sure that cl-data-structures builds without problems now. Is there anything else wrong?

**Comment by quicklisp** [comment]
Everything builds now, thanks.

**Comment by sirherrbatka** [comment]
Glad to hear that.
