### ISSUE TITLE
Please add :claw dependencies

### ISSUE THREAD

**Issue by borodust** [quicklisp/quicklisp-projects#1909]
Those are all dependencies required by new version of `:claw` and most libraries that depend on it.

Please, add:

* [claw-utils](https://github.com/borodust/claw-utils/tree/stable) (`stable` branch) - utilities for `:claw`
* [cffi-c-ref](https://github.com/borodust/cffi-c-ref/tree/stable) (`stable` branch) - advanced memory referencing for `:claw`/`CFFI`
* [claw-support](https://github.com/borodust/claw-support/tree/stable) (`stable` branch) - additional tooling for `:claw` 
* [c2ffi-blob](https://github.com/borodust/c2ffi-blob/tree/stable) (`stable` branch) - precompiled c2ffi executable

**Comment by quicklisp** [comment]
All added.
