### ISSUE TITLE
Please fix cl-digraph

### ISSUE THREAD

**Issue by mfiano** [quicklisp/quicklisp-projects#1913]
As per #1225, the author recommends pulling from either his BitBucket repository or the GitHub mirror, however it seems that he removed all of his repositories from BitBucket, and only the GitHub repository has been updated in some time.

I request that we please point to the GitHub repository instead, as the tracked version is fairly old (and broken [runtime errors] on SBCL) at this point.

Thank you.

**Comment by quicklisp** [comment]
How does this relate to https://github.com/quicklisp/quicklisp-projects/pull/1876?
