### ISSUE TITLE
Please add GUTE

### ISSUE THREAD

**Issue by genelkim** [quicklisp/quicklisp-projects#1921]
https://github.com/genelkim/gute
This is my personal utility repository. It is a dependency for a few other projects that I plan to upload soon.

**Comment by quicklisp** [comment]
I will be happy to add it. But in a quick glance at the code there seem to be a number of errors in it. Would you consider having someone review the code before adding it to Quicklisp?

**Comment by phoe** [comment]
@quicklisp Which ones do you mean? This seems just like another utility library tailored to its author's use cases. There are situations where this code could have been written better, e.g. `argnum` would be `alexandria:parse-ordinary-lambda-list` over `conium:arglist` without defining `grouped-arglist` whatsoever, but I can't see any immediate errors from a very brief glance there.

**Comment by quicklisp** [comment]
Here's an example of an outright error: https://github.com/genelkim/gute/blob/6bf5df8517b6b7c2ad865ebc6860a98eb49c637f/io.lisp#L30 

Here are a few things that are incomplete and/or concerning:

* https://github.com/genelkim/gute/blob/6bf5df8517b6b7c2ad865ebc6860a98eb49c637f/general.lisp#L37
* https://github.com/genelkim/gute/blob/6bf5df8517b6b7c2ad865ebc6860a98eb49c637f/hashtable.lisp#L15

**Comment by quicklisp** [comment]
https://github.com/genelkim/gute/blob/6bf5df8517b6b7c2ad865ebc6860a98eb49c637f/io.lisp#L16

**Comment by genelkim** [comment]
I would be more than grateful to have this package improved with a code review by some proper CL coders. But I don't want to commit anyone to spending their time doing that if it's a hassle. As @phoe pointed out, the code is closely tailored to my needs/preferences (and based on my ignorance of existing solutions for common problems).

I'm mainly want to get this on quicklisp because it's used by several other more coherent packages that I'll be adding to quicklisp.
