### ISSUE TITLE
Please add bitfield - a library for packing data into non-negative integers.

### ISSUE THREAD

**Issue by marcoheisig** [quicklisp/quicklisp-projects#1922]
I just wrote a library for packing plenty of information into a single non-negative integer.  I think the library is very convenient and I'd like to make it available on Quicklisp.

Here is the repository: https://github.com/marcoheisig/bitfield

**Comment by quicklisp** [comment]
Would you please add a description to the system definition?

**Comment by marcoheisig** [comment]
Done.
