### ISSUE TITLE
Please add fuzzy-match

### ISSUE THREAD

**Issue by vindarel** [quicklisp/quicklisp-projects#1923]
Hi, can you add fuzzy-match? 

https://github.com/vindarel/fuzzy-match

From one string input and a list of candidates, it returns the ones that apply, best first. 
It uses one string metrics, and crafts the results further.

```
(fuzzy-match:fuzzy-match "ofo" '("baaarfoo" "foo!" "ufo" "mmh"))
;; ("foo!" "baaarfoo")
```

thanks

**Comment by quicklisp** [comment]
Failure log here: http://report.quicklisp.org/2020-11-26/failure-report/fuzzy-match.html

**Comment by vindarel** [comment]
fixed, thanks. I also fixed `asdf:test-system "fuzzy-match"` to pass.
