### ISSUE TITLE
Please add stefil+

### ISSUE THREAD

**Issue by ruricolist** [quicklisp/quicklisp-projects#1924]
Stefil+ is a set of enhancements for the Stefil test framework.

This is now a dependency of [SEL](https://github.com/GrammaTech/sel).

https://github.com/GrammaTech/stefil-

**Comment by quicklisp** [comment]
Failure log here: http://report.quicklisp.org/2020-11-26/failure-report/stefil-.html

**Comment by ruricolist** [comment]
I have not been able to reproduce this failure locally, but I've added an explicit dependency on sb-sprof to [gt/profile](https://github.com/GrammaTech/cl-utils/blob/master/profile.lisp).

**Comment by quicklisp** [comment]
You have to add it as a dependency in the system file. sb-sprof is not part
of SBCL by default.

**Comment by quicklisp** [comment]
Oh, right, package-inferred-system, so not the same process.
