### ISSUE TITLE
Please add aether

### ISSUE THREAD

**Issue by karalekas** [quicklisp/quicklisp-projects#1929]
`aether` is a framework for emulating an actor-based distributed system housed on a family of emulated devices.

Here's a link to the git repository: https://github.com/dtqec/aether

We'd like to have it fetched from the most recently released git tag, which as of today is `v1.0.0`.

Thank you!

**Comment by quicklisp** [comment]
The test system doesn't build - can you please fix it?

**Comment by karalekas** [comment]
@quicklisp PR is open https://github.com/dtqec/aether/pull/27 -- once merged, I will release another version `v1.0.1`

**Comment by karalekas** [comment]
Alright the new version has been released https://github.com/dtqec/aether/releases/tag/v1.0.1
