### ISSUE TITLE
Please add DEFINER to Quicklisp.

### ISSUE THREAD

**Issue by marcoxa** [quicklisp/quicklisp-projects#1947]
Hi

I fixed a long standing (and idiotic, on my part) bug in the ASDF definition for DEFINER.

It should now be ready for inclusion in Quicklisp.

Thank you (and thank Mariano Montone for pointing out the obvious fix).

Marco

https://gitlab.common-lisp.net/definer/definer

**Comment by quicklisp** [comment]
Failure log here: http://report.quicklisp.org/2020-12-20/failure-report/definer.html

**Comment by marcoxa** [comment]
Ok.  Easy to fix...

**Comment by marcoxa** [comment]
Should be fixed in repo.
