### ISSUE TITLE
Please add WITH-CONTEXTS

### ISSUE THREAD

**Issue by marcoxa** [quicklisp/quicklisp-projects#1952]
Here is the gitlab

https://gitlab.common-lisp.net/mantoniotti/with-contexts

Thanks

**Comment by phoe** [comment]
I assume you mean https://gitlab.common-lisp.net/mantoniotti/with-contexts - I can't see the gitlab link in the above post.

Random curious question - do you have any tests for it?

**Comment by marcoxa** [comment]
Wrong cut-n-paste.

Sorry.

Very lightly tested.  The OPEN-FILE example works, btu I have not checked much more complex examples.

MA

**Comment by marcoxa** [comment]
Just added the full blown example of the Python  "exit context" that generates an error in the middle of opening a bunch of files.
Works as well (of course, I had some bugs in the code :)
