### ISSUE TITLE
Please (re)add TCLCS-CODE

### ISSUE THREAD

**Issue by phoe** [quicklisp/quicklisp-projects#1954]
Woop, I forgot that the `clcs-code` repository was Quicklisped, and got it removed from Quicklisp. Oh bother.

https://github.com/phoe/tclcs-code

**Comment by quicklisp** [comment]
I can't pull a subdirectory. What is https://github.com/phoe/portable-condition-system/ ?

**Comment by quicklisp** [comment]
Any update on this?

**Comment by phoe** [comment]
`portable-condition-system` is the canonical repository for PCS that is already in quicklisp; it is a different system than `tclcs-code`.

Give me a moment, I'll make the proper repository for the latter.

**Comment by phoe** [comment]
Done: https://github.com/phoe/tclcs-code
