### ISSUE TITLE
Quickdocs link is not helpful anymore

### ISSUE THREAD

**Issue by rtoy** [quicklisp/quicklisp-projects#1956]
On https://www.quicklisp.org/beta/, there's a link to quickdocs:

> While ql:system-apropos is useful for simple string searches of system and project names, Quickdocs provides a more general full-text search for systems and projects.

But following the link, we find that Quickdocs has been closed since Oct 16, 2020.  While I don't think I ever used Quickdocs, that's kind of unfortunate.

The link should probably be updated or removed as appropriate.

**Comment by phoe** [comment]
Quickref (https://quickref.common-lisp.net/) has taken its place.

**Comment by rtoy** [comment]
Ah. Nevertheless the link to quickdocs should be updated to quickref.

**Comment by quicklisp** [comment]
I took out the quickdocs link.

**Comment by guicho271828** [comment]
There are so much missing in quickref. Given Fukamachi has so much real web dev experience, the CSS is right, search works, there was depends-on / used-by links, ...

**Comment by Hexstream** [comment]
Note that [the revival of Quickdocs has just been announced by its original author](https://twitter.com/nitro_idiot/status/1366329581599215623) [thanks to support on GitHub Sponsors](https://github.com/sponsors/fukamachi), so getting rid of Quickdocs links is now much less useful, as they will work again soon.
