### ISSUE TITLE
Quickdocs link not helpful anymore

### ISSUE THREAD

**Issue by rtoy** [quicklisp/quicklisp-projects#1957]
On https://www.quicklisp.org/beta/, there's a link to quickdocs:

> While ql:system-apropos is useful for simple string searches of system and project names, Quickdocs provides a more general full-text search for systems and projects.

But following the link, we find that Quickdocs has been closed since Oct 16, 2020.  While I don't think I ever used Quickdocs, that's kind of unfortunate.

The link should probably be updated or removed as appropriate.

**Comment by phoe** [comment]
Duplicate of #1956

**Comment by rtoy** [comment]
Yeah, for some reason it looked like it wasn't actually submitted (404 error), but it actually was.  Closing.
