### ISSUE TITLE
Please Add Portal

### ISSUE THREAD

**Issue by charJe** [quicklisp/quicklisp-projects#1962]
Simple and portable websocket server library. I have tested `sbcl` and `ecl` on Linux.

https://github.com/charJe/portal

**Comment by quicklisp** [comment]
Failure log here: http://report.quicklisp.org/2021-01-16/failure-report/portal.html

**Comment by charJe** [comment]
Do I need to resubmit or is fixing it in the repository enough?

**Comment by phoe** [comment]
AFAIK fixing it in the repository is enough.
