### ISSUE TITLE
Please add cl-fxml

### ISSUE THREAD

**Issue by Goheeca** [quicklisp/quicklisp-projects#1969]
https://github.com/Goheeca/cl-fxml

Loads fine and works on SBCL, and ABCL.

I also tried CLISP 2.49.92 (2018-02-18), but the dependency `named-readtables` failed to load:
```
*** - Error while trying to load definition for system named-readtables from pathname /home/goheeca/quicklisp/dists/quicklisp/software/named-readtables-20201220-git/named-readtables.asd:
      REINITIALIZE-INSTANCE: illegal keyword/value pair :MAILTO, "mega@retes.hu" in argument list.
      The allowed keywords are (:NAME :VERSION :IN-ORDER-TO :DO-FIRST :PARENT :PATHNAME :AROUND-COMPILE :ENCODING
      :PROPERTIES :COMPONENTS :IF-COMPONENT-DEP-FAILS :DEFAULT-COMPONENT-CLASS :DESCRIPTION :LONG-DESCRIPTION :AUTHOR :MAINTAINER :LICENCE :LICENSE :SOURCE-FILE :DEFSYSTEM-DEPENDS-ON)
```

**Comment by Hexstream** [comment]
CLISP has not seen an *official* release in more than a decade, so no need to worry about supporting it, in my view. We already have plenty of actively *officially* supported implementations to worry about.

(Yes, I am aware that there is an *unofficial* fork of CLISP somewhere.)

**Comment by xach** [comment]
CLISP failure is not a deal-breaker.

**Comment by phoe** [comment]
The CLISP failure you mention sounds like something that could be solved by updating ASDF to a newer version. (AFAIK the last CLISP release still ships with ASDF 2 by default.)

If you feel like spending a while on that, you could try upgrading your local CLISP installation to ASDF 3.4+ (e.g. by downloading and loading https://common-lisp.net/project/asdf/archives/asdf.lisp into it) and see if your system and its dependencies load correctly then.

**Comment by xach** [comment]
CLISP does not include ASDF at all, so it's likely using the Quicklisp fallback 2.26.

**Comment by phoe** [comment]
OK - that's plausible. (It's likely a question for a separate issue, is it feasible/possible for Quicklisp to bump up its fallback ASDF version to 3.x? Why not?)

**Comment by Goheeca** [comment]
After loading the linked `asdf` into CLISP, everything worked fine.

**Comment by phoe** [comment]
Good - it's an issue of an old ASDF, then, and nothing wrong with your system.
