### ISSUE TITLE
Prevent quicklisp from trying to build the DQVM package from QVM

### ISSUE THREAD

**Issue by notmgsk** [quicklisp/quicklisp-projects#1971]
Hi, @quicklisp 

QVM defines a few packages, one of which is DQVM. Unfortunately DQVM depends on a patch to CL-MPI which has yet to be added to the mainline; more unfortunate is that it doesn't look like that patch will be applied any time soon, if ever. This all means that the DQVM build fails for quicklisp, and I get notifications for it. Is there any way to disable building/providing DQVM in quicklisp (not including the obvious "remove it from QVM")?

**Comment by phoe** [comment]
> more unfortunate is that it doesn't look like that patch will be applied any time soon, if ever.

Could you link to the patch in question? Is there a PR or issue on the main repository?

**Comment by notmgsk** [comment]
https://github.com/marcoheisig/cl-mpi/pull/29

**Comment by quicklisp** [comment]
I can hide it from the build system so there aren't RSS failure entries for it. This is done most easily via the https://github.com/quicklisp/quicklisp-projects/blob/master/qlc-meta/excluded-systems.txt file.

**Comment by notmgsk** [comment]
@quicklisp that would be helpful. Thanks

**Comment by quicklisp** [comment]
Ok, done.
