### ISSUE TITLE
MAGICL: quicklisp complains that "ABSTRACT-CLASSES" does not designate any package

### ISSUE THREAD

**Issue by notmgsk** [quicklisp/quicklisp-projects#1972]
See http://report.quicklisp.org/2021-01-25/failure-report/magicl.html#magicl-gen

Having trouble narrowing this down. Any suggestions, @quicklisp? Might help if `depcheck` was available publicly.

**Comment by phoe** [comment]
Quickloading `abstract-classes` should be enough to make the package appear on Quicklisp dist `"2020-12-20"`.

```lisp
CL-USER> (ql:quickload :abstract-classes)
To load "abstract-classes":
  Load 1 ASDF system:
    abstract-classes
; Loading "abstract-classes"

(:ABSTRACT-CLASSES)
CL-USER> (describe (find-package :org.tfeb.hax.final-classes))
#<PACKAGE "ORG.TFEB.HAX.ABSTRACT-CLASSES">
  [package]

Nicknames: ABSTRACT-CLASS, ABSTRACT-CLASSES, ORG.TFEB.HAX.FINAL-CLASSES
Use-list: CLOSER-MOP, COMMON-LISP
Shadows: BUILT-IN-CLASS, CLASS-NAME, CLASS-OF, DEFGENERIC, DEFMETHOD,
         ENSURE-GENERIC-FUNCTION, FIND-CLASS, STANDARD-CLASS,
         STANDARD-GENERIC-FUNCTION, STANDARD-METHOD, VALIDATE-SUPERCLASS
Exports: ABSTRACT-CLASS, DEFINE-ABSTRACT-CLASS, DEFINE-FINAL-CLASS,
         FINAL-CLASS
17 internal symbols.

CL-USER> (find-package :abstract-classes)
#<PACKAGE "ORG.TFEB.HAX.ABSTRACT-CLASSES">
```

**Comment by notmgsk** [comment]
I'm not sure why I should have to do that, since `abstract-classes` is already listed in `magicl-gen.asd` `:depends-on`: https://github.com/rigetti/magicl/blob/master/magicl-gen.asd#L10 The same is in `magicl.asd` which, ostensibly, does not raise an error in quicklisp.

**Comment by phoe** [comment]
Yes, that seems weird to me - the dependency is explicitly listed there and the package should be present.

**Comment by quicklisp** [comment]
The latest release of magicl (v0.7.0) does not include abstract-classes as a dependency. https://github.com/rigetti/magicl/blob/v0.7.0/magicl-gen.asd

depcheck is public (it's part of quicklisp-controller) but in this case it's not doing anything that you can't do yourself directly with asdf: clone magicl, check out v0.7.0, then try to load the magicl-gen system. It fails in the same way.
