### ISSUE TITLE
Please add org.tfeb.hax

### ISSUE THREAD

**Issue by tfeb** [quicklisp/quicklisp-projects#1976]
Repo is https://github.com/tfeb/tfeb-lisp-hax, documentation (again, just the README) is https://tfeb.github.io/tfeb-lisp-hax.

This is a really miscellaneous bunch of small things: what they have in common is that I wrote them all really.  Some of them are useful, perhaps.

**Comment by quicklisp** [comment]
Failure log here: http://report.quicklisp.org/2021-02-25/failure-report/tfeb-lisp-hax.html

**Comment by tfeb** [comment]
Sorry, that was a stupid bug because I didn't test in a cold enough lisp.

This should be resolved by tfeb/tfeb-lisp-hax@6a56b40cc90d790be4ee9ad02afe8b459e583cb8 (which is also v2.0.0).
