### ISSUE TITLE
Please add GECO 2.1.2

### ISSUE THREAD

**Issue by gpwwjr** [quicklisp/quicklisp-projects#1982]
No changes to the software, only the documentation (Docs subdirectory, and the geco-pdf.tar.gz release asset), the README.md, and CHANGES.txt files have been updated.

**Comment by gpwwjr** [comment]
I forgot to point to the repo: https://github.com/gpwwjr/GECO

**Comment by quicklisp** [comment]
Thanks for letting me know, but Quicklisp will do this automatically.
