### ISSUE TITLE
Please add trivial-coerce

### ISSUE THREAD

**Issue by digikar99** [quicklisp/quicklisp-projects#1984]
Library is at https://github.com/digikar99/trivial-coerce
Please fetch from the releases: https://github.com/digikar99/trivial-coerce/releases

`trivial-coerce` primarily provides a `trivial-coerce:coerce` function that is intended as an extensible alternative to `cl:coerce`.

**Comment by quicklisp** [comment]
Failure log here: http://report.quicklisp.org/2021-02-25/failure-report/trivial-coerce.html

**Comment by digikar99** [comment]
Please delay adding this until at least the next quicklisp release

**Comment by digikar99** [comment]
This library has been replaced by (renamed to) https://github.com/digikar99/extensible-optimizing-coerce - a number of people, myself included, felt that the library was not "trivial". Let the "trivial" name be left for some other library if it comes about some day.

Please fetch the latest tags from the new URL.
