### ISSUE TITLE
Please add pvars

### ISSUE THREAD

**Issue by ralt** [quicklisp/quicklisp-projects#1985]
Repository: https://gitlab.com/ralt/pvars
Description: `pvars` is a small library to easily define persistent variables. Use them as normal variables, but they are actually persistent.
License: MIT
Prior art: [persistent-variables](https://github.com/WarrenWilkinson/persistent-variables) exists and is similar, but `pvars` offers a fully-transparent API.

**Comment by quicklisp** [comment]
Would you please add a `:description` to the system file?
