### ISSUE TITLE
Please add Consfigurator

### ISSUE THREAD

**Issue by spwhitton** [quicklisp/quicklisp-projects#1992]
Library is at https://git.spwhitton.name/consfigurator where you can find signed git tags and tarballs generated from those tags.

Or, if it's easier, there's a [mirror on GitHub](https://github.com/spwhitton/consfigurator) which has tags and [tarballs](https://github.com/spwhitton/consfigurator/releases).

Consfigurator is a Lisp declarative configuration management system.  Please see [the README](https://git.spwhitton.name/consfigurator/about/) for more.

Tested and working with SBCL, ABCL and ECL.

Thank you for maintaining Quicklisp!

[name is not a typo :)]

**Comment by quicklisp** [comment]
Do you recommend using the latest tag/release? Or is the master branch the
thing to use?

**Comment by spwhitton** [comment]
On Thu 25 Feb 2021 at 02:09PM -08, Zach Beane wrote:

> Do you recommend using the latest tag/release? Or is the master branch the
> thing to use?

The latest tags/releases, I think, because I test them more throughly
before tagging.  Thanks!

-- 
Sean Whitton
