### ISSUE TITLE
Please add cl-megolm and my fork of claw-olm.

### ISSUE THREAD

**Issue by K1D77A** [quicklisp/quicklisp-projects#2001]
https://github.com/K1D77A/cl-megolm 
https://github.com/K1D77A/claw-olm

Hi could you please add both of these repos, they are both MIT. 
They depend on the foreign library found here: https://gitlab.matrix.org/matrix-org/olm/-/tree/master/

Thanks.

**Comment by quicklisp** [comment]
Failure log here: http://report.quicklisp.org/2021-04-22/failure-report/claw-olm.html

**Comment by K1D77A** [comment]
Hi,
I believe I have fixed the issue by adding :description into claw-olm-bindings.asd in https://github.com/K1D77A/claw-olm 
Thanks.

**Comment by quicklisp** [comment]
Failure log here: http://report.quicklisp.org/2021-05-13/failure-report/claw-olm.html

**Comment by borodust** [comment]
Ignore required for `claw-olm/wrapper` system.

**Comment by quicklisp** [comment]
cl-megolm's foreign library definitions are too specific in specifying /usr/local/lib - they should just refer to the library name.

**Comment by quicklisp** [comment]
claw-olm works fine though.

**Comment by K1D77A** [comment]
So just libolm.so instead of /usr/local/lib/libolm... etc ?

**Comment by phoe** [comment]
Yep. It's up to the OS to locate the library file on the filesystem.

**Comment by K1D77A** [comment]
Okay updated

**Comment by K1D77A** [comment]
Thanks :+1:
