### ISSUE TITLE
Please add mnas-string

### ISSUE THREAD

**Issue by mnasoft** [quicklisp/quicklisp-projects#2003]
https://github.com/mnasoft/mnas-string.

The mnas-string system is intended for:
    parsing a real number;
    splitting a string into substrings;
    replacing all occurrences of a substring in a string;
    replacing multiple occurrences of a pattern with a single one;
    preparing a string as an argument for a like SQL query;
    framing a string with a prefix and a postfix;
    outputting the date and time representation to a stream or string;
    string tracing.

**Comment by quicklisp** [comment]
Failure log here: http://report.quicklisp.org/2021-04-22/failure-report/mnas-string.html

**Comment by mnasoft** [comment]
Recheck it please.

mnas-package removed as dependencies for mnas-string/docs.
sb-posix added as dependencies for mnas-string/tests.

Could you explain how you setup testing environment for checking asdf-system on errors.
It will be useful in order to check  asdf-system by myself.
