### ISSUE TITLE
Please add mnas-package

### ISSUE THREAD

**Issue by mnasoft** [quicklisp/quicklisp-projects#2006]
https://github.com/mnasoft/mnas-package

**Description**
The mnas-package system is designed to extract information from asdf systems.
The extracted information is presented in the form of graphs.
The system allows you to build the following graphs:
- system dependencies;
- function calls;
- variable using;
- class inheritance.

**License**
GNU GENERAL PUBLIC LICENSE Version 3, 29 June 2007 or later

**Comment by quicklisp** [comment]
Failure log here: http://report.quicklisp.org/2021-04-22/failure-report/mnas-package.html

**Comment by mnasoft** [comment]
Recheck in please.

mnas-package/obj added as dependenсe to mnas-package/obj
slynk added as dependenсe to mnas-package/pkg
2 test was corrected

**Comment by phoe** [comment]
> mnas-package/obj added as dependenсe to mnas-package/obj

This doesn't look healthy. Could you check if this description is correct?

**Comment by mnasoft** [comment]
Please recheck https://github.com/mnasoft/mnas-package.

**Comment by mnasoft** [comment]
> mnas-package/obj added as dependenсe to mnas-package/obj

 mnas-package/obj added as dependenсe to mnas-package/pkg
