### ISSUE TITLE
Please add Tailrec (dual license)

### ISSUE THREAD

**Issue by charJe** [quicklisp/quicklisp-projects#2014]
Is it allowed to have dual licensed libraries on Quicklisp?
It it the same as Tailrec but with gpl components absent.

It should be retrieved from https://github.com/charJe/tailrec/archive/refs/heads/llgpl.zip.
It provides the `tailrec-llgpl` system.

**Comment by quicklisp** [comment]
I can't pull from that link. Do you have another?

**Comment by charJe** [comment]
That links downloads a zip. What kind of link do you need?

**Comment by charJe** [comment]
If you need a tarball: https://github.com/charJe/tailrec/releases/latest
