### ISSUE TITLE
cl-opencl: OpenCL API for Common Lisp

### ISSUE THREAD

**Issue by ghollisjr** [quicklisp/quicklisp-projects#2019]
I've finished the core OpenCL API with a Lisp wrapper in this project: [cl-opencl](https://github.com/ghollisjr/cl-opencl).

If you think it would be a useful addition to the quicklisp library, feel free to add it!

**Comment by quicklisp** [comment]
Failure log here: http://report.quicklisp.org/2021-04-22/failure-report/cl-opencl.html

**Comment by ghollisjr** [comment]
Thank you for trying to build cl-opencl; unfortunately the groveler doesn't copy compiler error messages, so I can't tell what's causing the C compiler to fail on that system.  Is it possible to execute the 

("cc" "-o" "/home/quicklisp/.cache/common-lisp/sbcl-2.1.3-linux-x64/home/quicklisp/quicklisp-controller/dist/build-cache/cl-opencl/4c65dc04f4eda652b37c526d73775ae8049717da/cl-opencl-20210422-git/grovel__grovel-tmp5GEXGEG5.o" "-c" "-g" "-Wall" "-Wundef" "-Wsign-compare" "-Wpointer-arith" "-O3" "-D_LARGEFILE_SOURCE" "-D_LARGEFILE64_SOURCE" "-D_FILE_OFFSET_BITS=64" "-Wunused-parameter" "-fno-omit-frame-pointer" "-momit-leaf-frame-pointer" "-fPIC" "-I/home/quicklisp/quicklisp-controller/dist/build-cache/cffi/e2767d598164ea88c0aa74a99efb2c0314a00506/cffi_0.24.1/" "/home/quicklisp/.cache/common-lisp/sbcl-2.1.3-linux-x64/home/quicklisp/quicklisp-controller/dist/build-cache/cl-opencl/4c65dc04f4eda652b37c526d73775ae8049717da/cl-opencl-20210422-git/grovel__grovel.c")

command in e.g. Bash and forward the output?

**Comment by ghollisjr** [comment]
As a basic check: The headers for OpenCL are installed on that system?

**Comment by ghollisjr** [comment]
I've removed a few of the experimental OpenCL API features that may have been causing problems
