### ISSUE TITLE
Please add cl-vorbis

### ISSUE THREAD

**Issue by Shinmera** [quicklisp/quicklisp-projects#2025]
This is a small library wrapping stb_vorbis to provide a fast, libre, and easy-to-ship OGG/Vorbis decoder.

Author: Nicolas Hafner
License: zlib
Source: https://github.com/shirakumo/cl-vorbis.git
Documentation: https://shirakumo.github.io/cl-vorbis/

**Comment by quicklisp** [comment]
Failure log here: http://report.quicklisp.org/2021-05-13/failure-report/cl-vorbis.html

**Comment by Shinmera** [comment]
Should be fixed as of Shinmera/cl-vorbis@03f61cba944aab99cd764d39a9d47718c14d0b83
