### ISSUE TITLE
Please add Lisp-Stat 'plot' library

### ISSUE THREAD

**Issue by Symbolics** [quicklisp/quicklisp-projects#2029]
'plot' is a plotting library for common lisp. Although part of Lisp-Stat, it may be used independently. It focuses primarily on web based, interactive plotting using Vega-Lite and Plotly backends.

https://github.com/Lisp-Stat/plot

**Comment by quicklisp** [comment]
Does not build. http://report.quicklisp.org/2021-05-02/failure-report/plot.html#plot

**Comment by Symbolics** [comment]
The latest push should fix this.
