### ISSUE TITLE
Please update cl-naive-store

### ISSUE THREAD

**Issue by Harag** [quicklisp/quicklisp-projects#2037]
git@gitlab.com:Harag/cl-naive-store.git
or
https://gitlab.com/Harag/cl-naive-store.git

Dependencies:

  cl-fad
  iron-clad
  cl-murmurhash
  split-sequence
  uuid
  local-time
  cl-getx
  bordeaux-threads
  lparallel
  cl-cpus

**Comment by quicklisp** [comment]
Projects are updated automatically. There is no need to open an issue to update.
