### ISSUE TITLE
Please add cl-sha1

### ISSUE THREAD

**Issue by zen-wq** [quicklisp/quicklisp-projects#2041]
https://github.com/naryl/sha1

Quicklisp currently has https://github.com/massung/sha1 which uses a `base64` library incompatible with the common `cl-base64` because of package nicknames.

**Comment by quicklisp** [comment]
That's not a good enough reason to switch. Consider asking massung to use a library you prefer, or ask naryl to use a name that can also be added to Quicklisp. Simply making the change could cause compatibility issues of its own.

**Comment by charJe** [comment]
He has already been asked and refused claiming that that sha1 is just for his personal use, so he is going to use his own personal base64 library. The author of cl-base64 is unresponsive and thus will note remove the conflicting `base64` nickname. The solution here is to just use ironclad if you need sha1.

**Comment by zen-wq** [comment]
System renamed. IMO it makes no sense to rename the package too because they provide the same functions and can't be loaded into the same system because of `base64` conflict anyway.

**Comment by zen-wq** [comment]
Also, removing the nickname from `cl-base64` would also cause compatibility issues. So, I guess this is the only way.

**Comment by dnaeon** [comment]
Considering the presence of `ironclad` doesn't this make this `sha1` library redundant?

**Comment by zen-wq** [comment]
Considering every single dependency on `ironclad` I saw only uses it for md5 and sha1 (I know I haven't seen ALL of them) it makes about 95% of `ironclad` redundant for most purposes.

**Comment by charJe** [comment]
I was under the impression that quicklisp-projects didn't do auditing, and thus accepts redundant projects.
