### ISSUE TITLE
Please add the OMGlib library

### ISSUE THREAD

**Issue by hemml** [quicklisp/quicklisp-projects#2052]
The library is available from https://github.com/hemml/OMGlib
It uses the JSCL as a submodule, so use `git clone --recursive https://github.com/hemml/OMGlib.git` to get it.

**Comment by quicklisp** [comment]
A submodule relationship like this is not ideal. It would be better to not include it and simply list it as a dependency.

**Comment by hemml** [comment]
Unfortunately, JSCL is not ASDF-ed yet. This is a compiller and runs both in the CL and JS environments, so it is not so easy to ASDF it (I have tried). If QL cannot fetch src with submodules, I can pull the specific version of JSCL and just include it as a subdirectory, without a git reference.

**Comment by quicklisp** [comment]
Ah, I see. A submodule will not be an issue in that case.
