### ISSUE TITLE
Cephes.cl: A CFFI wrapper for the Cephes mathmatical library

### ISSUE THREAD

**Issue by Symbolics** [quicklisp/quicklisp-projects#2065]
What's the correct way to add a project that is a CFFI wrapper around a library?

In this case, I'd like to submit [cephes.cl](https://github.com/Lisp-Stat/cephes.cl), a wrapper for the SciPy version of the Cephes Mathematical Library. To use it, the included C library needs to be compiled for each OS/Platform. Whilst a compiled of the original Cephes library is available on some Linux platforms, the enhanced version from SciPy is not and must be built. It should be a matter of just adding a target to the makefile and setting the optimisation and linker options. I.e. the code itself should build everywhere.

If I submit this as is, the build will fail because `libmd` won't be found. What's the best way to proceed?

**Comment by quicklisp** [comment]
Sorry - if it has a "complicated" step to build and install prerequisite libraries it's difficult for me to include. I don't mind if it's a command or two in a package manager, but fetching and building stuff manually is generally a no go.

**Comment by Symbolics** [comment]
The C source is included in the Cephes.cl repository. The user has to build it though, since the mathematical library will be specific to each platform. On my Windows machine the build step is: `cd scipy-cephes && make libmd.dll`.

**Comment by digikar99** [comment]
I've been using `uiop:run-program` to call the appropriate build commands while compiling the project, and similar appropriate commands to load the foreign library. I'm not sure if this is a recommendable way, but I have been using it in another library for ease-of-end-user-usage.

**Comment by Symbolics** [comment]
@digikar99, thanks. I looked at a few way to do this, and in the end your suggestion seemed to be the best one. Cephes will now call out to build automatically on Unix (and Linux) and MS Windows. I don't have a Mac to try this on, but it should be simple to build there too, once the right compiler/linker flags are known.

@xach, the latest commit is good to go.
