### ISSUE TITLE
Please add quick-patch

### ISSUE THREAD

**Issue by tdrhq** [quicklisp/quicklisp-projects#2066]
repo: https://github.com/tdrhq/quick-patch/
Description: Easily override quicklisp projects without using git submodules (also while you're at it, confirm for me that there's no in-built way to do something like this in Quicklisp :) )

**Comment by quicklisp** [comment]
Have you looked at qlot? It seems to do something similar.

**Comment by tdrhq** [comment]
@quicklisp Oh thanks, that indeed looks like it does things better and more thoroughly, might give it a go today

**Comment by quicklisp** [comment]
Do you still want me to add this library?

**Comment by tdrhq** [comment]
@quicklisp Yes please! I do want to switch to qlot, but quick-patch is a quick overriding library at the moment without any big infrastructure changes
