### ISSUE TITLE
Please add cffi-size-t

### ISSUE THREAD

**Issue by JolifantoBambla** [quicklisp/quicklisp-projects#2068]
Please add [cffi-size-t](https://github.com/JolifantoBambla/cffi-size-t).
I know this is going in the NPM direction of having tons of tiny packages, but I really don't want to define a `size_t` type anymore :sweat_smile:

**Comment by Hexstream** [comment]
Don't worry, [I spam microlibraries all the time](https://www.hexstreamsoft.com/libraries/), it's really great! 😂

Don't shy away from best practices, embrace them! 💪

**Comment by JolifantoBambla** [comment]
I missed that cffi has a `size_t` type now. Closing this.

See https://github.com/JolifantoBambla/cffi-size-t/issues/1#issue-969365633

**Comment by borodust** [comment]
Wasn't fast enough in the repo.

Join us at `#lispgames` at irc://libera.chat or `#lisp-gamedev` in [Lisp](https://discord.gg/hhk46CE) discord server to share ideas and to discuss anything lisp gamedev related! :)

**Comment by JolifantoBambla** [comment]
@borodust cool! Thanks, I will! :)
