### ISSUE TITLE
Please Add cl-yxorp

### ISSUE THREAD

**Issue by charJe** [quicklisp/quicklisp-projects#2076]
Reverse proxy server that can be use on it's own or as part of another project. The selling point is that the configuration is done in common lisp and thus is powerful and easy to read and write.

https://github.com/charJe/cl-yxorp

**Comment by quicklisp** [comment]
Failure log here: http://report.quicklisp.org/2021-08-22/failure-report/cl-yxorp.html

**Comment by charJe** [comment]
It should be fixed now. It is interesting that it doesn't seem to happen with sbcl 2.1.6, but obviously `coerce` is more apropriet than `str:concat`.
