### ISSUE TITLE
Please add compiler-macro-notes

### ISSUE THREAD

**Issue by digikar99** [quicklisp/quicklisp-projects#2080]
Please fetch from the releases: https://github.com/digikar99/compiler-macro-notes/releases

compiler-macro-notes provides two conditions `note` and `optimization-failure-note` and a couple of utilities for using these in macros and compiler-macros.

**Comment by quicklisp** [comment]
I'm happy to use the latest release, but the repo has only tags right now, and no releases.

**Comment by digikar99** [comment]
TIL: Tags and Releases are programmatically dissimilar even though, tags are visually shown under releases.

> I'm happy to use the latest release, but the repo has only tags right now, and no releases.

Would be glad if you could fetch the tags instead (assuming that's possible)! Thanks!
