### ISSUE TITLE
Move location of funds?

### ISSUE THREAD

**Issue by charJe** [quicklisp/quicklisp-projects#2082]
I wanted to add some functionallity to this library, but the repository seems to have shut down, and the author doesn't seem to be active. I started hosting it here https://github.com/charJe/funds.

I asked about it on reddit: https://www.reddit.com/r/Common_Lisp/comments/pihau5/functional_data_structures/. I thought I checked quicklisp, but I guess it is already here.

**Comment by charJe** [comment]
It appears that even though there is an issue for funds: https://github.com/quicklisp/quicklisp-projects/issues/96https://github.com/quicklisp/quicklisp-projects/issues/96. It is not available in the current quicklisp.

**Comment by quicklisp** [comment]
Failure log here: http://report.quicklisp.org/2021-09-22/failure-report/funds.html
