### ISSUE TITLE
Please add alexandria-plus

### ISSUE THREAD

**Issue by Symbolics** [quicklisp/quicklisp-projects#2083]
[Alexandria-plus](https://github.com/Symbolics/alexandria-plus) is a slightly less conservative set of utilities, similar in spirit to Alexandria.

**Comment by charJe** [comment]
You should not suggest people to :use these libraries

**Comment by quicklisp** [comment]
@charJe Please don't use Quicklisp issues to give advice like this.

**Comment by quicklisp** [comment]
@Symbolics I find the name confusing since there is no formal relationship with alexandria. Would you consider a different name?

**Comment by Symbolics** [comment]
Well, although there isn't (yet) a formal relationship between the projects they are, by design, philosophically and logistically very similar. Even to the point of using the same filesystem layout, e.g. p/a-list functions reside in `lists.lisp`. Conceptually, it's just a bit less conservative. For example Alexandria defines a type `proper-list`, but not a type for `alist` nor `plist`. It may one day, but it might be a long time, and this lib is for folks who need a bit more, now, and don't want to reinvent the wheel.

I thought about calling it UTSBIABA (Utilities That Should be in Alexandria But Aren't), but in the end figured alexandria+ was probably a better choice.

**Comment by quicklisp** [comment]
Many people write utility libraries that fit their needs and preferences, but nobody yet has given one a name that's almost identical to an existing, very popular utility library, even though there is no real connection. There are things like serapeum or rutils and many other things like that.

**Comment by Symbolics** [comment]
To my knowledge, no one has written one this close in spirit to Alexandria. This library is meant to provide 'just enough' beyond Alexandria to be useful in a greater number of use cases. What sort of confusion do you think this name would cause?

**Comment by quicklisp** [comment]
I think the name gives the impression that it is part of the Alexandria project.

**Comment by Symbolics** [comment]
I'm open to alternatives that make sense, but don't have any. I want to name to give the impression that the lib is a small addition to Alexandria, written in the same spirit. Do you have a suggestion?
