### ISSUE TITLE
Please add chain

### ISSUE THREAD

**Issue by Aksej** [quicklisp/quicklisp-projects#2102]
[https://gitlab.com/Aksej/chain](https://gitlab.com/Aksej/chain)
License: BSD-3

I am the author of the package.

Contains two chaining/piping macros, one just doing that, the other `setf`ing its first argument.

**Comment by xach** [comment]
Where is it?

**Comment by Aksej** [comment]
Sorry, misunderstood the link syntax, I've corrected that now. It's at [https://gitlab.com/Aksej/chain](https://gitlab.com/Aksej/chain)
