### ISSUE TITLE
Please add trivial-package-locks

### ISSUE THREAD

**Issue by yitzchak** [quicklisp/quicklisp-projects#2110]
A standard interface to the various package lock implementations of Common Lisp. 

Author: Tarn W. Burton
License: MIT
Homepage: https://github.com/yitzchak/trivial-package-locks
Sources: https://github.com/yitzchak/trivial-package-locks.git

**Comment by quicklisp** [comment]
Failure log here: http://report.quicklisp.org/2021-12-29/failure-report/trivial-package-locks.html

**Comment by yitzchak** [comment]
Should be fixed.
