### ISSUE TITLE
Please add cl-tar

### ISSUE THREAD

**Issue by daewok** [quicklisp/quicklisp-projects#2114]
A high level interface for tar archives, including extraction and creation

Author: Eric Timmons
License: MIT
Sources: https://gitlab.common-lisp.net/cl-tar/cl-tar
Homepage: https://common-lisp.net/project/cl-tar/

Please pull from Gitlab releases.

Requires cl-tar-file #2113.

On Windows, the `tar/create` system requires https://github.com/osicat/osicat/pull/57. But that's likely a small enough audience that it's not worth waiting for it to be merged.

Please blacklist the `tar-cli` and `tar-cli-asdf` systems for the time being. They have some dependencies that are not ready for Quicklisp yet.

**Comment by quicklisp** [comment]
Failure log here: http://report.quicklisp.org/2022-01-29/failure-report/cl-tar.html

**Comment by daewok** [comment]
Thanks, mostly fixed. `tar/simple-create` and `tar/simple-create-test` were accidentally committed and have been removed.

It'd be great if you could just blacklist `tar-cli` and `tar-cli-asdf`. I use them internally to build an executable, but they have dependencies that are not ready for Quicklisp yet.
