### ISSUE TITLE
Please add clop

### ISSUE THREAD

**Issue by sheepduke** [quicklisp/quicklisp-projects#2117]
Tom’s Obvious Minimal Language (TOML) is a human friendly configuration file format. This library implements a parser (decoder) for it.

Clop strictly follows TOML 1.0 specification and is fully compatible with it. It passes all 296 tests defined in BurntSushi/toml-test.

Release v1.0.0 download page:
https://github.com/sheepduke/clop/releases/tag/v1.0.0

Home page:
https://github.com/sheepduke/clop

**Comment by xach** [comment]
There aren't any releases: https://github.com/sheepduke/clop/releases

Do you want to make releases, or should I track the latest git master? Or something else?

**Comment by phoe** [comment]
There's a v1.0.0 tag at https://github.com/sheepduke/clop/tags - I assume that's what was meant.

**Comment by xach** [comment]
A tag is not a release, and using the latest tag isn't always what's desired either. I would prefer feedback from the original author instead of guesses and assumptions.

**Comment by sheepduke** [comment]
Sorry for the confusion. I *thought* they were the same thing, but actually they are not.

I have created a release and will use this feature in the future. Please use releases.

**Comment by sheepduke** [comment]
P.S. Please note that I edited my last comment because I changed my mind...Please view it on GitHub for latest information.

**Comment by xach** [comment]
- It's inconvenient to use a static tag (because then when you make updates, I have to do work to point to a new tag)
- It's convenient to use the latest tag, whatever it is, but sometimes the author may want a tag that isn't a release
- It's convenient to use to use the latest release, in the github release sense

Do you want me to use the latest tag?

**Comment by sheepduke** [comment]
Thanks for elaboration. I would like to use the **latest tag**.
