### ISSUE TITLE
Please add `cl-wol` - Wake On LAN (WoL) system for Common Lisp

### ISSUE THREAD

**Issue by dnaeon** [quicklisp/quicklisp-projects#2126]
Hey there,

Please add [cl-wol](https://github.com/dnaeon/cl-wol), which is a Common Lisp for Wake On LAN (WoL).

Note, that the `cl-wol.cli` system requires a recent version of [clingon](https://github.com/dnaeon/clingon).

Thanks!

**Comment by phoe** [comment]
Looks like clingon is already available on QL, so it should be 
auto-updated the next time Quicklisp updates its dists.
