### ISSUE TITLE
Please add MK:DEFSYSTEM to quicklisp.

### ISSUE THREAD

**Issue by marcoxa** [quicklisp/quicklisp-projects#2135]
Hi

the repository is at: https://gitlab.common-lisp.net/mantoniotti/mk-defsystem

There may be an issue with ASDF not liking a STYLE-WARNING (using DEFPACKAGE to modify the package).  Let me know if it is a show stopper.

All the best

Marco

**Comment by phoe** [comment]
> using DEFPACKAGE to modify the package

This actually invokes undefined behavior, as per standard Common Lisp; have you considered using `UIOP:DEFINE-PACKAGE` which explicitly defines the behavior that occurs when a package is redefined?

**Comment by phoe** [comment]
[CLHS Macro DEFPACKAGE](http://clhs.lisp.se/Body/m_defpkg.htm):

> If the new definition is at variance with the current state of that [package](http://clhs.lisp.se/Body/26_glo_p.htm#package), the consequences are undefined; an implementation might choose to modify the existing [package](http://clhs.lisp.se/Body/26_glo_p.htm#package) to reflect the new definition.

**Comment by marcoxa** [comment]
Ok.  Which implementatons do not work in the luser-expected way?

**Comment by marcoxa** [comment]
BTW.  I think I found the old time kruft that cause *two* defpackage forms to be evaluated in SBCL.

Hold your horses!

**Comment by marcoxa** [comment]
Hi

I just unravel a self inflicted merge mess :)  I was about to check what happens with ABCL.

I eliminated DEFPACKAGE altogether and now SBCL only makes noises about some strange assignment.

Stay tuned.
