### ISSUE TITLE
Please add generalized-reference

### ISSUE THREAD

**Issue by thephoeron** [quicklisp/quicklisp-projects#2146]
Extensible library for generalized reference over hierarchical data structures by pairwise reduction of place identifiers such as name strings, symbol, index, etc.

Currently supports arbitrary structures of data including symbol-values by package, symbol p-lists, hash-tables, p-lists, a-lists, vectors, arrays, proper lists, CLOS objects and slots, SERIES objects, and pathname components (so that filesystems can be navigated like any other data-type).

Available at https://github.com/thephoeron/generalized-reference

**Comment by quicklisp** [comment]
Failure log here: http://report.quicklisp.org/2022-03-28/failure-report/generalized-reference.html

**Comment by thephoeron** [comment]
Fixed.
