### ISSUE TITLE
Please add extensible-compound-types

### ISSUE THREAD

**Issue by digikar99** [quicklisp/quicklisp-projects#2155]
Please fetch from the master branch at https://github.com/digikar99/extensible-compound-types

The system provides a shadowing-cl package that allows the definition of user-defined compound-types.  Built-in compound types provided by ANSI CL include (VECTOR &OPTIONAL ELEMENT-TYPE LENGTH) or (INTEGER &OPTIONAL LOWER-LIMIT UPPER-LIMIT). With this system, can define types such as (EQUALP OBJECT) type, or (TYPE= TYPE), or (PAIR TYPE-1 TYPE-2) type, or (CUSTOM-ARRAY ELEMENT-TYPE DIMENSIONS).

**Comment by quicklisp** [comment]
Failure log here: http://report.quicklisp.org/2022-06-09/failure-report/extensible-compound-types.html

**Comment by digikar99** [comment]
I made the fix and tested it locally. Could you please recheck?

**Comment by digikar99** [comment]
Please avoid adding extensible-compound-types. I'm abandoning it in favour of peltadot.
