### ISSUE TITLE
Change LTK source to active repo

### ISSUE THREAD

**Issue by ghollisjr** [quicklisp/quicklisp-projects#2156]
Due to [Peter Herth: LTK](https://github.com/herth/ltk) going stale, and after attempting to contact Peter via email to no avail, the suggestion was made in [PR #14](https://github.com/herth/ltk/pull/14) to move Quicklisp's reference LTK repo to an actively maintained repository.  I contacted Luís Oliveira about adding LTK to Sharplispers and he suggested that it would be preferable to use Sharplispers as a last resort if someone is still willing to maintain the repo, so I suggest using mine:

https://github.com/ghollisjr/ltk

**Comment by cage2** [comment]
Hi!

First i have to say that i am that i am the maintainer of nodgui, a fork of LTK.

So said, as seems that you (and other people too) wants to keeps working on this library may i invite you to take a look at  [nodgui](https://notabug.org/cage/nodgui) I think would be good not to divide our energies in different but most overlapping projects and i think nodgui has some advantages over LTK, even if of course my point of view is biased ;-).

Bye!
C.

**Comment by vindarel** [comment]
Hey, shall we avoid the non-future proof error to move the repo to an individual repository? If not sharplispers, I suggest https://github.com/lisp-maintainers I would give you plain administrator rights for Ltk, if you step up as a maintainer you'll be able to do whatever you want (I don't aim at being a developer myself). This goes along those lines:

> Plan for project succession by hosting projects in a shared org instead of in your personal namespace.

https://www.timmons.dev/posts/cl-community-norms.html

**Comment by cage2** [comment]
Hi!

FWIW i am positive to move my fork's fork in an organization or where is more convenient for other people to work on the code and keep it in good shape! :-)

Bye!
C.

**Comment by Hexstream** [comment]
> Hey, shall we avoid the non-future proof error to move the repo to an individual repository?

That seems like a fairly novel and arbitrary guideline to me.

**Comment by ghollisjr** [comment]
* nodgui: This looks like a nice GUI library but I am not familiar with it.  I do like the idea of keeping LTK as a kind of Tkinter equivalent for Lisp, something you can use if you are already familiar with Tk without learning another API built on top of it.  Does nodgui contain LTK as a strict subset or has the API been modified?
* I like the idea of community repos, but there are definite pros and cons, and the problem of future-proofing seems to already be solved by having Quicklisp move its source repo whenever a repo goes stale.  How many people are interested in maintaining LTK?  Is lisp-maintainers an active group?
* If nodgui does contain LTK as a strict subset, then it would make sense to move LTK to a community repo for the purpose of using it as a stable core library that more high-level APIs like nodgui would be built on top of.  On the other hand, if LTK is basically a legacy library that isn't widely used and would have few active contributors then I would say the simplicity of a single user's repo would work fine.

Any thoughts on these ideas?

**Comment by cage2** [comment]
On Sat, Apr 09, 2022 at 09:34:22PM -0700, you wrote:

Hi!

> * nodgui: This looks like a nice GUI library but I am not familiar with it.

Thanks! :)

> I do like  the idea of keeping  LTK as a kind  of Tkinter equivalent
> for Lisp, something you can use  if you are already familiar with Tk
> without  learning another  API  built  on top  of  it.  Does  nodgui
> contain LTK as a strict subset or has the API been modified?

The library started  as a fork of  LTK and mostly of  the code remains
the same even if  has been refactored a lot.  But the  API is, no more
compatible even if  the changes to port from LTK  should be simple, an
excellent example can be found here:

https://peterlane.netlify.app/ltk-plotchart/

Nodgui fixed  some bugs that LTK  suffers and should work  (i tested it
some times  ago) with ECL.  And  offers more widgets, some  from tklib
too. Moreover is  has experimental support for  multithread programs, i
mean multiple  threads can  concurrently update  the GUI,  this feature
unfortunately does not works with CCL, though. :(

> * If nodgui does contain LTK as  a strict subset, then it would make
>sense to move LTK to a community  repo for the purpose of using it as
>a stable core library that more  high-level APIs like nodgui would be
>built on  top of.  On  the other hand, if  LTK is basically  a legacy
>library that isn't widely used

I still think LTK is the best choice if you need a GUI library that is
simple to program,  other library seems to me more  complex to use and
things like ClOG are  wonderful for a website (i plan  to use it!) but
you have to bring  an entire browser for the GUI and  this to me would
be  a waste  of  computational  (and energy  resources  for a  desktop
program (not to mention the and CO2 produced!).

Bye!
C.

**Comment by vindarel** [comment]
>  Is lisp-maintainers an active group?

Not really/a little. Some other guys liked the idea so we created those repos there. We don't work together as a real active group, but having those projects there helped communication and collaboration, IMO. We are active lispers, we use these projects, Some of those projects were updated this year. 

Anyways, I shared my proposal, now as you wish. Thanks for maintaining Ltk.

@cage2 

> FWIW i am positive to move my fork's repository in an organization or where is more convenient for other people to work on the code and keep it in good shape! :-)

If you think lisp-maintainers is a good place, we can absolutely do it :)

**Comment by ghollisjr** [comment]
Thanks everyone for the feedback, so far I'm thinking:

* For now, I could host the LTK repo from my user account.
* I'd like to take a look at nodgui in closer detail and see how similar the LTK API is and see which bugs have been fixed in nodgui.
* I'd like to try getting LTK patched up to the point where it can be a suitably stable foundation for libraries like nodgui, and if there's interest for using it as a base library then LTK could be moved to a community repo like lisp-maintainers and used as a stable base library for others like nodgui.  This way there can be a clean separation between the Tk-specific software and more convenient APIs built on top of Tk.

**Comment by cage2** [comment]
Hi @vindarel !

> @cage2
> 
> > FWIW i am positive to move my fork's repository in an organization or where is more convenient for other people to work on the code and keep it in good shape! :-)
> 
> If you think lisp-maintainers is a good place, we can absolutely do it :)

To be honest i have personal reasons for not using github for my repositories, but if other people would show interest improving the project i try to maintain (and they prefer to host the project's repo on lisp-maintainers), i would happily move the repository and continue the develop there. 

Bye!
C.

**Comment by cage2** [comment]
Hi @ghollisjr !

> * I'd like to try getting LTK patched up to the point where it can be a suitably stable foundation for libraries like nodgui,

Now i am realizing that i gave before the false impression that the API of nodgui diverged a lot from the one of LTK, in fact i believe the API is more than 90% the same, sorry for the misunderstanding.

Again the excellent work from this person can give some useful examples:

https://peterlane.netlify.app/ltk-examples/

Bye!
C.

**Comment by ghollisjr** [comment]
I recently was able to contact Peter Herth, and it seems he is still willing and able to maintain LTK but didn't get around to responding to the emails I had sent until now, so I'll close this issue.
