### ISSUE TITLE
Please add easter-gauss

### ISSUE THREAD

**Issue by cage2** [quicklisp/quicklisp-projects#2164]
This is a tiny library to perform the calculation of the Easter date.

https://notabug.org/cage/easter-gauss

Please consider including in quicklisp.

Bye!
C.

**Comment by Hexstream** [comment]
I'm getting on 404 for that page.

**Comment by cage2** [comment]
Hi!

> I'm getting a 404 for that page.

Maybe the problem was temporary, it is works to me now.

Bye!
C.

**Comment by Hexstream** [comment]
Still 404 here, and I also cannot find the project in [your list of repositories](https://notabug.org/cage).

Have you made sure the project is public? Have you made sure you are logged out while trying to view the project?

**Comment by cage2** [comment]
Hi @Hexstream 

I am so sorry! My fault, the repository was private indeed! 😓😓

I made it public now, thank you very much for checking!

Bye!
C.
