### ISSUE TITLE
Please add Github-API-CL

### ISSUE THREAD

**Issue by ccqpein** [quicklisp/quicklisp-projects#2166]
[Github-API-CL](https://github.com/ccqpein/Github-API-CL) is a wrapper rest api sdk of github rest API v3. 

All dependencies can quickload via quicklisp. Hopefully it can add to quicklisp for easy to loading.

Thank you!

**Comment by quicklisp** [comment]
Failure log here: http://report.quicklisp.org/2022-06-09/failure-report/github-api-cl.html

**Comment by ccqpein** [comment]
@quicklisp Sorry about this failure. I fix the `(asdf:compile-system github-api-cl)` in my local. Hope it also works on your side.
