### ISSUE TITLE
Please add ORG.MELUSINA.RASHELL

### ISSUE THREAD

**Issue by foretspaisibles** [quicklisp/quicklisp-projects#2174]
The Rashell package defines primitives which combine ease of use with the ability to write maintainable and resilient programs leveraging the full power of UNIX. These primitives implements common patterns to interact with UNIX utilities as subprocesses. These patterns usually yield a string or a sequence of lines, they will also adequately report error conditions on subprocesses.

Source: [git@github.com](mailto:git@github.com):melusina-org/cl-rashell.git

Make documentation: development/makedoc
Testsuite: development/testsuite

**Comment by quicklisp** [comment]
Failure log here: http://report.quicklisp.org/2022-06-09/failure-report/cl-rashell.html

**Comment by foretspaisibles** [comment]
Thanks! Is this building on a windows machine? How can I advertise in ASDF that windows is not supported.

For the error in the testsuite, missing package ORG.MELUSINA.CONFIDENCE, this should be addressed by #2172.

**Comment by quicklisp** [comment]
sb-posix is not part of the default sbcl system on any platform. You have to explicitly depend on it.

**Comment by foretspaisibles** [comment]
Ah, thank you for the update. Let's see if https://github.com/melusina-org/cl-rashell/commit/e44223848018520026be46ddd68b74bd12cb5877 fixes it!

**Comment by foretspaisibles** [comment]
Thanks!
