### ISSUE TITLE
Please add abstract-arrays

### ISSUE THREAD

**Issue by digikar99** [quicklisp/quicklisp-projects#2175]
Please retrieve using the tags: https://github.com/digikar99/abstract-arrays

This library provides an abstract-array class and an abstract-array-class metaclass, which can then be used for creating concrete arrays like [dense-arrays](https://github.com/digikar99/dense-arrays) or sparse-arrays (yet to be done)! It also provides type specifiers for the specification of element-type and rank (and dimensions if you are using [extensible-compound-types](https://github.com/digikar99/extensible-compound-types]), albeit using satisfies type hackery.

**Comment by quicklisp** [comment]
Failure log here: http://report.quicklisp.org/2022-06-09/failure-report/abstract-arrays.html

**Comment by digikar99** [comment]
Added the description and made a small fix; could you please check if the new version v0.1.1 builds correctly?
