### ISSUE TITLE
please add hunchentoot without ssl

### ISSUE THREAD

**Issue by oldk1331** [quicklisp/quicklisp-projects#2182]
https://edicl.github.io/hunchentoot/ says:

> Note: You can compile Hunchentoot without SSL support - and thus without the need to have CL+SSL - if you add :HUNCHENTOOT-NO-SSL to[ *FEATURES*](http://www.lispworks.com/documentation/HyperSpec/Body/v_featur.htm) before you compile it.

I wonder if we can provide something like "hunchentoo-no-ssl" that provides a HTTP only server.  This can be useful for people doesn't need ssl functionality -- FFI loading ssl library can be problematic on some exotic systems.

**Comment by samuel-hunter** [comment]
```lisp
* (ql:quickload :hunchentoot)
* (find-package :cl+ssl)
#<PACKAGE "CL+SSL">
```

```lisp
* (push :hunchentoot-no-ssl *features*)
* (ql:quickload :hunchentoot)
* (find-package :cl+ssl)
NIL
```

AFAIK, Quicklisp only fetches source dependencies, nothing pre-compiled. I'm not sure what role Quicklisp needs to play to provide both, when a lisp system can already provide the feature before quickloading or requiring a system.

**Comment by oldk1331** [comment]
Thanks for your input.

Sorry for not trying this earlier because I thought quicklisp not only controls source dependencies but also build/runtime dependencies.

When setting `(push :hunchentoot-no-ssl *features*)`, quicklisp still downloads and installs dependencies like "cl+ssl", but `(ql:quickload :hunchentoot)` will not load it.

So my original problem is solved.  I can close this issue now.
