### ISSUE TITLE
XMLS library update

### ISSUE THREAD

**Issue by rpgoldman** [quicklisp/quicklisp-projects#2185]
I just published XMLS 3.2.0

The git repo for the project hasn't changed (but you might want to use the `release` branch instead of `master`).

The https should be updated to https https://common-lisp.net/project/xmls/xmls-3.2.0.tar.gz

Thanks!

**Comment by quicklisp** [comment]
Ok, done, and now using the release branch.

**Comment by rpgoldman** [comment]
Thank you very much!
