### ISSUE TITLE
Quicklisp has two distributions of the same SHA1 library

### ISSUE THREAD

**Issue by samuel-hunter** [quicklisp/quicklisp-projects#2190]
- **sha1** - homepage https://github.com/massung/sha1 - from 2018 issue https://github.com/quicklisp/quicklisp-projects/issues/1521
- **cl-sha1** - homepage https://github.com/naryl/sha1 - from 2021 issue https://github.com/quicklisp/quicklisp-projects/issues/2041

`cl-sha1` is a fork of Massung's `sha1` that replaced the dependency `base64` with system-conflicting library, `cl-base64`, so that projects who also use the latter, or its 56 dependents (as of July 2022), or any dependents thereof, could also use `cl-sha1`.

Between then and now, the original `sha1` system removed `base64` as a dependency. With the original problem resolved, is it necessary to continue keeping two versions of the same code?

**Comment by quicklisp** [comment]
I don't generally remove projects for duplication of functionality.
