### ISSUE TITLE
Please add JSON-LIB

### ISSUE THREAD

**Issue by alexnygren** [quicklisp/quicklisp-projects#2195]
JSON-LIB is a quick and simple to use JSON parser and encoder for Common Lisp that strives to be quick and mainly compliant with the JSON test suite (with a few exceptions).

Code and Documentataion: https://github.com/KinaKnowledge/json-lib

Author: Alex Nygren

**Comment by quicklisp** [comment]
Failure log here: http://report.quicklisp.org/2022-09-26/failure-report/json-lib.html

**Comment by alexnygren** [comment]
Issue fixed and tested
