### ISSUE TITLE
Please add cl-djula-tailwind

### ISSUE THREAD

**Issue by rajasegar** [quicklisp/quicklisp-projects#2201]
`cl-djula-tailwind` is a package to use Tailwind classes in Djula templates without any overhead of JavaScript or Node.js tooling. It is a complete rewrite of Tailwind classes from scratch in Common Lisp using `djula` , `cl-css` and `cl-minify-css`
Project page: https://github.com/rajasegar/cl-djula-tailwind

**Comment by quicklisp** [comment]
Failure log here: http://report.quicklisp.org/2022-09-26/failure-report/cl-djula-tailwind.html

**Comment by rajasegar** [comment]
Fixed it  by adding the description
