### ISSUE TITLE
What happened to conduit-packages?

### ISSUE THREAD

**Issue by snunez1** [quicklisp/quicklisp-projects#2209]
The current [releases page](https://www.quicklisp.org/beta/releases.html) lists `conduit-packages-20220331-git` as an available system, and #1935 suggests it was added in 2020.  Yet, it doesn't appear to be part of Quicklisp any longer.  I just did a QL update, still no success.  It does appear in https://github.com/quicklisp/quicklisp-projects/tree/master/projects, but when I try to load it:
```
System "conduit-packages" not found
   [Condition of type QUICKLISP-CLIENT:SYSTEM-NOT-FOUND]
```
It's not appearing in my local Quicklisp directory, which is probably the reason for the error.  It *is* in systems.txt.  Perhaps connectivity or a wrong URL?

**Comment by phoe** [comment]
(ql:quickload :org.tfeb.conduit-packages)

**Comment by snunez1** [comment]
Aarrrrrrg. I hate package names like that.
