### ISSUE TITLE
Please add more-cffi

### ISSUE THREAD

**Issue by Hectarea1996** [quicklisp/quicklisp-projects#2211]
It is available from here: https://github.com/Hectarea1996/more-cffi

It has some macros to make easier the wrapping and documenting of C bindings.

**Comment by snunez1** [comment]
Looks interesting.  Why didn't you add this to the CFFI project?

**Comment by Hectarea1996** [comment]
I think I prefer to keep them separately. Not everybody would want to use
my project because it makes you to work in a very specific way. Also, I've
just started to program in Common Lisp (less than 1 year using it) and
doing this kind of things is a bit overwhelming for me 😅.

Anyway, thanks for considering adding my project to Quicklisp!
