### ISSUE TITLE
Please add cl-cmark

### ISSUE THREAD

**Issue by HiPhish** [quicklisp/quicklisp-projects#2230]
Repositories:

- Main repo on GitLab: https://gitlab.com/HiPhish/cl-cmark
- Mirror on GitHub: https://github.com/hiphish/cl-cmark

This library depends on the native [libcmark](https://github.com/commonmark/cmark) library, the official reference implementation of CommonMark. I intend to provide versioned releases rather than just following the `master` branch, so if there is anything I can do to make the update process automatic please let me know.

I have not yet commited to a stable release, so please let me know if there is anything missing for a proper inclusion in Quicklisp.

**Comment by quicklisp** [comment]
Is there an easy way to install libcmark on debian?

**Comment by HiPhish** [comment]
On Monday, November 14, 2022 8:29:20 PM CET Zach Beane wrote:
> Is there an easy way to install libcmark on debian?

I haven't tried it, but cmark is in the Debian packages:

https://packages.debian.org/bullseye/cmark
https://packages.debian.org/bullseye/libcmark0.29.0
https://packages.debian.org/bullseye/libcmark-dev

**Comment by quicklisp** [comment]
I'm using the latest debian packages, but I still get an error about being unable to load any of the alternatives. I don't quite understand the issue yet.

**Comment by HiPhish** [comment]
Is the problem with the C library in Debian itself or with my Lisp bindings?

**Comment by quicklisp** [comment]
Ok, it turns out to work if I make a symlink for libcmark.so.0 to my
versioned so file. The package only installs libcmark.so.

**Comment by phoe** [comment]
Sounds like https://github.com/HiPhish/cl-cmark/blob/14d63fb0c6a79144d0327851c279a0a4a6c98fbc/src/libcmark/main.lisp#L8 could use a `"libcmark.so"` in addition to the other library names.

**Comment by HiPhish** [comment]
Oops, you are right. The `libcmark` should have been `libcmark.so`. I
have fixed it now and pushed to the current `master`.
