### ISSUE TITLE
Please add cl-bloom-filter

### ISSUE THREAD

**Issue by alangalvino** [quicklisp/quicklisp-projects#2231]
`cl-bloom-filter` is just another Common Lisp bloom filter implementation.

- Author: Alan Gomes Alvino
- License: MIT
- Source: https://github.com/alangalvino/cl-bloom-filter
- Documentation: https://github.com/alangalvino/cl-bloom-filter/blob/main/README.markdown
- Dependencies:
  - Rove (for test only)

**Comment by quicklisp** [comment]
Failure log here: http://report.quicklisp.org/2022-11-02/failure-report/cl-bloom-filter.html
