### ISSUE TITLE
Plese add ADP

### ISSUE THREAD

**Issue by Hectarea1996** [quicklisp/quicklisp-projects#2232]
The source is here: https://github.com/Hectarea1996/adp/tree/main

ADP stands for Add Documentation, Please. It is a tool for literate programming and semi-automatic documentation generation. 

Some features of ADP:
* Headers
* Lists
* Tables
* Images
* API generation
* Cross references
* Code references and code hiding

Also, you can choose between different styles (currently there is only one, but there will be more).

The main system only depends on Alexandria and hyperspec, but styles could have more dependencies.

**Comment by quicklisp** [comment]
Failure log here: http://report.quicklisp.org/2022-11-02/failure-report/adp.html

**Comment by Hectarea1996** [comment]
I'm not getting that error, so I guess it is a dependency error. However, it says that package ql-dist doesn't exist, but it comes with Quicklisp, right? Am I missing something?

**Comment by phoe** [comment]
Projects added to Quicklisp cannot depend on the Quicklisp client itself. The line at https://github.com/Hectarea1996/adp/blob/c94cc06a365b385307fd0c174687ff4dfca6c376/readme.lisp#L42 mentions a symbol from the package `ql-dist` which is not available on the environment that is loading projects being added into Quicklisp. The solution is to remove a reference to the offending package.

**Comment by Hectarea1996** [comment]
I see. I've changed that already. It should be fine now.

**Comment by quicklisp** [comment]
Failure log here: http://report.quicklisp.org/2022-11-03/failure-report/adp.html

**Comment by phoe** [comment]
For adp/doc, it seems that the build ran on stale data - no symbols from `ql-dist` seem present in the repository right now. For adp/html, it seems there's a whole bunch of errors unrelated to this though.

**Comment by Hectarea1996** [comment]
Fixed!
