### ISSUE TITLE
Please add stepster

### ISSUE THREAD

**Issue by walpurgisnatch** [quicklisp/quicklisp-projects#2239]
Stepster is a web scraping library with convenient tools for json parsing.

https://github.com/walpurgisnatch/stepster/tree/main

Thanks.

**Comment by quicklisp** [comment]
Failure log here: http://report.quicklisp.org/2022-11-02/failure-report/stepster.html

**Comment by walpurgisnatch** [comment]
Excuse me. Forgot to merge in main. Fixed now.
