### ISSUE TITLE
Please add py4cl2-cffi

### ISSUE THREAD

**Issue by digikar99** [quicklisp/quicklisp-projects#2249]
Please fetch from the master branch at https://github.com/digikar99/py4cl2-cffi

`py4cl2-cffi` provdes an interface to embedded python through CFFI. It intends to preserve the semantics of `py4cl2`, but being based on function calls instead of IPC `py4cl2-cffi` is upto 50 times faster than `py4cl2`, and also allows for passing array data by reference..

**Comment by cage2** [comment]
On Sun, Dec 25, 2022 at 10:24:00AM -0800, Shubhamkar Ayare wrote:

[...]

> `py4cl2-cffi` provdes an interface to embedded python through CFFI.

Great project, thanks for working on it! 👍

Bye!
C.

**Comment by digikar99** [comment]
It stil requires more work to be at feature parity with py4cl2, hopefully in another month or two. But it should be useable none-the-less!

**Comment by digikar99** [comment]
Please use the github tags instead of fetching the latest commit.
