### ISSUE TITLE
Please add kdtree-jk

### ISSUE THREAD

**Issue by jetmonk** [quicklisp/quicklisp-projects#2250]
Please add https://github.com/jetmonk/kdtree-jk

This is an efficient implementation of KD-trees (N-dimensional log-N spatial search) that uses arrays instead of linked lists to minimize memory overheads.  It is tested on Darwin and Linux x64 SBCL, but is written pure Lisp with no other dependencies, so should work everywhere.

It is MIT-licensed.

A user found it useful (for game development) and requested its addition to quicklisp.

**Comment by quicklisp** [comment]
Failure log here: http://report.quicklisp.org/2023-02-14/failure-report/kdtree-jk.html

**Comment by jetmonk** [comment]
Added :DESCRIPTION fields to kdtree-jk.asd
