### ISSUE TITLE
Please add khazern

### ISSUE THREAD

**Issue by yitzchak** [quicklisp/quicklisp-projects#2259]
Khazern is a portable loop implementation from SICL

Author: Robert Strandh, Tarn W. Burton
License: BSD
Sources: https://github.com/s-expressionists/Khazern.git

**Comment by quicklisp** [comment]
Failure log here: http://report.quicklisp.org/2023-03-22/failure-report/khazern.html

**Comment by yitzchak** [comment]
khazern-environment is used only during SICL boot. It shouldn't be in the Quicklisp system index. Can I get it added to the excluded system list?

**Comment by quicklisp** [comment]
Sure, I will exclude it.
