### ISSUE TITLE
Please add openapi-generator

### ISSUE THREAD

**Issue by kilianmh** [quicklisp/quicklisp-projects#2272]
A client system generator from Openapi specification files.

Author: Kilian M. Haemmerle
License: AGPLv3
Source: https://codeberg.org/kilianmh/openapi-generator.git

If possible, please track the latest Codeberg tag. If not, then the latest commit.

**Comment by quicklisp** [comment]
Failure log here: http://report.quicklisp.org/2023-03-27/failure-report/openapi-generator.html

**Comment by kilianmh** [comment]
This library uses a _symbol_ from `quicklisp`. Is it enough to explicitly depend on `quicklisp` in the `.asd` file or is it not possible for you to build a library that depends on `quicklisp` itself?

**Comment by phoe** [comment]
The latter. The Quicklisp client is not included in the image that builds Quicklisp projects; if you really want to, you can possibly `#+quicklisp` and `(:feature-if :quicklisp)` these as a workaround and then ensure that your system builds cleanly with only ASDF loaded, but I think a better idea would be not to introduce a hard dependency on the Quicklisp client in your code.
