### ISSUE TITLE
LLA has moved, now maintained

### ISSUE THREAD

**Issue by Symbolics** [quicklisp/quicklisp-projects#2276]
New location is:
    https://github.com/Lisp-Stat/lla

Old location:
    https://github.com/tpapp/lla

**Comment by xach** [comment]
I believe this change breaks:

* cl-random http://report.quicklisp.org/2023-03-30/failure-report/cl-random.html#cl-random
* cl-mleb http://report.quicklisp.org/2023-03-30/failure-report/cl-mlep.html#mlep-add

Is this something you can fix with changes to LLA?

**Comment by Symbolics** [comment]
It's an easy fix.  Those systems are using `cl-num-utils`, the 'legacy' version, in their ASDF file and not `num-utils`, the maintained version, so there are package clashes.  I thought we deprecated Tamas' old libraries some time ago?

**Comment by quicklisp** [comment]
I'm not aware of any deprecation. I see a few options:

> Message ID: ***@***.***
> com>
>
* Stop using the new LLA
* Submit bug reports to cl-random and cl-mlep and wait for a response
* Drop cl-random and cl-mlep
* Use a new name for the new LLA if it's not compatible with the old LLA

Maybe there's something else?

**Comment by Symbolics** [comment]
I thought Tamas (or me?) wrote a few years ago about removing those systems in order to continue development in the Lisp-Stat ecosystem.

[cl-random](https://github.com/tpapp/cl-random) is another of Tamas' abandoned libraries, and has been continued in the [distributions ](https://github.com/Lisp-Stat/distributions)system, so it's safe to drop that one.  I'd also suggest dropping cl-num-utils or, if possible, redirect requests for it to num-utils.  We should also drop [cl-slice](https://github.com/tpapp/cl-slice) whilst we're at it to avoid any similar problem in the future; it is now [select](https://github.com/Lisp-Stat/select).

I'll write to the cl-mlep author and let him know about the changes.  That library would be a useful set of examples for Lisp-Stat.

**Comment by Symbolics** [comment]
OK, cl-mlep is now updated, so we should be good to go as above.  FYI, I'll be taking over cl-mlep in the near future.  It probably won't change locations, just adding me as a maintainer.
