### ISSUE TITLE
Please add jzon

### ISSUE THREAD

**Issue by aartaka** [quicklisp/quicklisp-projects#2281]
https://github.com/Zulu-Inuoe/jzon

It's yet another JSON parser for CL, this time focusing on JSON testcases conformance.

I'm not a maintainer, but I'm interested in seeing it on Quicklisp :)

Loading the library causes
```
; caught STYLE-WARNING:
;   Call to FLOAT-FEATURES:BITS-SINGLE-FLOAT could not be inlined because no
;   definition for it was seen prior to its first use.
```
is that critical for the build (float-features is on Quicklisp already)?

**Comment by quicklisp** [comment]
See issue #2256. It will be in the next release.

**Comment by aartaka** [comment]
Ouch :sweat_smile: Closing then!
