### ISSUE TITLE
Please add Webmachine

### ISSUE THREAD

**Issue by foretspaisibles** [quicklisp/quicklisp-projects#2292]
This is a port of Erlang's Webmachine, adding HTTP semantic on top of Hunchentoot. The port is still work in progress but can serve a simple web application (Bootstrap, Parenscript).

Author: Michaël Le Barbier
License: MIT
Source: https://github.com/melusina-org/cl-webmachine

**Comment by quicklisp** [comment]
Failure log here: http://report.quicklisp.org/2023-05-24/failure-report/cl-webmachine.html

**Comment by foretspaisibles** [comment]
I tried to address the issues above, would you give it another try?
