### ISSUE TITLE
Please add reblocks-typeahead

### ISSUE THREAD

**Issue by svetlyak40wt** [quicklisp/quicklisp-projects#2316]
Description: A Reblocks widget implementing typeahead search.
Author: Alexander Artemenko
License: Unlicense
Source: https://github.com/40ants/reblocks-typeahead
Documentation: https://40ants.com/reblocks-typeahead

**Comment by quicklisp** [comment]
Failure log here: http://report.quicklisp.org/2023-06-17/failure-report/reblocks-typeahead.html

**Comment by svetlyak40wt** [comment]
Seems you've removed wrong label, because error is there and dependency is missing.

I've created two issues to include dependencies needed for the example of reblocks-typeahead:

https://github.com/quicklisp/quicklisp-projects/issues/2319
https://github.com/quicklisp/quicklisp-projects/issues/2320
