### ISSUE TITLE
please update the trivial-sanitize repository

### ISSUE THREAD

**Issue by cage2** [quicklisp/quicklisp-projects#2322]
Hi!

I have moved my repository from not a bug to codeberg

old location:

```
https://notabug.org/cage/trivial-sanitize 
```
new location

```
https://codeberg.org/cage/trivial-sanitize
```

I am moving all my repositories to codeberg, i know this will be an inconvenience for quicklisp, my apologize in advance.

I am going to add an issue for each moved repository (this is the first), i hope this way fits fine with your workflow, if not I can add all the changes in a single report.

Bye!
C.

PS: i realized that just a substitution `notabug.org/cage` with `codeberg.org/cage` should do the job

**Comment by quicklisp** [comment]
In this case, a pull request is appropriate. On Jun 20, 2023, at 12:47, cage2 ***@***.***> wrote:﻿
Hi!
I have moved my repository from not a bug to codeberg
old location:
https://notabug.org/cage/trivial-sanitize 

new location
https://codeberg.org/cage/trivial-sanitize

I am moving all my repositories to codeberg, i know this will be an inconvenience for quicklisp, my apologize in advance.
I am going to add an issue for each moved repository (this is the first), i hope this way fits fine with your workflow, if not I can add all the changes in a single report.
Bye!
C.

**Comment by cage2** [comment]
Hi!

> In this case, a pull request is appropriate.

OK! I am going to close the issue and preparing the PR

Bye!
C.
