### ISSUE TITLE
Please add mutils

### ISSUE THREAD

**Issue by mmontone** [quicklisp/quicklisp-projects#2341]
Hello.

mutils is a collection of Common Lisp modules.

https://github.com/mmontone/mutils

Can you add? Thank you!

**Comment by quicklisp** [comment]
Failure log here: http://report.quicklisp.org/2023-07-26/failure-report/mutils.html

**Comment by mmontone** [comment]
I forgot the ASDF system description. Should be good now.

**Comment by mmontone** [comment]
Thanks
