### ISSUE TITLE
Please add cl-transducers

### ISSUE THREAD

**Issue by fosskers** [quicklisp/quicklisp-projects#2351]
Hi there, the source for the library is available here: https://git.sr.ht/~fosskers/cl-transducers

Thank you kindly!

**Comment by snunez1** [comment]
Nice library.  This would be a _lot_ more useful if it had a permissive license (Apache, MIT, BSD).  As it is, many companies disallow anything GNU licensed to be on their premises.

**Comment by quicklisp** [comment]
Hi Steve, it's fine to discuss your license preference with authors, but
please don't do it on these github issues.

**Comment by fosskers** [comment]
I've just released `1.0.0` of the library. It's now in a much better state to appear on QL.

As an aside, it's also now released under the LGPL, which still allows linking in entirely proprietary scenarios.

**Comment by fosskers** [comment]
Added some time ago. Thanks again!
