### ISSUE TITLE
Please add super-loader

### ISSUE THREAD

**Issue by jordan4ibanez** [quicklisp/quicklisp-projects#2359]
Super-loader is a local systems loader for common lisp.

Author: jordan4ibanez
License: GPLV3
Source: https://github.com/jordan4ibanez/super-loader.git

**Comment by quicklisp** [comment]
Failure log here: http://report.quicklisp.org/2023-10-01/failure-report/super-loader.html

**Comment by phoe** [comment]
Systems to be added to Quicklisp cannot depend on the Quicklisp client being present, but https://github.com/jordan4ibanez/super-loader/blob/c5a825d17189e200588b112bc5c7dc9f9ac28c2a/super-loader.lisp#L27 has such a dependency.
