### ISSUE TITLE
Please add cl-naive-ptrees

### ISSUE THREAD

**Issue by Harag** [quicklisp/quicklisp-projects#2379]
I often use plist trees and got tired of reinventing the wheel each  time and created cl-naive-ptrees for easy reuse.

Authors: PJB and Harag
License: MIT
Documentation: https://gitlab.com/naive-x/cl-naive-ptrees/-/blob/main/docs/docs.org
Source: https://gitlab.com/naive-x/cl-naive-ptrees.git

**Comment by Harag** [comment]
Tests depend on cl-naive-tests

**Comment by quicklisp** [comment]
I will never work with PJB again, I don't want to have any association with
him or any of his projects. If he is dropped as a contributor I will
consider it.
