### ISSUE TITLE
Please add Chipi

### ISSUE THREAD

**Issue by mdbergmann** [quicklisp/quicklisp-projects#2430]
A (house) automation tooling in Common Lisp

Author: Manfred Bergmann
License: Apache 2.0
Source: https://github.com/mdbergmann/chipi

**Comment by quicklisp** [comment]
Failure log here: http://report.quicklisp.org/2024-08-04/failure-report/chipi.html

**Comment by mdbergmann** [comment]
Sorry, this is based on a version of a dependency that is not yet available in quicklisp.
Closing for now.
