### ISSUE TITLE
Please update ht-simple-ajax and gtfl

### ISSUE THREAD

**Issue by martin-loetzsch** [quicklisp/quicklisp-projects#256]
Hi,

I updated 
http://martin-loetzsch.de/ht-simple-ajax/
and
http://martin-loetzsch.de/gtfl/

to work with the current version of hunchentoot.

Please update them in the distribution.

Thanks,

Martin

**Comment by quicklisp** [comment]
I can't reach this site any more - are the projects still active?

**Comment by quicklisp** [comment]
Please reopen if this site becomes active again.

**Comment by vindarel** [comment]
FYI the site http://martin-loetzsch.de/gtfl/ and the targ.gz are active. (deleted on https://github.com/quicklisp/quicklisp-projects/commit/f0102515a3607560e8ec5c3105269e3b6effe19d)
