### ISSUE TITLE
request: Common Lisp Music (CLM)

### ISSUE THREAD

**Issue by lindes** [quicklisp/quicklisp-projects#290]
Hi there,

I'd like to be able to load CLM via QuickLisp.  I _think_ it meets the pre-reqs for an easy build (it has [an asd file](https://ccrma.stanford.edu/workshops/linux2001/lectures/6a/clm/clm.asd)...  I'm not familiar enough with QuickLisp or CLM (or even Common Lisp in general) yet to know whether that's all that's needed, but here's hoping.

Info: https://ccrma.stanford.edu/software/clm/
Tar file (as of 2012-03-28): ftp://ccrma-ftp.stanford.edu/pub/Lisp/clm-4.tar.gz

Thanks!
- David

**Comment by jccerrillo** [comment]
Hello,
I've managed to put together a version of CLM that is loadable in Quicklisp, but it only works on ClozureCL for the moment.  I'll try to get it to load in sbcl as well soon.
https://github.com/jccerrillo/clm
