### ISSUE TITLE
Please add virgil and doors to Quicklisp

### ISSUE THREAD

**Issue by ckairaba** [quicklisp/quicklisp-projects#307]
"Virgil is an extensible and high level foreign function interface(FFI)"
https://github.com/Lovesan/virgil
"Doors is a lisper's gateway to Windows. It aims to cover only essential
features of that operating system, such as basic WinAPI, COM and OLE."
https://github.com/Lovesan/doors

**Comment by quicklisp** [comment]
Please reopen individual issues if this is still desired.
