### ISSUE TITLE
Elephant

### ISSUE THREAD

**Issue by eslick** [quicklisp/quicklisp-projects#34]
I'm one of the primary developers of Elephant and would be happy to make it reasonably compatible with Quicklisp.  We have a project to make a pure-lisp solution that is independent of SQLite or Berkeley DB, but that may be a way off.  Is there a reasonable way to package Elephant so it can be downloaded via Quicklisp with a clear warning that some manual configuration is necessary?

**Comment by Likenttt** [comment]
但是最终还是不能通过quicklisp安装
But even now,Elephant cannot be install by quicklisp.
