### ISSUE TITLE
Please add cl-cuda

### ISSUE THREAD

**Issue by takagi** [quicklisp/quicklisp-projects#514]
Cl-cuda is a library to use NVIDIA CUDA in Common Lisp programs.

https://github.com/takagi/cl-cuda

It depends on NVIDIA CUDA which is, you know, a parallel computing platform using GPUs.

**Comment by takagi** [comment]
@quicklisp Now the systems of cl-cuda, `cl-cuda` and `cl-cuda-interop`, have :author, :license and :description options.

**Comment by mpsota** [comment]
@quicklisp Any progress on this ticket? I can confirm that one can build cl-cuda without CUDA enabled graphics card. All I needed under ubuntu is nvidia-cuda-toolkit.

**Comment by quicklisp** [comment]
Cool, it works now, and will be in the next release.
