### ISSUE TITLE
Please add DEFINER

### ISSUE THREAD

**Issue by marcoxa** [quicklisp/quicklisp-projects#578]
The definer library http://common-lisp.net/project/definer/ is a quick hack to add a generalized DEF macro to CL.  Can you please add it to Quicklisp?  The license is BSD and the CVS repository is at

http://common-lisp.net/viewvc/definer/definer/

Thanks

Marco

**Comment by quicklisp** [comment]
Please reopen if appropriate.

**Comment by marcoxa** [comment]
Thanks for the heads up :)

I need to get one day to get all my libraries up to date with the new CLNET
gitlab setup...

I'll re-open when I am ready.

Marco




On Mon, Sep 28, 2015 at 3:13 PM, Zach Beane <notifications@github.com>
wrote:

> Please reopen if appropriate.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/quicklisp/quicklisp-projects/issues/578#issuecomment-143739779>
> .
>



-- 
Marco Antoniotti
Somewhere over the Rainbow
