### ISSUE TITLE
[Meta] Cloning submodules?

### ISSUE THREAD

**Issue by eudoxia0** [quicklisp/quicklisp-projects#685]
This was [an old problem](https://github.com/eudoxia0/clack-errors/issues/2), but I've decided to report it since I'm about to run into it again: Essentially, Quicklisp doesn't clone submodules when cloning Git repositories?

This is rather important for managing Lisp-external dependencies.

**Comment by quicklisp** [comment]
Submodules should work - if you have any problems please let me know in a new issue.
