### ISSUE TITLE
Looking for detailed explanation of everything I need to do to get my library on quicklisp.

### ISSUE THREAD

**Issue by W-Net-AI** [quicklisp/quicklisp-projects#713]
Is there a way to get a detailed explanation of everything I need to do to get my library on quicklisp.  It is still in process now , but if someone could give me a check list of the things I need to be mindful of while I create it. I would appreciate it.

**Comment by quicklisp** [comment]
See http://blog.quicklisp.org/2015/01/getting-library-into-quicklisp.html and http://blog.quicklisp.org/2015/01/some-problems-when-adding-libraries-to.html
