### ISSUE TITLE
Please add cl-webkit2

### ISSUE THREAD

**Issue by AeroNotix** [quicklisp/quicklisp-projects#731]
This project is a cffi wrapper around the gtk WebKit library. This is useful for creating GTK applications which wish to use a webkit window.

Author: @joachifm
URL: https://github.com/joachifm/cl-webkit.git
License: MIT

**Comment by quicklisp** [comment]
This is now building in debian 8 and will be in the next Quicklisp update.

**Comment by AeroNotix** [comment]
:+1:
