### ISSUE TITLE
Please add cl-libssh2

### ISSUE THREAD

**Issue by eudoxia0** [quicklisp/quicklisp-projects#758]
It's a binding to the libssh2 library, and right now the only Common Lisp SSH client library out there. I've tried it and it does seem to work as advertised, at least for connecting and handling `known_hosts`.

https://bitbucket.org/alxchk/cl-libssh2

**Comment by darabi** [comment]
The autthor has moved the repo to https://github.com/alxchk/cl-libssh2.git, the CFFI file with the dot in its name has been renamed, so it builds and works with current SBCL.

Could you please retry?

**Comment by quicklisp** [comment]
This is in Quicklisp now.
