### ISSUE TITLE
Please add capitaomorte/snooze

### ISSUE THREAD

**Issue by hijarian** [quicklisp/quicklisp-projects#773]
It is the REST router over the Hunchentoot: https://github.com/capitaomorte/snooze

[PR](https://github.com/capitaomorte/snooze/pull/1) with the required changes to .asd is submitted.

**Comment by capitaomorte** [comment]
After almost a year, I've rewritten Snooze almost completely, keeping the good part of the API, but making it backend-agnostic, adding a nicer tutorial and documentation. Perhaps it can be included in the next quicklisp release (the URL is the same).
