### ISSUE TITLE
Please use up to date lisp-magick

### ISSUE THREAD

**Issue by tmccombs** [quicklisp/quicklisp-projects#779]
The branch of lisp-magick at https://github.com/TBRSS/lisp-magick works for recent versions of ImageMagick, while version of lisp-magick currently in the quicklisp distribution does not.

**Comment by quicklisp** [comment]
I'd really like to have an updated lisp-magick, but I hate to use one with the same name that is incompatible with the original. What can be done?

**Comment by ruricolist** [comment]
I could rename the system; since it binds the MagickWand API, how about `lisp-magick-wand`?

**Comment by quicklisp** [comment]
That sounds good to me.

**Comment by ruricolist** [comment]
I've renamed the system. Do you need the Github repository renamed as well?

**Comment by quicklisp** [comment]
The project name and repo name need not match for Quicklisp's sake, but I think it may help people when searching if the names match.

**Comment by ruricolist** [comment]
Renamed. The new address:

https://github.com/TBRSS/lisp-magick-wand
