### ISSUE TITLE
Please add Woo

### ISSUE THREAD

**Issue by fukamachi** [quicklisp/quicklisp-projects#812]
Woo is a fast non-blocking HTTP server built on top of [cl-async](https://github.com/orthecreedence/cl-async) and [fast-http](https://github.com/fukamachi/fast-http).

https://github.com/fukamachi/woo

**Comment by sjatkins** [comment]
I still can't get it from quicklisp.  Please advise.

**Comment by quicklisp** [comment]
You must use an up-to-date dist. You can get the most recent dist by using `(ql:update-dist "quicklisp")`. After that, `(ql:quickload "woo")` should load woo.

**Comment by sjatkins** [comment]
Indeed.  Thanks!
