### ISSUE TITLE
Please add GENERIC-COMPARABILITY, a CDR-8 implementation.

### ISSUE THREAD

**Issue by pnathan** [quicklisp/quicklisp-projects#825]
Hello,

Please add https://github.com/pnathan/generic-comparability to Quicklisp. It implements CDR-8 (and personally, I will be really happy when this gets merged! :D).

Regards,
Paul

**Comment by marcoxa** [comment]
CDR is a spec for generic "equality" predicates in Common Lisp.  (By, shameless plug, yours truly.)

http://cdr.eurolisp.org/document/8/index.html

MA

**Comment by pnathan** [comment]
well, that's true, @quicklisp .  I will polish up the landing page for the github.
