### ISSUE TITLE
Please add Kenzo

### ISSUE THREAD

**Issue by gheber** [quicklisp/quicklisp-projects#828]
https://github.com/gheber/kenzo

**Comment by quicklisp** [comment]
Any word on this?

**Comment by gheber** [comment]
Nothing new. About a week ago, I have contacted another Kenzo coauthor, but not heard anything. Total silence. I'm not sure what's going on. I'll try a few other names. The can't have all disappeared  from the planet... We should definitely postpone it for Quicklisp until we've resolved the licensing question.

**Comment by quicklisp** [comment]
Please reopen when the license info is cleared up.

**Comment by gheber** [comment]
Licensing has been sorted. GPLv3. Would you give it another try? Thanks, G.
