### ISSUE TITLE
Please add Lucerne

### ISSUE THREAD

**Issue by eudoxia0** [quicklisp/quicklisp-projects#834]
It's a tiny web framework built on Clack. I have yet to announce it and make a nice project website, but I want to get it on Quicklisp since a couple of my projects use it.

https://github.com/eudoxia0/lucerne

Thanks!

**Comment by fukamachi** [comment]
I'm very glad to see a web framework built on Clack. Let's add it to http://clacklisp.org.

**Comment by eudoxia0** [comment]
Thanks! I hope to have a project site and proper documentation up soon.
