### ISSUE TITLE
Add DEFENUM to quicklisp

### ISSUE THREAD

**Issue by marcoxa** [quicklisp/quicklisp-projects#837]
Hi
could you please add DEFENUM to Quicklisp?

It is a small hack/library that adds C++ and Java like 'enum' to Common Lisp.
The site (and doc) is at http://defenum.sourceforge.net
The git repository is at http://git.code.sf.net/p/defenum/code
The license is - as usual - BSD.

All the best
--
MA

**Comment by quicklisp** [comment]
Can you please add :license and :description info to the system definition form?

**Comment by marcoxa** [comment]
Will do.

Marco


On Tue, Jan 13, 2015 at 6:11 PM, Zach Beane <notifications@github.com>
wrote:

> Can you please add :license and :description info to the system definition
> form?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/quicklisp/quicklisp-projects/issues/837#issuecomment-69780420>
> .
>



-- 
Marco Antoniotti
Somewhere over the Rainbow

**Comment by marcoxa** [comment]
Pushed to repo.

MA

On Tue, Jan 13, 2015 at 7:10 PM, Marco Antoniotti <marcoxa@gmail.com> wrote:

> Will do.
>
> Marco
>
>
> On Tue, Jan 13, 2015 at 6:11 PM, Zach Beane <notifications@github.com>
> wrote:
>
>> Can you please add :license and :description info to the system
>> definition form?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/quicklisp/quicklisp-projects/issues/837#issuecomment-69780420>
>> .
>>
>
>
>
> --
> Marco Antoniotti
> Somewhere over the Rainbow
>



-- 
Marco Antoniotti
Somewhere over the Rainbow
