### ISSUE TITLE
Please add on-lisp

### ISSUE THREAD

**Issue by DalekBaldwin** [quicklisp/quicklisp-projects#840]
This is a modernized and annotated companion repository to the book "On Lisp". Paul Graham gave the okay to distribute it in this form as long as it links to the original code too.

https://github.com/DalekBaldwin/on-lisp

**Comment by quicklisp** [comment]
The license on the original code, forbidding commercial use, isn't suitable for Quicklisp, sorry.

**Comment by quicklisp** [comment]
Feel free to reopen if the licensing changes in the future.
