### ISSUE TITLE
maybe add workout-timer

### ISSUE THREAD

**Issue by fare** [quicklisp/quicklisp-projects#842]
It's a silly small application, but already slightly useful, and could be used as the basis for more or better.

http://common-lisp.net/gitweb/?p=projects/users/frideau/workout-timer.git;a=summary;js=1
git://common-lisp.net/users/frideau/workout-timer.git

**Comment by quicklisp** [comment]
Can you please add :author information to the system definition?

**Comment by eudoxia0** [comment]
Unless I seriously misunderstood something, I suspect the `:description` and `:long-description` fields are wrong.

**Comment by quicklisp** [comment]
@eudoxia0 Seems probable.

**Comment by fare** [comment]
Oops, I updated the system definition, and created a trivial page on cliki.
