### ISSUE TITLE
Please add eazy-process

### ISSUE THREAD

**Issue by guicho271828** [quicklisp/quicklisp-projects#843]
https://github.com/guicho271828/eazy-process

In `run-program` interface in the popular implementations, piping between subprocesses are hard. It requires either reading the entire output stream and packing the contents as a new string-input-stream, or using some other implementation-specific functions. Compatibility libraries e.g.  trivial-shell or inferior-shell, often depend on `run-program`, but not implement "other impl-specific functions", therefore piping is again not clean. Iolib also has `run-program` that allows easy piping, but it is restricted to 3 fds: `input,output,error`.

Eazy-process provides a declarative and thin layer for manipulating processes. It is built on the concept of UNIX: "everything is a file" and do not provide interfaces to streams.

Currently, the only implementation verified to work as expected is SBCL on linux. CCL does not pass the test due to errors in opening /def/fd/[fd] to read/write the input/output/error directly. However, you can avoid this issue by writing the output to a temporary file and opening the file.

I suspect the same test might pass on the other OSes because it is a linux-specific problem (`realpath(3)` returns NULL and sets errno EACCES on those special files).

I used part of codes in SBCL and trivial-shell, so the current MIT licence might have to be changed.

**Comment by guicho271828** [comment]
if possible, please also "garbage correct" inner-conditional ...

**Comment by quicklisp** [comment]
Sorry, I do not like to add projects that work only on one implementation. Can you let me know when it supports more than one?

**Comment by guicho271828** [comment]
I do not mind if the addition is delayed. I use it in my private work anyways.

Ideally it should work on all implementations since it uses iolib.syscalls (and in turn CFFI) and cl package only. Build passes on all impls except on ecl (which fails to load CFFI).

What has been shown here is that there is only 1 implementation that can `(cl:open "/dev/fd/0")` and is CFFI-compatible on Linux. It is not that eazy-process fails because of this. Things happens *outside* eazy-process. See this test case:

```
(test read
  (let ((p1 (shell `("hostname"))))                ; eazy-process:shell
    (let ((fdpath (fd-as-pathname p1 1)))          ; eazy-process:fd-as-pathname returns /dev/fd/16 , for example
      (with-open-file (s fdpath)                   ; abcl and ccl fail to open this file
        (is (string= (machine-instance)
                     (read-line s)))))))
```

 If you have a Mac, would you please try `(cl:open "/dev/fd/0")` in your CCL repl? It might be okay on darwin because it uses different file system for /dev/fd/. Darwin implements it with `fdesc`, while linux makes the symlinks to /proc/self/fd/, which is implemented with `proc` filesystem. Please also refer to http://trac.clozure.com/ccl/ticket/1261 .

**Comment by guicho271828** [comment]
I asked a Mac owner to test `(cl:open "/dev/fd/[int]")` and `(with-open-file (s "/dev/fd/1" :direction :output :if-exists :overwrite) (write-char #\x s))`, both worked well. I now think the test should pass on darwin on CCL and SBCL.
