### ISSUE TITLE
Please add MGL-MAT and MGL

### ISSUE THREAD

**Issue by melisgl** [quicklisp/quicklisp-projects#844]
If understand https://github.com/quicklisp/quicklisp-projects/issues/514 right, then CL-CUDA is finally going in. Please add MGL-MAT and MGL too when that happens.

**Comment by melisgl** [comment]
Oops. MGL is in quicklisp, but it's stuck at an old version due to dependency on MGL-MAT. So it only needs to be updated when MGL-MAT gets in.

**Comment by quicklisp** [comment]
Unfortunately, while Debian 7 helped with cl-cuda, it broke a number of other things that I have been unable to fix. For the moment, it's still a work in progress.

**Comment by melisgl** [comment]
I see. While we are on this subject, I'm worried that this logic from the `mgl-mat.asd` would break quicklisp in interesting ways:

    ;;; The CUDA SDK may not be installed, we need CUDA-GROVEL-FILE from
    ;;; CL-CUDA to grovel safely.
    (eval-when (:load-toplevel :execute)
      (asdf:operate 'asdf:load-op '#:cl-cuda))

This is pretty similar to what's happening in `cl-cuda.asd`. Anyway, is this a problem for quicklisp?

**Comment by quicklisp** [comment]
It isn't a problem. Quicklisp tracks what's actually loaded, not just what's specified in the defsystem form.

**Comment by takagi** [comment]
melisgl may be asking about cl-cuda's subclassing `cffi-grovel::grovel-file`, which handles any errors that occur in groveling.

In [cl-cuda.asd](https://github.com/takagi/cl-cuda/blob/master/cl-cuda.asd):

    (defclass cuda-grovel-file (cffi-grovel:grovel-file) ())
    
    (defmethod asdf:perform :around ((op cffi-grovel::process-op) (c cuda-grovel-file))
      ...
      (handler-case (call-next-method op c)
        (error (e)
          ...)))

Although I think this does not affect any other libraries that do not use `cl-cuda::cuda-grovel-file`, would you check it too?

**Comment by quicklisp** [comment]
This builds now and will go into the next release.
