### ISSUE TITLE
Please add transparent-wrap

### ISSUE THREAD

**Issue by DalekBaldwin** [quicklisp/quicklisp-projects#847]
This utility is designed to programmatically wrap entire an entire package's worth of functions. It creates wrappers with parameter signatures that match (as closely as possible) the functions they wrap so you get the same information out of the SLIME minibuffer as if you'd used the original function.

https://github.com/DalekBaldwin/transparent-wrap

**Comment by quicklisp** [comment]
Doesn't build for me. Log is here: http://report.quicklisp.org/2015-01-30/failure-report/transparent-wrap.html

    ; caught WARNING:
    ;   :SPECIALIZED is not a known argument keyword.

**Comment by DalekBaldwin** [comment]
Okay, fixed. That was in a bit of currently unused helper code.

Although when I enable `disable-debugger` in SBCL, it still loads fine through `ql:quickload` - is there a Quicklisp setting I can use to make sure it still fails?

**Comment by quicklisp** [comment]
Make sure to quickload with the `:verbose t`. It is closer to the build testing I do than the default non-verbose mode.
