### ISSUE TITLE
Please add shellpool

### ISSUE THREAD

**Issue by jaredcdavis** [quicklisp/quicklisp-projects#848]
Hi,

[Shellpool](https://github.com/jaredcdavis/shellpool) is a library for running external programs from Common Lisp.  It has many features, e.g., control over when forking occurs, flexible access to stdout/stderr, exit code information, and graceful shutting down of the sub-program in response to user interrupts or output processing errors.

I think most things are in order per the [instructions](http://blog.quicklisp.org/2015/01/getting-library-into-quicklisp.html):

1. It is licensed under an MIT/X11 style [license](https://github.com/jaredcdavis/shellpool/blob/master/LICENSE).

2. It runs on many Lisps and operating systems (including the required SBCL on Linux platform).

3. Its [defsystem call](https://github.com/jaredcdavis/shellpool/blob/master/shellpool.asd) includes the required `:license`, `:author`, and `:description` fields.  It also has a [README.md](https://github.com/jaredcdavis/shellpool/blob/master/README.md) file and [API documentation](https://github.com/jaredcdavis/shellpool/blob/master/DOC.md).

4. Here I am less sure.  I normally load the library using `(ql:quickload "shellpool")` after putting it into my `quicklisp/local-projects` directory and also by running `(require 'shellpool)`.  But I am not very familiar with ASDF, so if any of this is incorrect or requires adjustment, please let me know and I will work to correct it.

5. Shellpool is hosted at Github, so a strategy of keeping it updated by just fetching `master` from Github would be great.

Other notes.

Shellpool has a small [test suite](https://github.com/jaredcdavis/shellpool/tree/master/test) which is **not** currently part of its build process.  This test suite takes perhaps a minute to run and invokes subprograms that are likely available (e.g., `perl`), but which are not strictly necessary for using Shellpool itself.  So, it may make sense for this to remain separate from the ASDF build.  I'm not sure how this sort of thing is ordinarily handled and would welcome any guidance.

Thanks very much for making Quicklisp.

Cheers,
Jared

**Comment by quicklisp** [comment]
Many projects put tests in my-cool-project-test.asd, which :depends-on the main system but then runs the test suite when loaded.

**Comment by jaredcdavis** [comment]
Thanks very much -- I will work on refactoring the test suite to make it a proper asdf system.
