### ISSUE TITLE
Please add TRIVIAL-EXPAND-TYPE.

### ISSUE THREAD

**Issue by markcox80** [quicklisp/quicklisp-projects#852]
The TRIVIAL-EXPAND-TYPE system provides an interface for expanding derived types. 

https://github.com/markcox80/trivial-expand-type

Thanks
Mark

**Comment by guicho271828** [comment]
Unfortunately the work seems duplicated... and the functionality is superseded.
see introspect-environment https://github.com/Bike/introspect-environment

**Comment by markcox80** [comment]
Thanks for pointing it out. I'll work on incorporating the implementations supported by TRIVIAL-EXPAND-TYPE in to INTROSPECT-ENVIRONMENT and then close the project.
