### ISSUE TITLE
Please add cl-yaml

### ISSUE THREAD

**Issue by eudoxia0** [quicklisp/quicklisp-projects#853]
It may have taken me two years, one complete rewrite, a whole extra library and a few hours of tracking down voodoo memory errors, but I've finally finished cl-yaml:

https://github.com/eudoxia0/cl-yaml

It's a YAML parser built on cl-libyaml, which binds libyaml, so we can read and write YAML files like those cool Ruby kids.

**Comment by quicklisp** [comment]
Does this relate in any way to cl-yaclyaml?

**Comment by eudoxia0** [comment]
Well, they are both YAML parsers. cl-yaclyaml is magrabor's project, which is pure CL, but is licensed under the GPL.

**Comment by mabragor** [comment]
Furthermore, in cl-yaclyaml emitting is not done, while cl-yaml, as I understood, can emit as well.

BTW, why GPL licence is an issue?

**Comment by eudoxia0** [comment]
I don't want to get into a political debate, but it's an issue to people who might want to use a YAML parser for a library, or in a commercial setting, and don't want to inherit the GPL license because it prevents them from eventually using the code in a closed-source commercial environment.
