### ISSUE TITLE
Please add burgled-batteries.syntax

### ISSUE THREAD

**Issue by mmontone** [quicklisp/quicklisp-projects#857]
https://github.com/mmontone/burgled-batteries.syntax

This library provides Embedded Python syntax for burgled-batteries

**Comment by quicklisp** [comment]
The test system doesn't build for me: http://report.quicklisp.org/2015-02-09/failure-report/burgled-batteries.syntax.html

**Comment by mmontone** [comment]
On 09/02/15 12:01, Zach Beane wrote:
>
> The test system doesn't build for me:
> http://report.quicklisp.org/2015-02-09/failure-report/burgled-batteries.syntax.html
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/quicklisp/quicklisp-projects/issues/857#issuecomment-73522340>.
>
My wrong. Sorry for the inconvenience. Should be fixed now.
