### ISSUE TITLE
Please add clavier

### ISSUE THREAD

**Issue by mmontone** [quicklisp/quicklisp-projects#859]
Clavier is a general purpose validation library for Common Lisp.

https://github.com/mmontone/clavier

**Comment by eudoxia0** [comment]
:+1:, I'm gonna have to see how I can adapt this to form validation.

**Comment by mmontone** [comment]
On 08/02/15 17:32, Fernando Borretti wrote:
>
> :+1:, I'm gonna have to see how I can adapt this to form validation.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/quicklisp/quicklisp-projects/issues/859#issuecomment-73430016>.
>
Ok. You can look here for some examples:
https://github.com/mmontone/cl-forms
