### ISSUE TITLE
Please add cl-xmlw

### ISSUE THREAD

**Issue by jlahd** [quicklisp/quicklisp-projects#865]
cl-xmlw is a simple namespace-aware XML writer for Common Lisp.

http://github.com/jlahd/cl-xmlw

**Comment by quicklisp** [comment]
This looks very similar to what CXML does. How does it differ?

**Comment by jlahd** [comment]
True. I simply overlooked CXML when I looked for an XML generator, as its description only advertises parsing. I found XML-EMITTER, which did not suit my needs, so I wrote a new one myself. I don't think cl-xmlw does anything CXML does not.

Thus, no need to add cl-xmlw after all.
