### ISSUE TITLE
Please add hl7-client

### ISSUE THREAD

**Issue by MartinEnders** [quicklisp/quicklisp-projects#867]
hl7-client is a TCP/IP client for sending HL7-Messages.

https://github.com/MartinEnders/hl7-client

**Comment by quicklisp** [comment]
What is an HL7-Message? Can that info be included (or linked to) in the README?

**Comment by MartinEnders** [comment]
I cited from the FAQ from hl7.org and put it in the README.md file (on both Projects hl7-parser and hl7-client):

>The HL7 Version 2 Messaging Standard — Application Protocol for Electronic Data Exchange in Healthcare Environments — is considered to be the workhorse of data exchange in healthcare and is the most widely implemented standard for healthcare information in the world.

Source: http://www.hl7.org/about/FAQs/index.cfm?ref=nav ("General HL7 FAQ" > "Version 2" > "What is Version 2?")
