### ISSUE TITLE
Please add cl-thread-macro

### ISSUE THREAD

**Issue by hipeta** [quicklisp/quicklisp-projects#869]
Cl-thread-macro is clojure-like thread macro library.

https://github.com/hipeta/cl-thread-macro

**Comment by quicklisp** [comment]
I find the name a bit confusing, since threading is more often used in the CL context for threads of execution. Is there any candidate name that would avoid this issue?

**Comment by hipeta** [comment]
Thanks for your response.  Then I will rename it to arrow-macros. Please wait a minute.

**Comment by hipeta** [comment]
I'm done. 

https://github.com/hipeta/arrow-macros

**Comment by quicklisp** [comment]
Ok. Have you seen https://github.com/nightfly19/cl-arrows, already in Quicklisp? Is there any possibility of combining the projects?

**Comment by hipeta** [comment]
I have seen cl-arrow but it becomes not combining but replacement ...

**Comment by hipeta** [comment]
I have sent pull request to nightfly19/cl-arrows for now.
