### ISSUE TITLE
clim-chess

### ISSUE THREAD

**Issue by jschatzer** [quicklisp/quicklisp-projects#871]
https://github.com/stassats/clim-chess

**Comment by quicklisp** [comment]
There's a lot of missing metadata - no README, and no license, author, or description info in the system file. When it's updated I can add it.

**Comment by jschatzer** [comment]
I got this answer from the author, Tue 03 Mar 2015
>
> Would you mind adding some metadata?
> Thank you very much
It's not in any working state and never will be, so, yes, I do mind.
With best regards, Stas.

**Comment by quicklisp** [comment]
That seems definitive.
