### ISSUE TITLE
Please add cl-sodium

### ISSUE THREAD

**Issue by psyhofreak** [quicklisp/quicklisp-projects#872]
It can be found on GitHub:

 https://github.com/orthecreedence/cl-sodium

*Thanks!*

**Comment by quicklisp** [comment]
I can't build it, can you?

**Comment by psyhofreak** [comment]
I just gave it a quick try, and nope. I think I had this one working a while back, but that was a whole Ubuntu install ago. Darned dependencies...

**Comment by quicklisp** [comment]
Please reopen if necessary.
