### ISSUE TITLE
Please add cl-poker-eval

### ISSUE THREAD

**Issue by jperson** [quicklisp/quicklisp-projects#874]
cl-poker-eval is a library for evaluating the strength of poker hands.

http://github.com/jperson/cl-poker-eval

**Comment by quicklisp** [comment]
Why does the example use defparameter without * around the variable name? That's a pretty bad idea.

**Comment by jperson** [comment]
I wrote this years ago before I was used to standard naming conventions.  It's fixed now, thanks.
