### ISSUE TITLE
Why not using two level directory structure to handle meta directory

### ISSUE THREAD

**Issue by netroby** [quicklisp/quicklisp-projects#877]
Why not using two level directory structure to handle meta directory?
Ths structure may be like this : 
```
a/
  aa/
  ab/
  ac/
b/
  ba/
  bb/
  bc/
  bd/
c/
  ca/
  cb/
  cc/
  cd/
```

**Comment by netroby** [comment]
We can see githhub do not allow more than 1000 sub directories in the same directory

```
Sorry, we had to truncate this directory to 1,000 files. 272 entries were omitted from the list.
```

**Comment by quicklisp** [comment]
That's a limitation of github that I don't care for working around.
