### ISSUE TITLE
Please add json-responses

### ISSUE THREAD

**Issue by bradJM** [quicklisp/quicklisp-projects#878]
Provides JSON response functions for Hunchentoot apps. Can be found on BitBucket: https://bitbucket.org/bradJM/json-responses

Should have all the required info, but if anything is missing I can definitely add it. Thanks!

**Comment by quicklisp** [comment]
Just curious - why does the JSON produce "error" but the keyword is :err? It would be more typical to use a full word on the Lisp side, too.

**Comment by bradJM** [comment]
Good catch, I pushed up a change to make them match.
