### ISSUE TITLE
Please add cl-groupby

### ISSUE THREAD

**Issue by wlbr** [quicklisp/quicklisp-projects#879]
https://github.com/wlbr/cl-groupby

A short implementation of Scalas groupBy functionality for Common Lisp. Provides a new higher order function for Lisp, see the readme for example usage.

Thanks!!

**Comment by quicklisp** [comment]
Why does the example use defparameter without * around the variable name? That's a pretty bad idea.

**Comment by quicklisp** [comment]
Also, it's best to put "groupby" in the :depends-on list of a system file. Putting load-system or require into source code is not a great option.

**Comment by wlbr** [comment]
Added the asterisks according to the convention. 

The tests or examples are not part of the asdf system, so I think the `require` is ok for an 'didactic' illustration.

Thanks for adding!
