### ISSUE TITLE
Please add trivia, trivia.balland2006, type-r, type-i

### ISSUE THREAD

**Issue by guicho271828** [quicklisp/quicklisp-projects#881]
https://github.com/guicho271828/trivia         -------- non-optimized, *trivial* pattern matching system with modularized optimization API, fully compatible with optima. (but in fact, empirical results indicates that it's *not that slow*...)
https://github.com/guicho271828/trivia.balland2006 ------- optimizer for Trivia (60x faster than optima in some case)
https://github.com/guicho271828/type-i ------ type inference library : infer types from predicate forms
https://github.com/guicho271828/type-r ------ type reference library : fork from Bike/compiler-macro/type-utils.lisp
https://github.com/guicho271828/immutable-struct ----- Simple library that encourage the use of functional programming + pattern matching.

**Comment by quicklisp** [comment]
Can you please add a more informative github description to type-r?

**Comment by guicho271828** [comment]
Done. V-TEC FTW!

**Comment by guicho271828** [comment]
Please add this one also :)
https://github.com/guicho271828/optima-immutable-struct
