### ISSUE TITLE
Please add metap, cl-singleton-mixin

### ISSUE THREAD

**Issue by hipeta** [quicklisp/quicklisp-projects#887]
Metap provides metaclass propagation along class inheritance structure.
https://github.com/hipeta/metap

Cl-singleton-mixin provides singleton mixin in Common Lisp.
https://github.com/hipeta/cl-singleton-mixin

**Comment by hipeta** [comment]
I withdraw this issue for some reasons.

**Comment by guicho271828** [comment]
oh I'm sad to see this, I was writing a type variable library in which this library would fit nicely.

**Comment by hipeta** [comment]
Sorry. 
I found an critical bug in metap so I wtihdrew it for now.
And I fixed it now, so reopen this issue.
Thanks to use this library :)
