### ISSUE TITLE
Please add unix-opts

### ISSUE THREAD

**Issue by mrkkrp** [quicklisp/quicklisp-projects#888]
This is a minimalistic parser of command line options. Main advantage of this library is ability to concisely define command line options once and then use this definition for parsing and extraction of command line arguments, as well as printing description of command line options (you get `--help` for free). This way you don't need to repeat yourself.

GitHub repo: https://github.com/mrkkrp/unix-opts
License: MIT

**Comment by quicklisp** [comment]
How does this project distinguish itself from the 10 other command-line parsing libraries already available in Quicklisp?

**Comment by mrkkrp** [comment]
First of all, the fact that Quicklisp has 10 different command-line parsing libraries, shows that this question should have been posed not now, but 9 libraries earlier. If you can list all the 10 libraries, I will gladly look at them all and if my library is inferior compared to any of them, I will close the issue. I don't write Lisp libraries because I have lots of free time, but because I need better libraries for my own project that is highly valuable for me. Before writing a library I usually do some research.

However, your desire to limit packages that provide similar functionality in Quicklisp is perfectly understandable. Moreover, command line parsing libraries seem to be trivial to write and thus numerous. Now, here is comparison between `unix-opts` and those libraries that I know of:

## [unix-options](https://github.com/astine/unix-options)

This library tries to emulate Unix `getopt`, which is originally a C function, that has flawed design (probably it's not that bad for C, but that's C). This library makes you *repeat yourself*: you have to pass arguments describing command line options when you 1) parse them 2) print descriptions of options (for `--help` command for example). It's also overcomplicated and has questionable (from my point of view) macros with hairy logic.

## [lisp-gflags](https://github.com/brown/lisp-gflags)

This is much better, because it allows to *define* flags (just like my library does). However, my library supports more CL implementations and it also makes use of Common Lisp restarts to allow precise control over such things as unknown options, arguments that cannot be parsed to specified data type et cetera. `lisp-gflags` just ignores unknown options, so what do you do when you want to stop execution of your program if you encounter unknown option? In my library you can specify parser for every argument (arbitrary function, possibly user-written), and if it fails you can use restarts to tell the library what to do. Also, my library doesn't depend on anything. This may be of questionable value, until you see that your executable is 67 M big. Such trivial libraries must be lightweight.

## [apply-argv](https://github.com/pve1/apply-argv)

This is too simple, lacks functionality and documentation.

No time for more... Have you seen [example](https://github.com/mrkkrp/unix-opts/blob/master/example/example.lisp)? Have you read [description](https://github.com/mrkkrp/unix-opts/blob/master/README.md)? If you still consider my library not unique, well, that's understandable, I will rework my other projects because they use Quicklisp to get their dependencies.

**Comment by quicklisp** [comment]
I don't reject libraries because they aren't sufficiently unique.

I ask about uniqueness because in some cases, authors are simply unaware that anyone else has had and solved a similar problem. (This is partly because it's too hard to discover useful things in Quicklisp.) In some of these cases, it is sufficient to add a feature or two to an existing project to make it suitable for the author's use.

Here are some of the other command-line processing projects of which I'm aware:

* [command-line-arguments](https://gitlab.common-lisp.net/qitab/command-line-arguments/blob/master/README)
* [clon](https://www.lrde.epita.fr/~didier/software/lisp/clon.php)
* [cl-cli](https://github.com/renard/cl-cli)

I think there are some I've missed, too.

**Comment by mrkkrp** [comment]
>I ask about uniqueness because in some cases, authors are simply unaware that anyone else has had and solved a similar problem.

This is good thing to do, because indeed, quite often we don't know about something useful. About those projects:

## command-line-arguments

Well, you can read their TODO list yourself and compare it with my first answer. Speaking of test-suite my lib has it. `command-line-arguments` also has no documentation (ubiquitous problem of many libraries, even quite useful and popular), I never put anything without docs. Last commit "30 Dec, 2013", so I can assume that all those problems won't be fixed. For me it's easier to write such little thing from scratch than contribute.

## clon

This must be great beast if it has

> automatic generation and formatting of help strings, with support for highlighting on tty's through ISO/IEC 6429 SGR. This formatting is customizable through "themes".

(!). Wow, this library even has its own logo. However, this is not minimalistic or lightweight. So this library and mine are incomparable.

**Comment by mrkkrp** [comment]
## cl-cli

This is not bad, I would use it, but API is hairy for my taste:

* you are supposed to define options by storing them in some variable, which is specially formatted list (look at it, its organization is not too clear), pass it around to parse things. Why, when it can be organized as DSL? Clearly we should be able to define options and all other parts of such a library should *just work* with this definition in mind.

* to define command you first construct it with `cl-cli:defcommand`, then again pass it around.

I have to admit that `unix-opts` doesn't support commands, it only supports options and free arguments, but that may be easily fixed later and coded in the same spirit.

I hate to look like a person who doesn't like work of others, but I also cannot do my work in wrong way when I can fix it. So, I have written this library, according to my understanding of the problem.
