### ISSUE TITLE
Please ass carrier

### ISSUE THREAD

**Issue by orthecreedence** [quicklisp/quicklisp-projects#890]
https://github.com/orthecreedence/carrier

A simple non-blocking HTTP client that runs on top of cl-async/fast-http. Thanks!

**Comment by orthecreedence** [comment]
Wow did not notice the title until now. Oops.

**Comment by eudoxia0** [comment]
tbh Zach should've committed "Assed carrier per issue #890".

**Comment by orthecreedence** [comment]
Agreed =].
