### ISSUE TITLE
Please remove HCTSMSL

### ISSUE THREAD

**Issue by HiTECNOLOGYs** [quicklisp/quicklisp-projects#893]
Apology for burdening you with such a ridiculous requests. I just want to make sure I won't be responsible for indirectly and accidentally breaking something some time in future.

Maybe it's good enough but I have no more will to keep it up-to-date or develop it further. Maybe somebody will pick it from there, but that'll be totally different project with, hopefully, better name.

Thanks in advance, I really appreciate that it was there for quite some time.

**Comment by quicklisp** [comment]
This was done some time ago.

**Comment by HiTECNOLOGYs** [comment]
Thanks.
