### ISSUE TITLE
Please, add should-test

### ISSUE THREAD

**Issue by vseloved** [quicklisp/quicklisp-projects#897]
<https://github.com/vseloved/should-test>

It's yet another test library. It's minimal, but it supports xunit output which is rare if present at all in the Lisp testing world.

**Comment by quicklisp** [comment]
Is there any way that xunit output could be added to an existing test library instead?

**Comment by vseloved** [comment]
Sure, it's just a separate file independent of the other parts of the library (which was lurking in the directory but haven't got to github - added it now :)

Still, I'd like to add the thing for it to be available to other folks. It proved to be much more convenient for my needs than other testing libraries (of which I preferred to use `rt` before, but it's really limited).

**Comment by quicklisp** [comment]
Does not build for me. There are multiple problems. A log is here:

http://report.quicklisp.org/2015-03-27/failure-report/should-test.html

**Comment by vseloved** [comment]
Sorry, updated to a working version.

**Comment by quicklisp** [comment]
Still can't build due to local-time issue.

**Comment by vseloved** [comment]
yup, now fixed :(

**Comment by quicklisp** [comment]
Now can't build because package "RE" not found.

**Comment by vseloved** [comment]
fixed

**Comment by quicklisp** [comment]
Now it cannot find package "PPCRE".

**Comment by vseloved** [comment]
yes, dependence on local env when releasing something is a curse 
fixed

**Comment by quicklisp** [comment]
Fresh sessions!

Works now, thanks.

**Comment by vseloved** [comment]
Yeah, fresh and vanilla :)
