### ISSUE TITLE
Please add Jonathan

### ISSUE THREAD

**Issue by Rudolph-Miller** [quicklisp/quicklisp-projects#900]
Jonathan is aJSON encoder and decoder.

https://github.com/Rudolph-Miller/jonathan

**Comment by quicklisp** [comment]
Is there any way the benefits the Jonathan can be incorporated into one of the many existing JSON libraries?

**Comment by Rudolph-Miller** [comment]
It seems to be the fastest (I think the fastest library to parse JSON in Common Lisp was jsown.).

**Comment by eudoxia0** [comment]
Suggestion: Yason has these macros like `with-object`, `with-array`, `encode-array-element` etc for writing stuff to JSON. It would be cool if Jonathan had these so we don't have to take the error-prone route of writing `(write-char #\{)`, etc.

**Comment by Rudolph-Miller** [comment]
Yeah, I thought of that kind of macro to ease encoding original structure or class, and I will write some.

**Comment by quicklisp** [comment]
I am asking if Jonathan can be incorporated completely into something else. Is that possible?

**Comment by Rudolph-Miller** [comment]
No, it's totally different from other projects from the viewpoint of the codes and it makes faster than other projects.

**Comment by guicho271828** [comment]
it would catch more attentions if you add some keywords like "compatible with jsown" to the description.

**Comment by quicklisp** [comment]
If it's compatible with jsown, why not merge the projects so jsown is faster and users of jsown get the benefits without changing their code?

**Comment by Rudolph-Miller** [comment]
Ah, this is just optional.
I don't like the style of jsown object, and operations of jsown object.
I just wanted to handle plist mainly, and then I added compatible layer.
Moreover, it's not really compatible with jsown:parse.jsown:parse can raise the error with incomplete json string, and jonathan:parse behaves like junk-allowed of parse-integer.

**Comment by quicklisp** [comment]
To be clear: I will not reject Jonathan (or any other project) for covering similar ground as another project. However, I would like to see projects work together whenever possible. If it is not possible, that is unfortunate but not an insurmountable obstacle to inclusion in Quicklisp.

**Comment by Rudolph-Miller** [comment]
It's really reasonable, and I agree with you of course.
If I could make jsown faster and make jsown be able to handle plist and alist with some patches (in other words, with not replacement of whole codes), I would do so.
