### ISSUE TITLE
Please add bytecurry.mocks

### ISSUE THREAD

**Issue by tmccombs** [quicklisp/quicklisp-projects#905]
This is a small library to make it a little easier to mock up functions and methods for unit tests:

https://github.com/bytecurry/bytecurry.mocks

**Comment by quicklisp** [comment]
I'm getting this:

    Unhandled SIMPLE-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING {10040BFB53}>: Unknown suite BYTECURRY.MOCKS.TEST.

http://report.quicklisp.org/2015-04-05/failure-report/bytecurry.mocks.html

**Comment by tmccombs** [comment]
Oops, should be fixed now.
