### ISSUE TITLE
Please add cl-pslib

### ISSUE THREAD

**Issue by cage2** [quicklisp/quicklisp-projects#906]
cl-pslib is a CFFI wrapper for the pslib, a library for generating PostScript files.

https://github.com/cage2/cl-pslib/

Bye.

**Comment by quicklisp** [comment]
Have you considered writing this in Lisp, like cl-pdf?

**Comment by cage2** [comment]
On Wed, Apr 08, 2015 at 02:21:50PM -0700, Zach Beane wrote:
> Have you considered writing this in Lisp, like cl-pdf?

To be honest no, I wanted to  learn someting about CFFI when i started
cl-pslib.   But  the C  library  has  some  good features,  like  text
justification and hyphenation, and this wrapper became actually useful
some time later for me.

Rewrite all in lisp  would be great but i have not  so much spare time
and  i found  i could  go  straight to  the  goal (write  a bunch  of
documents, mostly letter) with this wrapper.

Bye!
C.

**Comment by cage2** [comment]
On Wed, May 06, 2015 at 06:26:14AM -0700, Zach Beane wrote:
> Closed #906.
> 

Thank you!
