### ISSUE TITLE
Add cl-vector-math to quicklisp

### ISSUE THREAD

**Issue by porky11** [quicklisp/quicklisp-projects#908]
Didn't find a system for math with vectors, made one, here it is:
https://github.com/cl-porky11/cl-vector-math
please add

**Comment by quicklisp** [comment]
Can you please add a README to the project?

**Comment by quicklisp** [comment]
Also, can you add :author to the system file?

**Comment by quicklisp** [comment]
Any word on this?

**Comment by porky11** [comment]
I don't think it's a good lib anymore, maybe later
