### ISSUE TITLE
Please add cl-strftime

### ISSUE THREAD

**Issue by ruricolist** [quicklisp/quicklisp-projects#911]
https://github.com/ruricolist/cl-strftime

Formats dates and times using the strftime "language".

**Comment by quicklisp** [comment]
Out of curiosity: I am under the impression that "strftime" varies by platform. Is that impression mistaken? If it's not, are you targeting a common subset, or a superset, or something?

**Comment by ruricolist** [comment]
I'm particularly targeting GNU strftime. Most of the actual time-formatting directives are in POSIX, but there are a few GNU "extras", and only GNU supports flags to control field padding, which is indispensable for generating some of the named formats cl-stftime supports.
