### ISSUE TITLE
Please add or-functions

### ISSUE THREAD

**Issue by opsresearch** [quicklisp/quicklisp-projects#913]
The system or-functions is a library of data structures and algorithms useful for implementing applications in the area of Operations Research.

The system is located at: https://github.com/OpsResearchLLC/or-functions

**Comment by quicklisp** [comment]
I looked at the code, and it does not seem like anything is implemented yet. Am I looking in the wrong place?

**Comment by opsresearch** [comment]
Yes, the location is correct and there is more implementation checked in now.

**Comment by opsresearch** [comment]
Yes, it is correct and there is more implementation checked in now.

**Comment by quicklisp** [comment]
Do you actively use this project, or is it a placeholder for some future work?

**Comment by opsresearch** [comment]
I will re-submit or-functions later when it has more features.
