### ISSUE TITLE
Please add or-mixed-integer

### ISSUE THREAD

**Issue by opsresearch** [quicklisp/quicklisp-projects#914]
The system or-mixed-integer is a library for solving mixed integer linear programming optimization problems.

The system is located at: https://github.com/OpsResearchLLC/or-mixed-integer

**Comment by quicklisp** [comment]
There doesn't seem to any code in the repo. Is something missing?

**Comment by opsresearch** [comment]
Please close this issue. or-mixed-integer has been incorporated into or-functions.

**Comment by quicklisp** [comment]
Ok. Can you please respond to my question on #913?
