### ISSUE TITLE
lisp-critic?

### ISSUE THREAD

**Issue by nklein** [quicklisp/quicklisp-projects#917]
I copied the lisp-critic tarball from your website.  I untarred it in local-projects/.  It worked just fine out of the box.  Same goes for this from github:  https://github.com/g000001/lisp-critic.git

**Comment by quicklisp** [comment]
The system file on github lacks [some metadata](http://blog.quicklisp.org/2015/01/getting-library-into-quicklisp.html).

**Comment by g000001** [comment]
some metadata added. https://github.com/g000001/lisp-critic/blob/master/lisp-critic.asd
