### ISSUE TITLE
Please add cl-durian

### ISSUE THREAD

**Issue by GordianNaught** [quicklisp/quicklisp-projects#921]
cl-durian creates human legible, indented HTML from simple list structures

https://github.com/GordianNaught/cl-durian

**Comment by quicklisp** [comment]
There are a number of HTML generation projects already. Is there any way this functionality could be added to an existing project?

**Comment by GordianNaught** [comment]
Examples of multiple different HTML generators (including cl-durian) can be found from line 313 onwards https://gitlab.com/com-informatimago/com-informatimago/blob/master/common-lisp/html-generator/html-generators-in-lisp.txt.

Most currently maintained HTML generators use macros instead of list structures. I use list structures so that plain list interpolation can be used to control selective evaluation, and because the list structure representation can be passed around and wrapped by other functions.

cl-durian is loosely based on how dynamic html is generated in SWI-Prolog.

**Comment by quicklisp** [comment]
Ok. Can you please tell me if this project can be combined with another existing project?

**Comment by GordianNaught** [comment]
I cannot be combined with any that I know of.

**Comment by quicklisp** [comment]
Why not?

**Comment by eudoxia0** [comment]
cl-markup does this, unless I'm missing some new feature:

```lisp
CL-USER> (markup:markup* (list :a :href "google.com" (list :b "Text")))
"<a href=\"google.com\"><b>Text</b></a>"
CL-USER> (markup:markup* `(:span :class "number" ,(format nil "~3$" pi)))
"<span class=\"number\">3.142</span>"
```

**Comment by GordianNaught** [comment]
That is more similar that other projects I have seen.
It does not produce indented HTML from what I see, though.
It also has a less permissive license (LLGPL).
cl-durian is under WTFPL.

**Comment by eudoxia0** [comment]
No, it doesn't, but a macro could be added to do just that (e.g. `(with-indent (:length 4) ...)`), and I don't think the authors are very religious about that choice of license, I think they would be willing to discuss relicensing to BSD.

**Comment by GordianNaught** [comment]
cl-durian currently supports the indentation, and cl-markup works differently so it isn't something that can be moved across trivially.
The source of cl-durian is very small.
There is value in not using macros when not necessary.
Using a comma to interpolate when necessary is more convenient than adding a colon before every tagname (personal taste on that I suppose).
I do think there is a substantive difference between the two projects.
