### ISSUE TITLE
Please add Function-Literal

### ISSUE THREAD

**Issue by GordianNaught** [quicklisp/quicklisp-projects#924]
It is a read macro that allows for Clojure-style function literals in Common Lisp.
They can nest as well, which they can't in Clojure.

It allows you to write `#f(+ 1 %)` instead of `(lambda (x) (+ 1 x))`.

https://github.com/GordianNaught/Function-Literal

**Comment by antoszka** [comment]
Tako rzecze Jonathan Wardell Avery (2015-05-14, 04:28):

> It is a read macro that allows for Clojure-style function literals in Common Lisp.
> They can nest as well, which they can't in Clojure.
> 
> It allows you to write `#f(+ 1 %)` instead of `(lambda (x) (+ 1 x))`.
> 
> https://github.com/GordianNaught/Function-Literal

Isn't a practically identical functionality already being provided by
hu.dwim.syntax-sugar? As in:

(hu.dwim.syntax-sugar:enable-sharp-l-syntax)
;
#l(foo !2 !1) → (lambda (x y) (foo y x))

-- 
[アントシカ]

**Comment by GordianNaught** [comment]
I tried

    (ql:quickload :hu.dwim.syntax-sugar)

that worked
then I tried

    (hu.dwim.syntax-sugar:enable-sharp-l-syntax)

and got

    #<PACKAGE HU.DWIM.SYNTAX-SUGAR> has no external symbol with name
    "ENABLE-SHARP-L-SYNTAX"

Can you explain how to use this package a little more, please?

**Comment by antoszka** [comment]
Tako rzecze Jonathan Wardell Avery (2015-05-14, 05:34):

> I tried
> 
>     (ql:quickload :hu.dwim.syntax-sugar)
> 
> that worked

Yep, sorry I wasn't specific enough, you need to:

(ql:quickload :hu.dwim.syntax-sugar+hu.dwim.walker)

then:

CL-USER> (funcall #L(values !2 !1) 'foo 'bar)
BAR
FOO

Also Arnesi seems to include a #L reader:

https://github.com/vseloved/arnesi/blob/master/src/sharpl-reader.lisp

-- 
[アントシカ]

**Comment by GordianNaught** [comment]
Thank you.
It seems to fail under CLISP.

    [43]> (funcall #L(values !2 !1) 'foo 'bar)

    ** - Continuable Error
    This is not implemented for your lisp, sorry. You may try to continue, but...
    If you continue (by typing 'continue'): ignore and try to continue
    The following restarts are also available:
    ABORT          :R1      Abort main loop
    Break 1 [44]>

**Comment by antoszka** [comment]
Tako rzecze Jonathan Wardell Avery (2015-05-14, 06:15):

> Thank you.
> It seems to fail under CLISP.

But arnesi *does* work under clisp (the #L reader seems to behave more
or less identically).

-- 
[アントシカ]

**Comment by GordianNaught** [comment]
just tested the arnesi variant, it doesn't nest

    [15]> (#l(#l(* !1 !2) !1 3) 4)

    *** - EVAL:
           (IT.BESE.ARNESI::SHARPL-EXPANDER #<PACKAGE COMMON-LISP-USER>
            ((IT.BESE.ARNESI::SHARPL-EXPANDER #<PACKAGE COMMON-LISP-USER> (* !1 !2) NIL) !1 3)
            NIL)
          is not a function name; try using a symbol instead
    The following restarts are available:

**Comment by GordianNaught** [comment]
apparently you must use `funcall` on the inner function as well

I don't see any reason for this behavior, as it should expand at read-time.

**Comment by quicklisp** [comment]
I can't load this until it has a system definition file (*.asd).

**Comment by quicklisp** [comment]
Please reopen when you add a system file.
