### ISSUE TITLE
CFFI from git?

### ISSUE THREAD

**Issue by tarballs-are-good** [quicklisp/quicklisp-projects#926]
Any reason why CFFI isn't being pulled from git? https://github.com/cffi/cffi

This has had fixes for Mac. Do you just wait until it's released on C-L.net?

**Comment by quicklisp** [comment]
I've just always pulled the release, and they have happened on a semi-regular basis. If the git version has good stuff in it, perhaps it's time for a new release.

**Comment by quicklisp** [comment]
There's been a new CFFI release, is it good?

**Comment by quicklisp** [comment]
Any word on this?

**Comment by quicklisp** [comment]
Feel free to reopen if needed.
