### ISSUE TITLE
clim-pkg-doc

### ISSUE THREAD

**Issue by jschatzer** [quicklisp/quicklisp-projects#927]
https://github.com/jschatzer/clim-pkg-doc

**Comment by quicklisp** [comment]
Doesn't build for me. http://report.quicklisp.org/2015-05-28/failure-report/clim-pkg-doc.html has a log.

**Comment by quicklisp** [comment]
Still can't build it - it now references ql-dist? That package is not available.

**Comment by jschatzer** [comment]
Could you please give another try?
Removed above reference to ql-dist.

**Comment by jschatzer** [comment]
Now it could go, please try another time.
(Don't know how to test it myself)
Thank you

**Comment by quicklisp** [comment]
Now in Quicklisp.
