### ISSUE TITLE
Please add swank-protocol

### ISSUE THREAD

**Issue by eudoxia0** [quicklisp/quicklisp-projects#931]
It's basically a lower-level, permissively-licensed [swank-client](https://github.com/brown/swank-client). It implements just the low-level parts of Swank's protocol (encoding, sending/receiving data through streams) so other people can implement actual clients over it

https://github.com/eudoxia0/swank-protocol

Thanks!

**Comment by quicklisp** [comment]
I'm having trouble building this project today. Something seems to be hanging in the tests. Have you tested with slime 2.14?
