### ISSUE TITLE
Please add Varjo

### ISSUE THREAD

**Issue by cbaggers** [quicklisp/quicklisp-projects#935]
Varjo contains a lisp->glsl compiler

Translates a subset of common lisp to glsl. Checks types and allows rolling translate where args and uniforms from one stage are made available in the next.

Support ubos, external struct definition & is easy to extend

git@github.com:cbaggers/varjo.git

Thanks :)

[note] Does depend on 'fn' another library with a quicklisp add request.

**Comment by eudoxia0** [comment]
:+1:
