### ISSUE TITLE
Please add cl-string-match

### ISSUE THREAD

**Issue by vityok** [quicklisp/quicklisp-projects#937]
CL-STRING-MATCH aims at providing robust implementations of string matching algorithms. These algorithms are also called "substring search" or "subsequence search" algorithms.

At the moment most useful feature it provides is parametric Boyer-Moore-Horspool algorithm implementation offering up to an order of magnitude performance boost over standard `search` function.

https://bitbucket.org/vityok/cl-string-match

**Comment by quicklisp** [comment]
Does this project relate to http://clstringmatch.sourceforge.net/ which is already in Quicklisp? Is it the same thing?

**Comment by vityok** [comment]
Yep, it is a mirror of the same project. Sorry for confusing you, will push to the original repository instead.

Sorry
