### ISSUE TITLE
Please add qt-libs

### ISSUE THREAD

**Issue by Shinmera** [quicklisp/quicklisp-projects#938]
This is a wrapper system that should help ensure that the necessary shared libraries for development with CommonQt/Qtools are available on the system and can be easily used for deployment.

Author: Nicolas Hafner
Source: https://github.com/Shinmera/qt-libs.git
Documentation: http://shinmera.github.io/qt-libs/

**Comment by quicklisp** [comment]
Looks neat! I gave this a try, but got an error. The docs say this:

> which will try to make sure that everything concerning foreign libraries will go smoothly.

Does that mean only the _smoke_ foreign libraries? Or should qt-libs install qt as well?

**Comment by quicklisp** [comment]
The error:

    CMake Error at /usr/local/share/cmake-3.2/Modules/FindQt4.cmake:1326 (message):
      Found unsuitable Qt version "" from NOTFOUND, this code requires Qt 4.x
    Call Stack (most recent call first):
      CMakeLists.txt:4 (find_package)

**Comment by Shinmera** [comment]
Qt has to be provided by the system, yes. I considered it too large to set up an automatic source build, and it should be available on every distribution, as well as OS X, so there's no special need for it, unlike smoke.

**Comment by quicklisp** [comment]
Does qt-libs work well on Windows, too?

**Comment by Shinmera** [comment]
Currently it doesn't. You need Visual Studio in order to build libcommonqt properly (I tried with MSYS et al before, it can't be done), which I cannot really depend on. However, I'll include an automatic download of the required DLLs so that it'll work using that at least.

**Comment by Shinmera** [comment]
Also: This system is currently duplicated in Qtools (and has been for the past few days). If you can still squeeze this project in before the next dist release, I'll remove it from there.

**Comment by quicklisp** [comment]
I can't add it until it's removed from qtools due to .asd name clash.

**Comment by Shinmera** [comment]
Done. Shinmera/qtools@0f1ac7a9763a3527a2fa212843209ed23dfebd2d
