### ISSUE TITLE
Please add or-glpk

### ISSUE THREAD

**Issue by opsresearch** [quicklisp/quicklisp-projects#941]
OR-GLPK is a complete foreign interface to the GNU Linear Programming Kit.
The repository is here: https://github.com/OpsResearchLLC/or-glpk

**Comment by cl-opsresearch** [comment]
The Gnu Linear Programming Kit in CL allows one to develop optimizations in an interactive environment with the ability to move the results to production without having to change platforms. The optimizations are useful to industries including manufacturing, transportation, operations and logistics to name a few.

**Comment by opsresearch** [comment]
I will  have to close this request because or-glpk has a dependency on cl-opsresearch which isn't in the repo yet. It isn't going to build for you.
