### ISSUE TITLE
Please add or-gsl

### ISSUE THREAD

**Issue by opsresearch** [quicklisp/quicklisp-projects#942]
OR-GSL is a complete foreign interface to the GNU Scientific Library.
The repository is here: https://github.com/OpsResearchLLC/or-gsl

**Comment by quicklisp** [comment]
There is already a project that does this, gsll. Does or-gsl differ from gsll in a significant way?

**Comment by cl-opsresearch** [comment]
Yes, or-glpk and or-gsl are the first two in a set of analytical components that are designed to interoperate. In addition to the CFFI interface they (will) have a lisp wrapper around the CFFI to normalize the data structures and operations of the native libraries. There are more components planned.

**Comment by quicklisp** [comment]
Can you use gsll instead of making a new project?

**Comment by cl-opsresearch** [comment]
Gsll would likely work as a dependency of or-gsl to implement the CFFI. However; or-gsl would still need to exist to implement the lisp wrapper that provides interoperability with the other components.

**Comment by quicklisp** [comment]
I don't really want to add an incomplete library that could cause confusion with an existing library. When it's more complete, could you please submit it for inclusion again?

**Comment by opsresearch** [comment]
OK, will do.
