### ISSUE TITLE
Please add cl-git

### ISSUE THREAD

**Issue by russell** [quicklisp/quicklisp-projects#948]
Hey Zach,

I would really like to add cl-git to Quicklisp.  I will do what ever I can to get it in. There are some caveats. https://github.com/russell/cl-git/

For a start it only support libgit2 0.20.0 which the current version of libgit2 is 0.22.2  it should be trivial to update, I have a fairly high degree of test coverage.  So don't bother trying to build it yet.  It also still produces warnings, which I will fix.

The current version of libgit2 that is in Debian 7 (Wheezy) is 0.21.1-3~bpo7+1 which isn't the current upstream version.

The current version in Debian Unstable is 0.22.2-2.

What is available on your build hosts?  I'm assuming that you do an apt-get update && apt-get upgrade before releasing a dist?  If you support Debian Unstable, I'm currently the package maintainer for libgit2 so I can control the release to try and ensure that it doesn't break every few months when a new version comes out.  libgit2 moves quite quickly and do symbol changes with each release so its hard to make a library that is going to be backwards compatible, I would prefer to only support the current version if possible.

Sorry for the brain dump, but i figured giving you more information rather than less would help.

Thanks!

**Comment by russell** [comment]
Gosh, this is embarrassing cl-git actually support libgit 0.21.0 at the moment.

Also, despite this library having a dependency on libgit2 another option would be to build libgit2 from source.  It has very few dependencies.  I currently build the library when testing with travis-ci https://github.com/russell/cl-git/blob/master/.travis.yml and I would be happy to craft a script to build libgit2 in your environment.

**Comment by quicklisp** [comment]
I am using debian 7 for testing libraries. I don't mind installing libraries from source to build something.

**Comment by russell** [comment]
Ok cool.

What are your thoughts?  would you be happy if i provide a script that builds the library in the cl-git source dir?  That way i can use the same script for both travis-ci and quicklisp.

My concern is that otherwise you will have to update the local install of libgit2 every time it's released.

**Comment by quicklisp** [comment]
You write "don't bother trying to build it yet." When should I try?

I don't need a script for the library.

**Comment by russell** [comment]
You can have a crack.  I got it working on CCL today and building on ECL.  I have cleaned up all of the warnings.

So yes, if your happy to take on the task of building libgit2 it's ready to go!

**Comment by russell** [comment]
Thanks!  Checked the version in the latest Quicklisp yesterday,  works like a charm!
