### ISSUE TITLE
Please add check-it

### ISSUE THREAD

**Issue by DalekBaldwin** [quicklisp/quicklisp-projects#953]
https://github.com/DalekBaldwin/check-it

check-it is a QuickCheck/test.check/Hypothesis-style tool with a slick integrated DSL for defining data generators. Quicklisp already has cl-quickcheck, but that was really always just a bare-bones demo of this technique. check-it should be useful and pleasant enough to integrate into anybody's testing workflow.

**Comment by DalekBaldwin** [comment]
Just wondering, how close to the next release can I keep making changes and still reasonably expect them to make it into the distribution?

**Comment by quicklisp** [comment]
I try to make a release on the first weekend of each month. (This doesn't always happen, but that's my general goal.) The day of the release, I check out and build everything and if it all works, it becomes the new release.
