### ISSUE TITLE
Please add terminfo

### ISSUE THREAD

**Issue by npatrick04** [quicklisp/quicklisp-projects#954]
The terminfo package here has been split out from the linedit package with a few minor additions.
https://github.com/npatrick04/terminfo

nikodemus has indicated he plans to remove the terminfo package from linedit upon inclusion of this package per npatrick04/terminfo#1.

**Comment by 3b** [comment]
It looks like that has the `LOAD-TERMINFO` from the original version (http://users.actrix.co.nz/mycroft/terminfo.lisp), which has a bug on darwin compared to the linedit/hemlock versions. It calls `(char-name 0)`, which looks like it should be `(char name 0)`. (reported at http://paste.lisp.org/display/151278)

**Comment by npatrick04** [comment]
I must have merged that in when incorporating some fixes that Paul had made that weren't in the linedit version.  It is fixed now.
