### ISSUE TITLE
Please add cl-opsresearch

### ISSUE THREAD

**Issue by opsresearch** [quicklisp/quicklisp-projects#956]
The system cl-opsresearch is a collection of algorithms for Operations Research. The algorithms are grouped into subsystems so they can be selectively loaded. The subsystems are embedded so they don't pollute the quicklisp project namespace or cause user confusion.

The repository is located here: https://github.com/OpsResearchLLC/cl-opsresearch

**Comment by quicklisp** [comment]
This does not compile because it refers to QL:QUICKLOAD, a function that is not available in the test build environment. If you want to depend on another system, you should express that in the .asd file via the :depends-on list.

**Comment by opsresearch** [comment]
The compilation error has been fixed. Thanks for the feedback.

**Comment by quicklisp** [comment]
http://report.quicklisp.org/2015-07-07/failure-report/cl-opsresearch.html has some more failure. If you search down for "duplicate definition" you will see some conditions that signal full warnings and cause it not to build on SBCL.

**Comment by opsresearch** [comment]
The 16 full warnings about duplicate function names are fixed.

**Comment by quicklisp** [comment]
Ok, this is in Quicklisp now.
