### ISSUE TITLE
Please add quickapp

### ISSUE THREAD

**Issue by triclops200** [quicklisp/quicklisp-projects#957]
quickapp is a way of generating template buildapp projects using sbcl
https://github.com/triclops200/quickapp

**Comment by triclops200** [comment]
I've made some changes to my project since having this merged, will they be reflected in the release automatically, or does that need to be made manually?

**Comment by quicklisp** [comment]
The most recent version will be fetched for the release automatically.

**Comment by triclops200** [comment]
Thanks!
