### ISSUE TITLE
Please add clml

### ISSUE THREAD

**Issue by mmaul** [quicklisp/quicklisp-projects#958]
CL Machine-Learning is high performance and large scale statistical machine learning package written in Common Lisp developed at MSI. 

This repository contains is a authorized fork of the original CLML with the following goals in mind:
  + Remove dependent libraries available from the Quicklisp repository
  + Re-factor code to support Quicklisp packaging 
  + Organize code into independent systems based on functional category
  + Support for SBCL, CCL, LispWorks and Allegro Common Lisp
  + Improve documentation

**Repository location:** https://github.com/mmaul/clml

**NOTE** Compilation of CLML requires an expanded heap space in SBCL, heap space should be greater that or equal to 2640

     sbcl --dynamic-space-size 2640

This is a resubmission resolving previous compilation issues.

Thanks

**Comment by quicklisp** [comment]
http://report.quicklisp.org/2015-07-02/failure-report/clml.html has a list of the compilation problems I had. It's quite a variety.

**Comment by mmaul** [comment]
So the errors are in two classes. 

One problem is package resolution. When building with quicklisp-controller dependand packages are unable to be resolved. I setup quicklisp-controller and vereifed that this is happening on my system. So among the dependant packages are packages that are in quicklisp like ALEXANDRIA and ITERATE as packages part of CLML. Not sure why this is happening, (I haven't yet dug deep enough into quicklisp-controller to understand the build mechanisim). Any suggestions?

The other class of erros are resulting from the *default-float-reader-format* not being set to 'double-float, this is done in clml.asd. Building clml.asd is them method used to compile CLML, it pulls in the other systems that are part of CLML as dpendencies. Not knowing how quicklisp-controller works I assumed that it just went with <system name>.asd, as opposed to walking the source tree and processing every asd file. (The *default-float-reader-format* is set n clml.asd but not every where else, with the onus of setting this on the user if using clml systems ala-carte) I can fix this if necessary but....

Is there any way of providing a hint to quicklisp-controller on what systems (asd's) to process and what not to?

**Comment by quicklisp** [comment]
quicklisp-controller finds all .asd files, finds every system within each .asd file, and then, one by one, attempts to load each system. When loading, every other system file is known to ASDF and can be put in a :depends-on list.

So when you have a system defined like "clml-hjs.package" that does not :depend-on iterate, but its source code references the ITERATE package, you will get an error. 

Would it be possible to unify e.g. clml-hjs.package with clml-hjs, so that the depends-on list is used to load the prerequisites for package.lisp?

The missing SB-CLTL2 needs to be in a :depends-on list as well. Is that package unconditionally required to load CLML? Does that mean CLML only works on sbcl?

**Comment by mmaul** [comment]
I have sucessfully built CLML with quicklisp-controller.

I did run into some issues with bordeaux-threads/source.txt and anaphora/source.txt not updating because commonlisp-net is doing HTTP to HTTPS redirect. (I have updated all source.txt files referencing comon-lisp.net where the method was HTTP in a fork of quicklisp-projects and issued a pull request to quicklisp-projects)

To answer your questions:
>Would it be possible to unify e.g. clml-hjs.package with clml-hjs, so that the depends-on list is used to load the prerequisites for package.lisp?

Yes, done for clml.hjs and all other system definitions.

>The missing SB-CLTL2 needs to be in a :depends-on list as well. Is that package unconditionally required to load CLML? 

Only when building on SBCL.

>Does that mean CLML only works on sbcl?

No, CLML works on SBCL, CCL verified, Lispworks and Allegro needs to be tested but should work. CLASP is something I'm looking at adding support for.  As for other lisps support should be possible with a little work (If people express entrest on other CLML on other lisps I will consider working on it).

**Comment by guicho271828** [comment]
if possible, you could consider replacing sb-cltl2 with introspect-environment, a compatibility layer to CLtL2  environment, which is already in quicklisp.

**Comment by quicklisp** [comment]
Everything builds for me, thanks for the updates!

A lot of system definitions have no :description and other metadata. Could you please add descriptions to as many systems as possible?

**Comment by mmaul** [comment]
Added system definition descriptions and metadata for all systems. 
Removed gratuitious sb-* system loads.
Using introspect-environment in place of implementation specific introspection facilities where possible.
