### ISSUE TITLE
Please add TIFF4CL

### ISSUE THREAD

**Issue by josrr** [quicklisp/quicklisp-projects#963]
http://wcp.sdf-eu.org/software/tiff4cl-20150716T215800.tbz
TIFF4CL is a library to read TIFF file tags leaving the actual image data alone.

**Comment by josrr** [comment]
Please, can I have an answer for this issue? I think the lack of it has to do with retrospectiff, but the two libraries does not have the same purpose. TIFF4CL is only for read the file format metadata and not for reading and writing TIFF files.

**Comment by quicklisp** [comment]
It will be in the next release of Quicklisp, early next week.

**Comment by josrr** [comment]
Ok, thnaks.
