### ISSUE TITLE
Please add cl-liballegro

### ISSUE THREAD

**Issue by kalouantonis** [quicklisp/quicklisp-projects#971]
Hosted on Github at: https://github.com/resttime/cl-liballegro

It's a well maintained and well written binding to the [allegro game library.](http://alleg.sourceforge.net/)

The project should be pretty straight forward to add as it already has a [cl-liballegro.asd](https://github.com/resttime/cl-liballegro/blob/master/cl-liballegro.asd) file and a well defined [package description](https://github.com/resttime/cl-liballegro/blob/master/allegro/package.lisp). 

The [licence](http://alleg.sourceforge.net/license.html) is the same as the original Allegro library.

Thanks for your time.

P.S. Note that I'm not the package maintainer.

**Comment by quicklisp** [comment]
It doesn't build for me in SBCL due to a package lock issue. constants.lisp defines REQUIRE as a constant.

http://report.quicklisp.org/2015-07-24/failure-report/cl-liballegro.html has a log.

**Comment by kalouantonis** [comment]
Ok, thanks. I'll file an issue on cl-liballegro and see if the author is willing to fix it.

**Comment by resttime** [comment]
Hello, I'm the author of cl-liballegro and I believe I've made the proper changes that will fix the build.

**Comment by quicklisp** [comment]
What allegro library do I need to use to get cl-liballegro to work? I tried installing 4.4.1.1, but that built something called "liballeg.so". I still can't build cl-liballegro with that installed.

**Comment by resttime** [comment]
The 4.4 version of Allegro is too old since the bindings are intended for the more modern 5.0 version which underwent significant changes to be more modern. Try again with a [5.0.x release](http://alleg.sourceforge.net/download.html) and let me know how it goes. 

On a side note, I'm excited to see my first Common Lisp project on the way to being available in quicklisp. Yayifications!

**Comment by quicklisp** [comment]
What is the license on cl-liballegro code?

**Comment by resttime** [comment]
I will use the original license of the Allegro 5 library from a recommendation to avoid confusion: http://alleg.sourceforge.net/license.html

Does that work? I'm not quite sure how licenses are done.

**Comment by quicklisp** [comment]
That works. Can you please update the system file to add a :license option?

**Comment by resttime** [comment]
Okay, I added it in.
