### ISSUE TITLE
Please add Geneva

### ISSUE THREAD

**Issue by eugeneia** [quicklisp/quicklisp-projects#977]
Geneva is "the portable document preparation system": https://github.com/inters/geneva

Depends on: #976 #975 #974 #973

**Comment by eugeneia** [comment]
Might be worth noting that Geneva provide several ASDF systems, but `open-geneva` should be considered the "main system" (it loads all subsystems).

**Comment by quicklisp** [comment]
> Might be worth noting that Geneva provide several ASDF systems, but `open-geneva` should be considered the "main system" (it loads all subsystems).

If there are multiple systems, my build system will try to load them
each independently, and if they don't load, they aren't indexed in
Quicklisp.

geneval-latex and geneva-tex both fail to load directly with this error:

    The name "FILE-TYPES" does not designate any package

**Comment by eugeneia** [comment]
> geneval-latex and geneva-tex both fail to load directly with this error:

Oops. That was a missing dependency in geneva-tex. Should be fixed now. Sorry for the lazy testing on my part.
