### ISSUE TITLE
Please add macrodynamics

### ISSUE THREAD

**Issue by DalekBaldwin** [quicklisp/quicklisp-projects#982]
https://github.com/DalekBaldwin/macrodynamics

It's yet another language extension for writing language extensions.

I'll be making some improvements to check-it that depend on this functionality, so I'd like to make sure it gets into Quicklisp at the same time.

**Comment by quicklisp** [comment]
Can you please add a :description to macrodynamics.asd?

**Comment by DalekBaldwin** [comment]
Added.
