### ISSUE TITLE
Request to add cl-disque

### ISSUE THREAD

**Issue by CodyReichert** [quicklisp/quicklisp-projects#986]
This is a Common Lisp client for interacting with [Disque](https://github.com/antirez/disque).

(Note that the test suite requires a Disque server running locally, if you plan on running it).

Author: CodyReichert
URL: https://github.com/CodyReichert/cl-disque

**Comment by quicklisp** [comment]
Can you please add a sentence or so on what a Disque server is?

**Comment by CodyReichert** [comment]
Good point - I added some more info to the README. To be thorough I'll put it here too:

> Disque is an in-memory job queue and message broker. It’s distributed and fault-tolerant so it works as a middle layer among processes that want to exchange messages.

> Learn more about message queues here, and more about the Disque implementation here.

> cl-disque provides a client for working with Disque through sending and receiving jobs and commands.

Thanks
