### ISSUE TITLE
Please add zenekindarl

### ISSUE THREAD

**Issue by KeenS** [quicklisp/quicklisp-projects#987]
This is a fast precompiling template engine.
https://github.com/KeenS/zenekindarl

**Comment by quicklisp** [comment]
Why does the chart say "arrows"?

How does it compare to [html-template](http://weitz.de/html-template/)?

**Comment by KeenS** [comment]
Its original name was "arrows" but because people call it as "zenekindarl", I renamed it. Because the chart was contributed one, I'm not able to change the title.

Zenekindarl is web targeted and flexible compared to html-template. It auto escapes variables (this is mandatory for web template engine). It have varies backends such as string, octets, {string, octet}streams, and fastio for present.

**Comment by quicklisp** [comment]
html-template also auto-escapes variables. 

It seems a little unfair to compare speed to a Python program. html-template also precompiles. It would be interesting to see how zenekindarl speed matches up to it.
