### ISSUE TITLE
Please add Elb-Log

### ISSUE THREAD

**Issue by Rudolph-Miller** [quicklisp/quicklisp-projects#989]
Elb Log is an [ELB](https://aws.amazon.com/elasticloadbalancing/) log manager for Common Lisp.
https://github.com/Rudolph-Miller/elb-log

**Comment by bhyde** [comment]
Maybe, add the phrase “elastic load balancer” to the readme and doc?

**Comment by Rudolph-Miller** [comment]
Thanks!
I added "Elastic Load Balancing" to README.md.
