### ISSUE TITLE
Please add data-omnivore

### ISSUE THREAD

**Issue by maxmaeteling** [quicklisp/quicklisp-projects#990]
Which is available from: https://github.com/tpapp/data-omnivore

This library is the bridge between csv-files (from cl-csv) and cl-data-frames.

**Comment by quicklisp** [comment]
The README says it's experimental, and it hasn't been updated in 3 years. Are you sure it's good to add to Quicklisp?

**Comment by maxmaeteling** [comment]
It is as old (as updated) as cl-data-frames, but after some work with it I realized that it is probably not the right library for me so I think you can drop this request if there is nobody else supporting it. Sorry for the hassle!

**Comment by quicklisp** [comment]
No problem. If you need it in the future, feel free to reopen.
