### ISSUE TITLE
Please update xml-emitter

### ISSUE THREAD

**Issue by VitoVan** [quicklisp/quicklisp-projects#997]
https://github.com/VitoVan/xml-emitter

It is taken from Peter Scott, I've emailed him about this. Now it should be updated as xml-emitter-1.0.3.

Thank you.

**Comment by quicklisp** [comment]
Why is xml-emitter-1.0.3.tar.gz part of the git repo?

Also, please add a :description to the system definition.

**Comment by VitoVan** [comment]
The project has been updated, thank you.
