### ISSUE TITLE
Please add Lispbuilder to quicklisp

### ISSUE THREAD

**Issue by Txellenne** [quicklisp/quicklisp-projects#998]
Hi 
I am an user and I have got interest in the [Lispbuilder](https://github.com/lispbuilder/lispbuilder) library. It would be easy to explore on creating gui interfaces on lisp for learning purposes, so I make this petition following guidelines from the [quiclklisp site faq section](http://blog.quicklisp.org/2015/01/getting-library-into-quicklisp.html). I would like to be able to add this library from Quicklisp. 
Accordingly documentation the project is under MIT-style license, It is cross platform but its availability on Linux is some [confusing](https://github.com/lispbuilder/lispbuilder/issues/41). 
I hope this was possible.
I would appreciate it so much. 
Here the source: 
https://github.com/lispbuilder/lispbuilder

**Comment by bhyde** [comment]
On 14 Sep 2015, at 9:57, Txellenne wrote:
> Hi
> I am an user and I have got interest in the 
> [Lispbuilder](https://github.com/lispbuilder/lispbuilder) library. It 
> would be easy to explore on creating gui interfaces on lisp for 
> learning purposes, so I make this petition following guidelines from 
> the [quiclklisp site faq 
> section](http://blog.quicklisp.org/2015/01/getting-library-into-quicklisp.html). 
> I would like to be able to add this library from Quicklisp.
> Accordingly documentation the project is under MIT-style license, It 
> is cross platform but its availability on Linux is some 
> [confusing](https://github.com/lispbuilder/lispbuilder/issues/41).
> I hope this was possible.
> I would appreciate it so much.
> Here the source:
> https://github.com/lispbuilder/lispbuilder
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/quicklisp/quicklisp-projects/issues/998

Good news: (ql:system-apropos "lispbuilder") shows many variations and 
such of lispbuilder

**Comment by Txellenne** [comment]
Hey!, yeap. Thanks!! :flushed:

**Comment by quicklisp** [comment]
It should already be there.
